### ISSUE TITLE
Referring to a trait when it is already imported renamed/hidden (`use foo::Foo as _`) can't be autofixed.

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust-analyzer#10197]
```rust
mod hidden {
    pub trait Foo {
        fn foo(&self);
    }
}
use hidden::Foo as _;

fn testing(x: impl Foo) {
    x.foo();
}
```

This program produces the expected error “cannot find trait `Foo` in this scope”. rust-analyzer offers a fix “Import `hidden::Foo`”, but applying that fix makes no changes to the source code. It would be better if it deleted “as _” from the existing `use`.

(If the item is a type instead of a trait, then it instead adds a separate `use hidden::Foo;`, which is correct but untidy.)

Relatedly, if `use hidden::Foo as _;` is replaced by `use hidden::Foo as Bar;` then there is no auto-fix offered at all (though rustc is still reporting “consider importing this trait:”). In this case, it would make sense to offer changing `x: impl Foo` to `x: impl Bar`. That would be an enhancement rather than a bug, though. (This happens for both traits and types.)

**Comment by lnicola** [comment]
Strange, I get:

```
mod hidden {
    pub trait Foo {
        fn foo(&self);
    }
}
use hidden::Foo as _;

use self::hidden::Foo;

fn testing(x: impl Foo) {
    x.foo();
}
```

**Comment by lnicola** [comment]
I also get:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 4 but the index is 16', crates/ide_db/src/line_index.rs:106:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:69:5
   3: ide_db::line_index::LineIndex::offset
   4: rust_analyzer::from_proto::text_range
   5: rust_analyzer::handlers::handle_code_action
   6: std::panicking::try
   7: <F as threadpool::FnBox>::call_box
```

**Comment by kpreid** [comment]
> Strange, after triggering the assist I get:

Further environment info in case it's useful:

* rust-analyzer version 0.2.735
* Rust version 1.55.0 (but this isn't a new bug)
* Test project for the above example was a library crate and I wrote the code directly in `lib.rs`.

**Comment by lnicola** [comment]
I'm on a source build (21a1ced8b64a70dd22d215c16d72968bde10cab2), but I don't think there were any changes related to auto-import in the last four days.

**Comment by kpreid** [comment]
This bug is still occurring, with rust-analyzer `0.4.1390-standalone (04850a192 2023-02-02)` and VS Code extension v0.4.1390.

**Comment by Veykril** [comment]
Hmm, this works fine for me (aside from not fixing up the `as _` import itself). ![Code_oJmdV7eS1a](https://user-images.githubusercontent.com/3757771/216683767-21725c92-7e69-4da5-810d-362ced4833d8.gif)

Assuming you mean the `Import X` quickfix, do you have any import related settings changed from the defaults?

**Comment by kpreid** [comment]
> Assuming you mean the `Import X` quickfix,

Yes.

> do you have any import related settings changed from the defaults?

I just tried again after clearing all of my VS Code settings (user and workspace settings files both empty) and got the same result: no changes.

**Comment by Veykril** [comment]
What's your VSCode version? And r-a I assume you are on a latest stable or nightly

**Comment by kpreid** [comment]
* VS Code:

    ```
    Version: 1.75.0
    Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
    Date: 2023-02-01T15:24:42.903Z (3 days ago)
    ```
* rust-analyzer extension: `v0.4.1391 Pre-Release`
* rust-analyzer version: `0.4.1391-standalone (3bc33c7e9 2023-02-03)`
* macOS Monterey 12.6.3 (21G419)

But as per the original issue date, this has been around since 2021, so it isn't any recent appearance.

**Comment by Veykril** [comment]
Yes, I know. Was wondering whether it might've been a VSCode issue caused by an old client. This is rather odd that its failing just for you though ... It looks like resolving the completion fails for you which means this returns None/an empty vec for some reason 🤔 https://github.com/rust-lang/rust-analyzer/blob/3bc33c7e9f041c5aef69a5c33b3d29d19a341ece/crates/ide-completion/src/lib.rs#L207-L252

**Comment by kpreid** [comment]
This now behaves for me [as @Veykril described above](https://github.com/rust-lang/rust-analyzer/issues/10197#issuecomment-1416268786), so the bug has been fixed, or gone away, or my configuration changed.
