### ISSUE TITLE
GAT + const generics crash v2

### ISSUE THREAD

**Issue by spookyvision** [rust-lang/rust-analyzer#12193]
unfortunately, I'm hitting another of those… (previously: #11769)
```rust
#![feature(generic_associated_types)]

trait Collection {
    type Item;
    type Member<T>: Collection<Item = T>;
    fn add(&mut self, value: Self::Item) -> Result<(), Self::Error>;
}


struct ConstGen<T, const N: usize> {
    data: [T; N],
}

impl<T, const N: usize> Collection for ConstGen<T, N> {
    type Item = T;
    type Member<U> = ConstGen<U, N>;
}
```

**rust-analyzer version**: `5d5bbec9b 2022-05-08 nightly`

**rustc version**: `rustc 1.62.0-nightly (e1b71feb5 2022-05-03)`

**relevant settings**: `None`

crash log:

```code
Panic context:
> 
version: 5d5bbec9b 2022-05-08 nightly
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/Users/ace/play/gat-coll/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 17,
            character: 0,
        },
    },
}

thread '<unnamed>' panicked at 'mismatched kinds in substitution', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-ir-0.82.0/src/fold/subst.rs:64:22
stack backtrace:
   0: std::panicking::begin_panic
   1: <chalk_ir::fold::subst::Subst<I> as chalk_ir::fold::Folder<I>>::fold_free_var_ty
   2: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with
   3: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with
   4: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   5: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with
   6: <chalk_ir::Ty<I> as chalk_ir::fold::SuperFold<I>>::super_fold_with
   7: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::GenericArg<I>>::fold_with
   8: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   9: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::Fold<I> for chalk_ir::Substitution<I>>::fold_with
  10: chalk_ir::fold::subst::Subst<I>::apply
  11: chalk_ir::Binders<T>::substitute
  12: chalk_solve::split::Split::impl_parameters_and_projection_from_associated_ty_value
  13: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
  14: chalk_solve::clauses::push_program_clauses_for_associated_type_values_in_impls_of
  15: chalk_recursive::solve::SolveIterationHelpers::solve_from_clauses
  16: chalk_recursive::solve::SolveIteration::solve_iteration
  17: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  18: chalk_recursive::fulfill::Fulfill<I,Solver>::prove
  19: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  20: chalk_recursive::solve::SolveIterationHelpers::solve_from_clauses
  21: chalk_recursive::solve::SolveIteration::solve_iteration
  22: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  23: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  24: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  25: salsa::runtime::Runtime::execute_query_implementation
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::read
  28: salsa::QueryTable<Q>::get
  29: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  30: hir_ty::db::trait_solve_wait
  31: <DB as hir_ty::db::HirDatabase>::trait_solve
  32: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  33: hir_ty::infer::unify::InferenceTable::normalize_projection_ty
  34: <hir_ty::fold_tys_and_consts::TyFolder<F> as chalk_ir::fold::Folder<hir_ty::interner::Interner>>::fold_ty
  35: hir_ty::infer::infer_query
  36: salsa::runtime::Runtime::execute_query_implementation
  37: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  38: salsa::derived::slot::Slot<Q,MP>::read
  39: salsa::QueryTable<Q>::get
  40: <DB as hir_ty::db::HirDatabase>::infer_query
  41: hir_ty::db::infer_wait
  42: hir::source_analyzer::SourceAnalyzer::new_for_body
  43: hir::semantics::SemanticsImpl::analyze_impl
  44: hir::semantics::SemanticsImpl::type_of_pat
  45: ide::inlay_hints::hints
  46: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  47: ide::inlay_hints::inlay_hints
  48: std::panicking::try
  49: rust_analyzer::handlers::handle_inlay_hints
  50: std::panicking::try
  51: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 3:38:50 AM] Request textDocument/inlayHint failed.
  Message: request handler panicked: mismatched kinds in substitution
  Code: -32603 

```

**Comment by bugadani** [comment]
I think I'm getting hit by this error (it appeared when I first introduced a const generic associated type in my code base), but with the following backtrace:

```
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', crates\hir-ty\src\utils.rs:272:18
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:48
   3: hir_ty::utils::Generics::find_param
   4: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
   5: hir_ty::lower::TyLoweringContext::lower_ty_ext
   6: hir_ty::lower::TyLoweringContext::substs_from_path_segment
   7: hir_ty::lower::TyLoweringContext::substs_from_path_segment
   8: hir_ty::lower::TyLoweringContext::lower_type_bound
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  10: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::size_hint
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  12: hir_ty::chalk_db::associated_ty_data_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  15: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  17: hir_ty::db::HirDatabaseGroupStorage__::maybe_changed_since
  18: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  19: salsa::derived::slot::MemoRevisions::validate_memoized_value
  20: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  21: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  23: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  24: salsa::derived::slot::MemoRevisions::validate_memoized_value
  25: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  26: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  27: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  28: hir_ty::db::HirDatabaseGroupStorage__::maybe_changed_since
  29: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  30: salsa::derived::slot::MemoRevisions::validate_memoized_value
  31: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  32: salsa::derived::slot::Slot<Q,MP>::read
  33: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  34: <DB as hir_ty::db::HirDatabase>::infer_query
  35: hir_ty::db::infer_wait
  36: hir::source_analyzer::SourceAnalyzer::new_for_body
  37: hir::semantics::SemanticsImpl::analyze_impl
  38: ide_db::defs::NameRefClass::classify
  39: ide_db::search::FindUsages::search
  40: ide_db::search::FindUsages::search
  41: ide::references::find_all_refs::{{closure}}::{{closure}}
  42: ide::ssr::ssr_assists
  43: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  44: ide::references::find_all_refs
  45: ide::annotations::resolve_annotation
  46: std::panicking::try
  47: rust_analyzer::handlers::handle_code_lens_resolve
  48: std::panicking::try
  49: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:01:22] Request codeLens/resolve failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
```

It's moderately annoying because an error popup shows up basically with every keystroke I make.

**Comment by N3xed** [comment]
Here's another example:
```rust
pub struct ISRExecutor<'a, const C: usize, N, W, S = ()> {
    queue: PhantomData<[(); C]>,
    notify_factory: N,
    wait: W,
    _sendable: PhantomData<S>,
    _marker: PhantomData<core::cell::UnsafeCell<&'a ()>>,
}

impl<'a, N, W, S, const C: usize> Spawner<'a> for ISRExecutor<'a, C, N, W, S> {
    type Error = ();

    type Task<T>
        = ()
        where
            T: 'a;

    fn spawn<F, T>(&mut self, fut: F) -> Result<Self::Task<T>, Self::Error>
    where
        F: std::future::Future<Output = T> + Send + 'a,
        T: 'a,
    {
        todo!()
    }
}

pub trait Spawner<'a> {
    type Error: std::fmt::Debug;
    type Task<T>
    where
        T: 'a;

    fn spawn<F, T>(&mut self, fut: F) -> Result<Self::Task<T>, Self::Error>
    where
        F: std::future::Future<Output = T> + Send + 'a,
        T: 'a;
}
```

Happens when:
- `Spawner` trait implementation for `ISRExecutor` has a const generics argument; or
- `type Task<T>` has a `where` bound.

This crash makes working in that file almost impossible.
