### ISSUE TITLE
Error while installing rust-analyzer extension

### ISSUE THREAD

**Issue by sainishwanth** [rust-lang/rust-analyzer#12248]
Trying to install it from the vscode extension market and I constantly get this error. I have rust-lang uninstalled and have also tried installing it manually which didn't help. This is on macOS (apple silicon m1) using the default apple silicon VsCode.

Here are the logs if it helps -> 

2022-05-14 11:00:45.417] [renderer5] [error] ["Error: Server returned 404","    at i (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:29:97869)","    at K.getManifestFromRawExtensionVersion (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:32001)","    at async K.getEngine (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:50:292)","    at async K.getCompatibleExtension (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:26721)","    at async O.checkAndGetCompatibleVersion (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:11657)","    at async O.installFromGallery (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:2840)"]

[2022-05-14 11:00:45.431] [renderer5] [error] Server returned 404: Error: Server returned 404
    at i (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:29:97869)
    at K.getManifestFromRawExtensionVersion (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:32001)
    at async K.getEngine (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:50:292)
    at async K.getCompatibleExtension (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:26721)
    at async O.checkAndGetCompatibleVersion (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:11657)
    at async O.installFromGallery (vscode-file://vscode-app/private/var/folders/hf/y10yygrx7lb2177cn071tfn00000gn/T/AppTranslocation/0CA6E9DB-37E7-45E3-B437-6C25D332782B/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:2840)

**Comment by tresuke** [comment]
Maybe I'm looking in the wrong place...
Is this related to https://github.com/microsoft/vscode/issues/149518 ??

**Comment by lnicola** [comment]
Yeah, that sounds like a Marketplace error. Do you already have RA installed? Try removing and installing it again.

If not, you can download a VSIX from GitHub.

**Comment by sainishwanth** [comment]
I have already tried re installing it and also manually installing it via the VSIX file, neither of them seemed to have worked. I assumed it had to do something with this extension since all my other extensions seem to be installing and running fine.

**Comment by Veykril** [comment]
Try uninstalling, restarting VSCode then searching for the extension on the marketplace again, that *should* fix it.

**Comment by sainishwanth** [comment]
Thank you, updating VsCode seemed to have fixed it. You're right it had something to do with VsC.
