### ISSUE TITLE
Cannot activate rust-analyzer: Unable to write to User Settings because rust-analyzer.hoverActions.references.enable is not a registered configuration.

### ISSUE THREAD

**Issue by PureWhiteWu** [rust-lang/rust-analyzer#12249]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)

![image](https://user-images.githubusercontent.com/3314335/168413986-4cd77125-b6f6-4618-9e89-776528c99947.png)

```
 $ ~/.vscode/extensions/rust-lang.rust-analyzer-0.3.1051-darwin-arm64/server  ./rust-analyzer --version
rust-analyzer 94fa8a653 2022-05-12 nightly
```

**rustc version**: (eg. output of `rustc -V`)

rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

OS: macOS 12.3 M1 Max

![image](https://user-images.githubusercontent.com/3314335/168413953-bf0f8bc5-8ec6-4c33-b223-51103e083b3c.png)

**Comment by QuiiBz** [comment]
Hello, I'm having the same issue in both local & remote extensions. Here's my full stacktrace:

```
[2022-05-14 06:50:03.871] [exthost] [error] Activating extension matklad.rust-analyzer failed due to an error:
[2022-05-14 06:50:03.871] [exthost] [error] Error: Unable to write to User Settings because rust-analyzer.hoverActions.run.enable is not a registered configuration.
    at b.toConfigurationEditingError (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2666:12734)
    at b.validate (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2666:15602)
    at b.doWriteConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2666:9059)
    at Object.factory (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2666:8915)
    at T.consume (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:71:15885)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:71:15700
    at new Promise (<anonymous>)
    at T.queue (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:71:15624)
    at b.writeConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2666:8884)
    at O.writeConfigurationValue (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2666:41744)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2666:27470
    at Array.map (<anonymous>)
    at O.updateValue (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2666:27458)

```

**Comment by Veykril** [comment]
Ye this is a bug with 0.3.1051. You can either fix it by updating to 0.3.1053 or by changing the `rust-analyzer.hoverActions.references` config key in your config.json to `rust-analyzer.hover.actions.references.enable` manually (and similar for other `hoverActions` configs)

**Comment by PureWhiteWu** [comment]
> Ye this is a bug with 0.3.1051. You can either fix it by updating to 0.3.1053 or by changing the `rust-analyzer.hoverActions.references` config key in your config.json to `rust-analyzer.hover.actions.references.enable` manually (and similar for other `hoverActions` configs)

Hello, seems that the latest release version is still v0.3.1051 in vscode extension market, could you please update it to v0.3.1053?

**Comment by Veykril** [comment]
The latest should be v0.3.1053 https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer

**Comment by PureWhiteWu** [comment]
> The latest should be v0.3.1053 https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer

Thanks! Seems that there's cache somewhere so the version here is still v0.3.1051.

I will wait for that cache to expire.

**Comment by carlgieringer** [comment]
Installing the 'pre-release' version from VS Code's UI seemed to fix this for me.

**Comment by Wyvern** [comment]
Just updated the release version, got the same problem!

Still v0.3.1051, please fix it ASAP.
