### ISSUE TITLE
vscode remote uses the local architecture instead of the remote architecture

### ISSUE THREAD

**Issue by degaart** [rust-lang/rust-analyzer#12299]
Installing rust-analyzer using vscode remote development uses the local architecture instead of the remote one.

Relevant vscode console logs:

```
INFO [5/18/2022, 9:55:47 AM]: Using server binary at /root/.vscode-server/extensions/matklad.rust-analyzer-0.3.1051/server/rust-analyzer
ERROR [5/18/2022, 9:55:47 AM]: Bootstrap error [Error: Failed to execute /root/.vscode-server/extensions/matklad.rust-analyzer-0.3.1051/server/rust-analyzer --version
	at xS (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.1051/out/main.js:85:2158)
	at async PS (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.1051/out/main.js:84:810)
	at async av (/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.1051/out/main.js:84:641)
	at async _activate (/root/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (/root/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
	at async _initialize (/root/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)]
```

Checking the file /root/.vscode-server/extensions/matklad.rust-analyzer-0.3.1051/server/rust-analyzer gives:

```
$ file /root/.vscode-server/extensions/matklad.rust-analyzer-0.3.1051/server/rust-analyzer
/root/.vscode-server/extensions/matklad.rust-analyzer-0.3.1051/server/rust-analyzer: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
```

which is uses the local architecture/executable format instead of the remote.

**rust-analyzer version**: v0.3.1051

**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**relevant settings**:

- Local: aarch64 macOS 12.4
- Remote: x86_64 debian 10.12

**Comment by SimonSapin** [comment]
I’m affected by this as well. Replacing the binary in question on the remote machine with one downloaded from https://github.com/rust-lang/rust-analyzer/releases seems to work. However I don’t know how version numbers for the VSCode extension (currently v0.2.1048) should map to date-based version numbers on GitHub.

**Comment by bjorn3** [comment]
I think this should be fixed on vscode's side. IMO vscode should install the extension variant for whichever platform the extension host is running on, not whichever variant is locally installed.

**Comment by degaart** [comment]
Tried with vscode-insider 1.68.0-insider and the issue did not occur. Seems it will be fixed in the next vscode release.
