### ISSUE TITLE
'internal error: entered unreachable code: unsize_array with non-array ?138', crates/hir-ty/src/method_resolution.rs:521:21

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust-analyzer#12348]
Spotted in https://github.com/rust-lang/rust-analyzer/issues/12182.

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code: unsize_array with non-array ?138', crates/hir-ty/src/method_resolution.rs:521:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/daf68b1f766e67ffe040260b15c218301853386a/library/core/src/panicking.rs:142:14
   2: hir_ty::method_resolution::ReceiverAdjustments::apply
   3: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
   5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  13: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  14: hir_ty::infer::infer_query
  15: salsa::runtime::Runtime::execute_query_implementation
  16: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<Q,MP>::read
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  19: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  20: hir_ty::db::infer_wait
  21: hir::source_analyzer::SourceAnalyzer::new_for_body
  22: hir::semantics::SemanticsImpl::analyze_impl
  23: hir::semantics::SemanticsImpl::resolve_path
  24: ide_db::defs::NameRefClass::classify
  25: ide_db::search::FindUsages::search
  26: ide_db::search::FindUsages::all
  27: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  28: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  29: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  30: ide::references::find_all_refs
  31: std::panicking::try
  32: ide::Analysis::find_all_refs
  33: rust_analyzer::handlers::handle_references
  34: std::panicking::try
  35: <F as threadpool::FnBox>::call_box
```

**Comment by flodiebold** [comment]
Hmm probably needs a `resolve_ty_shallow` in some place.

**Comment by lowr** [comment]
Haven't tested myself, but this might've been fixed by #13624.

**Comment by ChayimFriedman2** [comment]
Unlikely to be reproducible again.
