### ISSUE TITLE
Request textDocument/completion failed

### ISSUE THREAD

**Issue by OneKnightOnly** [rust-lang/rust-analyzer#12408]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 7e95c14ea 2022-05-17 stable

**rustc version**: (eg. output of `rustc -V`)
rustc 1.60.0 (7737e0b5c 2022-04-04)

Error message:
Request textDocument/completion failed
Source: rust-analyzer (Extension)

VSCode keeps popping up with this error message every time a period is entered following a number, like this 0.
This message is very annoying and doesn't go away until you manually click the close button.
Is there any way to disable this message from popping up?

**Comment by lnicola** [comment]
Try updating the extension.

**Comment by OneKnightOnly** [comment]
The extension is already updated, if I click the "go to output" button on the popup, theres this extra information available.

[Error - 5:28:59 pm] Request textDocument/completion failed.
  Message: request handler panicked: index out of bounds: the len is 5 but the index is 27
  Code: -32603

**Comment by IAIAE** [comment]
same, how to solve this? 
i update the rust-analyzer version, not work; and re-installl it, not work; and update the rustup, not work.

**Comment by Perodactyl** [comment]
Same here, just randomly popped up and won't go away at all.

**Comment by TheWolfKnight** [comment]
I just had the same problem when I lunched VS Code with MINGW64, I then switch to the standard CMD terminal where I do not get this error.

**Comment by vdods** [comment]
I'm getting this problem as well, simply while typing Rust code in certain cases.  I'd just like an option to disable the popup.

**Comment by zayman2045** [comment]
Having the same problem.

**Comment by Veykril** [comment]
Please open a new issue with the general info, rust version, rust-analyzer version and ideally a reproducing sample code

**Comment by dengyunsheng250** [comment]
i have met this also.

**Comment by kkettinger** [comment]
Have the same issue. I'm currently doing the guessing example in the rust book, and auto completion doesn't work.

This is the error:
```
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-solve-0.89.0\src\clauses\builtin_traits\fn_family.rs:90:55
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:117
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_recursive::solve::SolveIteration::solve_iteration
   7: chalk_recursive::solve::SolveIteration::solve_iteration
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: <DB as hir_ty::db::HirDatabase>::trait_solve_query::__shim
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_method_candidates_dyn
  20: hir_ty::method_resolution::iterate_method_candidates_dyn
  21: hir::Type::iterate_path_candidates_dyn
  22: hir::Type::iterate_path_candidates
  23: ide_completion::context::CompletionContext::iterate_path_candidates
  24: ide_completion::completions::pattern::complete_pattern_path
  25: ide_completion::completions
  26: std::panicking::try
  27: rust_analyzer::handlers::request::handle_completion
  28: std::panicking::try
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:12:37 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: 0.3.1541-standalone (2f1b7cedc 2023-06-04)
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/d%3A/Entwicklung/Repositories/rust/example-01/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 21,
            character: 25,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}
```

![grafik](https://github.com/rust-lang/rust-analyzer/assets/83078716/67bf4053-4cb6-4ce0-8ee1-a3e85a6861dc)

It happens in this minimal example, directly after writing the "." in "io::stdin()":
```
use std::io;

fn main() {
    io::stdin().
}
```

**Comment by ysy** [comment]
I encountered  same issue.  "**thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value',**". 

Reinstall the extension fix the problem.  I guess the index database might be damaged when i was installing new crates.

**Comment by ShayBox** [comment]
This is a constant problem and has been since I started using the rust-analyzer extension awhile ago, any time you add new dependencies or save the file too quickly after editing or if you have auto-fix on save, that's when it shows up the most. I see it many times every day, it'll never be fixed.

**Comment by flodiebold** [comment]
"Request textDocument/completion failed" is just a generic error message that can be caused by any panic happening during analysis. The error causing the original report was fixed, it's not helpful to keep posting comments on this issue. If you encounter this issue, look at the error message and stack trace in the rust-analyzer output tab, check whether there's an *open* issue for this, and create a new one with a description how to reproduce the error if not.
