### ISSUE TITLE
Error with 'Inline into all callers' Code Action

### ISSUE THREAD

**Issue by kilbd** [rust-lang/rust-analyzer#12429]
I maintain a Rust extension for the Nova text editor by Panic. A user [reported an issue](https://github.com/kilbd/nova-rust/issues/30) when attempting to use the **Inline into all callers** Code Action with the following code in `main.rs`:

```rust
fn main() {
    let width1 = 30;
    let height1 = 50;
    println!(
        "The area of the rectangle is {} pixels.",
        rect_area(width1, height1),
    );
}

fn rect_area(width: u32, height: u32) -> u32 {
    width * height
}
```

The request for Code Actions with the cursor over `rect_area` got this response from Rust Analyzer:

```json
{
  "jsonrpc":"2.0",
  "id":5,
  "result":[
    {
      "title":"Inline into all callers",
      "kind":"refactor.inline",
      "edit":{
        "documentChanges":[
          {
            "textDocument":{"uri":"file:///Users/xxxx/issue-30/src/main.rs","version":1},
            "edits":[
              {"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":10}},"newText":"width1"},
              {"range":{"start":{"line":4,"character":10},"end":{"line":4,"character":26}},"newText":" "},
              {"range":{"start":{"line":4,"character":26},"end":{"line":4,"character":26}},"newText":"*"},
              {"range":{"start":{"line":4,"character":26},"end":{"line":4,"character":26}},"newText":" "},
              {"range":{"start":{"line":4,"character":26},"end":{"line":4,"character":26}},"newText":"height1"},
              {"range":{"start":{"line":9,"character":0},"end":{"line":11,"character":1}},"newText":""}
            ]
          }
        ]
      }
    },
    {
      "title":"Generate a documentation template",
      "kind":"",
      "edit":{"documentChanges":[
        {
          "textDocument":{"uri":"file:///Users/xxxx/issue-30/src/main.rs","version":1},
          "edits":[
            {"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":0}},"newText":"/// .\n"}
          ]
        }
      ]
    }
  }
  ]
}Content-Length: 188
```

Following these instructions, Nova overwrites a portion of the string on line 5 instead of the function call on line 6.

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command) `rust-analyzer 84be2eaf9 2022-05-23 stable`

**rustc version**: (eg. output of `rustc -V`) `rustc 1.61.0 (fe5b13d68 2022-05-18)`

**Comment by flodiebold** [comment]
Seems the code action doesn't handle usages in macro expansions correctly.

**Comment by antonilol** [comment]
i also have this issue, to add, depending on context it might produce an error or weird behavior:

case 1:
```rust
fn function() -> &'static str {
    "world"
}

fn main() {
    println!("hello {}", function());
}
```

case 2:
```rust
fn filler() {
    let a = 1;
    let a = 1;
}

fn function() -> &'static str {
    "world"
}

fn main() {
    println!("hello {}", function());
}
```

in both cases 'inline into all callers' is used on `function`, in the first case where there is no code before `function`, i get a notification (vscode) with "request handler panicked: assertion failed: check_disjoint_and_sort(indels)", in the second case the function body of `function` is placed somewhere in `filler`:

```rust
fn filler() {
    let a = 1;
  "world"1;
}



fn main() {
    println!("hello {}", function());
}
```

panic log (case 1):

```
thread 'Worker' panicked at crates/text-edit/src/lib.rs:194:5:
assertion failed: check_disjoint_and_sort(indels)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:127:5
   3: text_edit::assert_disjoint_or_equal
   4: syntax::algo::TreeDiff::into_text_edit
   5: ide_db::source_change::SourceChangeBuilder::commit
   6: ide_db::source_change::SourceChangeBuilder::finish
   7: ide_assists::assist_context::Assists::add_impl
   8: ide_assists::assist_context::Assists::add
   9: ide_assists::handlers::inline_call::inline_into_callers
  10: ide_assists::assists
  11: salsa::Cancelled::catch
  12: ide::Analysis::assists_with_fixes
  13: rust_analyzer::handlers::request::handle_code_action_resolve
  14: std::panicking::try
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.4.1830-standalone
request: codeAction/resolve CodeAction {
    title: "Inline into all callers",
    group: None,
    kind: Some(
        CodeActionKind(
            "refactor.inline",
        ),
    ),
    command: None,
    edit: None,
    is_preferred: None,
    data: Some(
        CodeActionData {
            code_action_params: CodeActionParams {
                text_document: TextDocumentIdentifier {
                    uri: Url {
                        scheme: "file",
                        cannot_be_a_base: false,
                        username: "",
                        password: None,
                        host: None,
                        port: None,
                        path: "/home/antoni/code/rust-playground/src/main.rs",
                        query: None,
                        fragment: None,
                    },
                },
                range: Range {
                    start: Position {
                        line: 0,
                        character: 9,
                    },
                    end: Position {
                        line: 0,
                        character: 9,
                    },
                },
                context: CodeActionContext {
                    diagnostics: [],
                    only: Some(
                        [
                            CodeActionKind(
                                "refactor",
                            ),
                        ],
                    ),
                    trigger_kind: Some(
                        Invoked,
                    ),
                },
                work_done_progress_params: WorkDoneProgressParams {
                    work_done_token: None,
                },
                partial_result_params: PartialResultParams {
                    partial_result_token: None,
                },
            },
            id: "inline_into_callers:RefactorInline:0",
        },
    ),
}

thread 'Worker' panicked at crates/text-edit/src/lib.rs:194:5:
assertion failed: check_disjoint_and_sort(indels)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:127:5
   3: text_edit::assert_disjoint_or_equal
   4: syntax::algo::TreeDiff::into_text_edit
   5: ide_db::source_change::SourceChangeBuilder::commit
   6: ide_db::source_change::SourceChangeBuilder::finish
   7: ide_assists::assist_context::Assists::add_impl
   8: ide_assists::assist_context::Assists::add
   9: ide_assists::handlers::inline_call::inline_into_callers
  10: ide_assists::assists
  11: salsa::Cancelled::catch
  12: ide::Analysis::assists_with_fixes
  13: rust_analyzer::handlers::request::handle_code_action_resolve
  14: std::panicking::try
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lnicola** [comment]
Worked around in #16678.

**Comment by antonilol** [comment]
https://github.com/rust-lang/rust-analyzer/issues/12429#issuecomment-1932509992
the 2 cases in this comment now both do nothing: no panic, no code placed on random places but also no inlining, should i make a new bug report?
