### ISSUE TITLE
Proc macro server crashed

### ISSUE THREAD

**Issue by Spanfile** [rust-lang/rust-analyzer#12600]
I don't think this is a duplicate of the other macro issues, I haven't seen this error message in them:
```
thread 'MacroExpander' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/handle.rs:22:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::handle::InternedStore<T>::new
   5: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::client::HandleStore<S>::new
   6: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::server::run_server
   7: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::server::<impl proc_macro_srv::abis::abi_1_63::proc_macro::bridge::client::Client<(proc_macro_srv::abis::abi_1_63::proc_macro::TokenStream,proc_macro_srv::abis::abi_1_63::proc_macro::TokenStream),proc_macro_srv::abis::abi_1_63::proc_macro::TokenStream>>::run
   8: proc_macro_srv::abis::abi_1_63::Abi::expand
   9: proc_macro_srv::abis::Abi::expand
  10: proc_macro_srv::ProcMacroSrv::expand
  11: proc_macro_srv::cli::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Similarly to the other issues, the entire macro site is marked as an error with `failed to write request: Broken pipe (os error 32)`.

Happens with at least all serde derives, tracing `#[instrument]`, `#[async_trait]` and tonic's `include_proto!`.

**rust-analyzer version**: 0.0.0 (427061da1 2022-06-19)

**rustc version**: rustc 1.63.0-nightly (bb8c2f411 2022-06-19) on Arch Linux

**relevant settings**: rust-analyzer.procMacro.attributes.enable is true, no macros have been ignored.

**Comment by lnicola** [comment]
Confirmed, looks like another ABI change. As a workaround you can downgrade to a nightly from around 2022-06-08.

**Comment by lnicola** [comment]
This broke between 2022-06-18 and 2022-06-19.

**Comment by bjorn3** [comment]
There are probably going to be a couple of other abi breakages in the near future. There are several PR's affecting libproc_macro open at the moment.

**Comment by flodiebold** [comment]
@dacut That's a different problem, caused by using an x86 VSCode and an ARM Rust toolchain. In that case, yours is indeed a possible workaround. (The other option would be to just install an aarch64 VSCode build.) This is unrelated to the problem in this issue though.

**Comment by flodiebold** [comment]
@dacut It was a guess for the actual problem you're having, because the issue described here cannot be fixed by running another version of rust-analyzer.

**Comment by dacut** [comment]
Hmm... it was suggested that ABI mismatches were at fault here from [this Twitter reply by Lukas Wirth](https://twitter.com/Veykril/status/1539297596057042945), hence my attempt to keep `rust-analyzer` in-sync with `rustup`.

Without `rust-analyzer.server.path` set, I currently get:
```
% rustc --version
rustc 1.63.0-nightly (5750a6aa2 2022-06-20)
> Rust Analyzer: Show RA version
rust-analyzer version: 0.0.0 (6fc5c3cd2 2022-06-20)
```

Interestingly, the version installed by `rustup` looks like it should be *more* broken... maybe?
```
% ~/.rustup/toolchains/nightly-aarch64-apple-darwin/bin/rust-analyzer --version
rust-analyzer 1.63.0-nightly (366bd7242 2022-06-12)
```

**Comment by Galster-dev** [comment]
Hello! I've been slowly downgrading using VS marketplace so I can tell this broke in release `0.4.1086`
Downgrading to `0.4.1085` seems to fix *this* issue (there is other error log related to proc macro server which I'm not gonna cover because it's most likely already fixed)

**Comment by flodiebold** [comment]
@Galster-dev downgrading just hides the issue, it doesn't fix it. To hide it you could also just disable the diagnostic.

**Comment by dacut** [comment]
For those (like me) who might be curious as what to the proc macro PRs in flight might be that this issue depends upon (from https://github.com/rust-lang/rust-analyzer/issues/12600#issuecomment-1160849983), [this is the list of PRs with "proc" in their title](https://github.com/rust-lang/rust/pulls?q=is%3Apr+is%3Aopen+proc+in%3Atitle+); what I found that seem to be relevant (recent):

* https://github.com/rust-lang/rust/pull/97445
* https://github.com/rust-lang/rust/pull/98189
* https://github.com/rust-lang/rust/pull/98223
* https://github.com/rust-lang/rust/pull/98463

That said, I'm about as far from an expert as one could be on proc_macro issues; this list is almost certainly inaccurate, but _might_ provide some insight as to what's going on behind the scenes.

**Comment by lifegpc** [comment]
Got same error here.
![image](https://user-images.githubusercontent.com/41434272/178136150-26cebf82-9de7-46bd-b2da-e61b39d105a6.png)

**Comment by jonas-schievink** [comment]
https://github.com/rust-lang/rust-analyzer/pull/12747 should fix this issue, at least on beta and the *current* nightly. Please let us know if it still doesn't work.

**Comment by veber-alex** [comment]
Doesn't seem to work, I am getting the same assert as OP.
This is with 
RA: rust-analyzer 0.0.0 (4cbf23c19 2022-07-12)
Rust: rustc 1.64.0-nightly (38b72154d 2022-07-11)

**Comment by bjorn3** [comment]
I am pretty sure that rust-analyzer version doesn't yet include the fix.

**Comment by andylokandy** [comment]
Confirm fixed in the nightly build, but go-to-definition doesn't work for the idents inside the function-like proc macro. Maybe the ident span is get discarded.

**Comment by RohanKapurDEV** [comment]
I tried using @dacut's method to fix my issue, which did not work since I could not locate the `rust-analyzer.server.path` setting to begin with. I then tried to set `rust-analyzer.procMacro.server` to the same value (`/Users/rohan/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/rust-analyzer`) but to no avail.

Running arm64 vscode on an m1 but r-a seems convinced im running on an x86 system. The error:

```
proc macro `main` not expanded: Cannot create expander for /Users/rohan/Desktop/code/autodca/target/debug/deps/libtokio_macros-71ca935c51905a5f.dylib: Io(Custom { kind: InvalidData, error: DlOpen { desc: "dlopen(/Users/rohan/Desktop/code/autodca/target/debug/deps/libtokio_macros-71ca935c51905a5f.dylib, 10): no suitable image found.  Did find:\n\t/Users/rohan/Desktop/code/autodca/target/debug/deps/libtokio_macros-71ca935c51905a5f.dylib: mach-o, but wrong architecture\n\t/Users/rohan/Desktop/code/autodca/target/debug/deps/libtokio_macros-71ca935c51905a5f.dylib: mach-o, but wrong architecture" } })rust-analyzer[unresolved-proc-macro](https://rust-analyzer.github.io/manual.html#unresolved-proc-macro)
```

**Comment by flodiebold** [comment]
@RohanKapurDEV make sure you're using the arm64 Rust toolchain if you're using arm64 VSCode (`rustup toolchain install stable-arm64 && rustup default stable-arm64`).

**Comment by RohanKapurDEV** [comment]
@flodiebold running that command yields the following error:
```
❯ rustup toolchain install stable-arm64 && rustup default stable-arm6
info: syncing channel updates for 'stable-arm64'
info: latest update on 2022-06-30, rust version 1.62.0 (a8314ef7d 2022-06-27)
error: target 'arm64' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
```

Checking the provided link does lead me to a possible valid target: `aarch64-apple-darwin`. should i be using that instead of arm64?

**Comment by flodiebold** [comment]
Yes

**Comment by suica** [comment]
Switched my toolchain to beta and it worked.

**Comment by mccolljr** [comment]
I'm using rust toolchain `nightly-2022-06-08` (as suggested higher up in this thread) with the latest release version of the `rust-analyzer` VSCode extension (`0.3.1140-standalone (7e2b983fd 2022-07-24)`). All VSCode settings for rust-analyzer are the defaults. This error (or a related error) is still occurring with this combination - what is the latest known-good pairing of nightly rust and rust-analyzer version? The `atsamd-rs` libraries make pretty heavy use of proc macros and it is difficult to work effectively without proc macro support

**Comment by jplatte** [comment]
The latest known-good pair is today's nightly of both rustc and rust-analyzer. And from now on, rust nightlies contain a rust-analyzer proc-macro server that is guaranteed to use the same bridge version as rustc, which the rust-analyzer extension will check for and use (as of today), so expect no more breakage of this kind :)

You can read about all the details on [fasterthanlime's blog](https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions).

**Comment by mccolljr** [comment]
> The latest known-good pair is today's nightly of both rustc and rust-analyzer. And from now on, rust nightlies contain a rust-analyzer proc-macro server that is guaranteed to use the same proc-macro bridge version as rustc, which the rust-analyzer extension will check for and use (as of today), so expect no more breakage of this kind :)
> 
> You can read about all the details on [fasterthanlime's blog](https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions).

Awesome news and of course also an awesome and informative blog post. Thanks for the answer+update & thanks to everyone who contributed for your work on this.

**Comment by SturdyFool10** [comment]
I have had the same issue, my code can be found at https://github.com/SturdyFool10/RustResourceMonitor.git, setup goes commit, cargo build, cargo run
