### ISSUE TITLE
proc-macro server crashing on Serde derive

### ISSUE THREAD

**Issue by veber-alex** [rust-lang/rust-analyzer#12606]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 0.0.0 (6fc5c3cd2 2022-06-20)

**rustc version**: (eg. output of `rustc -V`)
rustc 1.63.0-nightly (bb8c2f411 2022-06-19)

code:
```rust
use serde::Deserialize;

#[derive(Deserialize)]
struct X;
```

log:
```
thread 'MacroExpander' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/handle.rs:22:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::handle::InternedStore<T>::new
   5: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::client::HandleStore<S>::new
   6: proc_macro_srv::abis::abi_1_63::proc_macro::bridge::server::run_server
   7: proc_macro_srv::abis::abi_1_63::Abi::expand
   8: proc_macro_srv::abis::Abi::expand
   9: proc_macro_srv::ProcMacroSrv::expand
  10: proc_macro_srv::cli::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by veber-alex** [comment]
duplicate of #12600
