### ISSUE TITLE
RA panicking on build script failure

### ISSUE THREAD

**Issue by mahdi-frms** [rust-lang/rust-analyzer#12769]
The server panics if executing just **any** build script in the project fails. Now it might seem a bit reasonable that in case we cannot build the project RA should also panic ( although not that great either ), but panicking only because there is an example in the project docs which has a dependency that fails to build is way out of mind. An example would be [Calloop](https://github.com/Smithay/calloop) in which the provided examples in the docs have [Rust-ZMQ](https://github.com/erickt/rust-zmq) as dependency and it fails to build if you do not have libzmq installed on your machine; while building Calloop itself and running `cargo check` in the project root would be error-free. With the current situation, you can't use Rust Analyzer for Calloop just because of that.

**Comment by flodiebold** [comment]
What do you mean by "panicking"? Can you provide a stack trace or error message?

**Comment by mahdi-frms** [comment]
server log:

```
[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to run build scripts

error: failed to run custom build command for `zmq-sys v0.11.0`

Caused by:
  process didn't exit successfully: `/home/mahdif/projects/gh/calloop/target/debug/build/zmq-sys-b894531aadc87439/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build/main.rs
  cargo:rerun-if-env-changed=PROFILE
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/home/mahdif/.cargo/registry/src/github.com-1ecc6299db9ec823/zeromq-src-0.1.10+4.3.2/vendor" "-DCMAKE_INSTALL_LIBDIR=lib" "-DCMAKE_C_STANDARD=99" "-DZMQ_BUILD_TESTS=OFF" "-DENABLE_DRAFTS=OFF" "-DENABLE_CURVE=ON" "-DCMAKE_BUILD_TYPE=Debug" "-DWITH_PERF_TOOL=OFF" "-DBUILD_SHARED=OFF" "-DBUILD_STATIC=ON" "-DWITH_LIBSODIUM=OFF" "-DCMAKE_INSTALL_PREFIX=/home/mahdif/projects/gh/calloop/target/debug/build/zmq-sys-c84a4d903ff6ee7e/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc"

  --- stderr
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now', /home/mahdif/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
     2: cmake::fail
               at /home/mahdif/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
     3: cmake::run
               at /home/mahdif/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:945:13
     4: cmake::Config::build
               at /home/mahdif/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:780:13
     5: zeromq_src::Build::build
               at /home/mahdif/.cargo/registry/src/github.com-1ecc6299db9ec823/zeromq-src-0.1.10+4.3.2/src/lib.rs:314:23
     6: build_script_main::find::configure
               at ./build/vendored.rs:9:21
     7: build_script_main::main
               at ./build/main.rs:6:5
     8: core::ops::function::FnOnce::call_once
               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
this happens just after I open VSCode in root directory of Calloop source tree

**Comment by Veykril** [comment]
That's not r-a panicking but the build script. R-a telling the user here is the correct thing, if the build-scripts fail to build r-a won't work properly on the project

**Comment by mahdi-frms** [comment]
Oh sorry, I thought r-a itself has panicked!

**Comment by flodiebold** [comment]
Note that most features should still work fine in this situation, but rust-analyzer won't be able to expand proc macros and anything generated by build scripts won't be there.
