### ISSUE TITLE
When i modify toml, i have to wait 1 minute for hints, with error

### ISSUE THREAD

**Issue by cybersoulK** [rust-lang/rust-analyzer#12943]
Rust Stable, rust-analyzer stable. VsCode. When i add new crate, i have to wait 1 minute for hints. even though i already downloaded that crate several times in other parts of my project. This errors shows up after 1 minute.

> impl_self_ty_query(ImplId(23287) -> ItemLoc { container: ModuleId { krate: CrateId(147), block: None, local_id: Idx::<ModuleData>(4) }, id: ItemTreeId { tree: TreeId { file: HirFileId(FileId(FileId(2168))), block: None }, value: Idx::<Impl>(0) } } -> ImplData { target_trait: Some(TraitRef { path: Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("GemmSelect"))] }, generic_args: [Some(GenericArgs { args: [Type(Path(Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("T"))] }, generic_args: [None] }))], has_self_type: false, bindings: [], desugared_from_fn: false })] } }), self_ty: Path(Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("GemmParameters"))] }, generic_args: [Some(GenericArgs { args: [Type(Path(Path { type_anchor: None, mod_path: ModPath { kind: Plain, segments: [Name(Text("T"))] }, generic_args: [None] }))], has_self_type: false, bindings: [], desugared_from_fn: false })] }), items: [FunctionId(FunctionId(99969))], is_negative: false, attribute_calls: None })

> DefMap CrateId(147) crate_name=Some(CrateDisplayName { crate_name: CrateName("malloc_buf"), canonical_name: "malloc_buf" }) block=None path=GemmParameters

thread 'Worker' panicked at 'index out of bounds: the len is 1 but the index is 4', crates/hir-def/src/nameres/path_resolution.rs:381:33
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
   4: hir_def::resolver::Resolver::resolve_path_in_type_ns
   5: hir_ty::lower::TyLoweringContext::lower_ty_ext
   6: hir_ty::lower::impl_self_ty_query
   7: salsa::runtime::Runtime::execute_query_implementation
   8: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   9: salsa::derived::slot::Slot<Q,MP>::read
  10: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  11: salsa::QueryTable<Q>::get
  12: <DB as hir_ty::db::HirDatabase>::impl_self_ty
  13: hir_ty::lower::impl_trait_query
  14: salsa::runtime::Runtime::execute_query_implementation
  15: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  16: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  18: salsa::derived::slot::MemoRevisions::validate_memoized_value
  19: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  20: salsa::derived::slot::Slot<Q,MP>::read
  21: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  22: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  23: hir_ty::method_resolution::TraitImpls::trait_impls_in_deps_query
  24: salsa::runtime::Runtime::execute_query_implementation
  25: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  26: salsa::derived::slot::Slot<Q,MP>::read
  27: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  28: <DB as hir_ty::db::HirDatabase>::trait_impls_in_deps::__shim
  29: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::impls_for_trait
  30: chalk_recursive::solve::SolveIteration::solve_iteration
  31: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  32: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  33: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  34: salsa::runtime::Runtime::execute_query_implementation
  35: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  36: salsa::derived::slot::Slot<Q,MP>::read
  37: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  38: salsa::QueryTable<Q>::get
  39: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  40: hir_ty::db::trait_solve_wait
  41: <DB as hir_ty::db::HirDatabase>::trait_solve
  42: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  43: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::register_obligations_for_call
  44: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_overloadable_binop
  45: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  46: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  47: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  49: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  50: hir_ty::infer::infer_query
  51: salsa::runtime::Runtime::execute_query_implementation
  52: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  53: salsa::derived::slot::Slot<Q,MP>::read
  54: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  55: salsa::QueryTable<Q>::get
  56: <DB as hir_ty::db::HirDatabase>::infer_query
  57: hir_ty::db::infer_wait
  58: hir::DefWithBody::diagnostics
  59: hir::Module::diagnostics
  60: ide_diagnostics::diagnostics
  61: std::panicking::try
  62: ide::Analysis::diagnostics
  63: rust_analyzer::handlers::publish_diagnostics
  64: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  65: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by cybersoulK** [comment]
[Error - 6:46:11 PM] Request textDocument/inlayHint failed.
  Message: request handler panicked: no entry found for key
  Code: -32603 
Panic context:
> 
version: 0.3.1170-standalone (b6d59f2bb 2022-08-14)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/Users/andremarques/Desktop/cybergate/engine/networking/src/sync/channel_optimizer.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 81,
            character: 22,
        },
    },
}

thread 'Worker' panicked at 'no entry found for key', crates/hir-def/src/nameres.rs:226:23
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: hir_def::nameres::DefMap::crate_def_map_query
   6: salsa::runtime::Runtime::execute_query_implementation
   7: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   8: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
   9: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  10: salsa::derived::slot::MemoRevisions::validate_memoized_value
  11: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  12: salsa::derived::slot::Slot<Q,MP>::read
  13: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  14: <DB as hir_def::db::DefDatabase>::trait_data::__shim
  15: hir_ty::chalk_db::trait_datum_query
  16: salsa::runtime::Runtime::execute_query_implementation
  17: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  18: salsa::derived::slot::Slot<Q,MP>::read
  19: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  20: salsa::QueryTable<Q>::get
  21: <DB as hir_ty::db::HirDatabase>::trait_datum
  22: <chalk_ir::UCanonical<chalk_ir::InEnvironment<chalk_ir::Goal<I>>> as chalk_solve::coinductive_goal::IsCoinductive<I>>::is_coinductive
  23: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  24: chalk_recursive::fulfill::Fulfill<I,Solver>::prove
  25: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  26: chalk_recursive::solve::SolveIteration::solve_iteration
  27: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  28: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  29: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  30: salsa::runtime::Runtime::execute_query_implementation
  31: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  32: salsa::derived::slot::Slot<Q,MP>::read
  33: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  34: salsa::QueryTable<Q>::get
  35: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  36: hir_ty::db::trait_solve_wait
  37: <DB as hir_ty::db::HirDatabase>::trait_solve
  38: hir_ty::infer::unify::InferenceTable::try_obligation
  39: hir_ty::autoderef::autoderef_step
  40: hir_ty::autoderef::deref
  41: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  42: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  43: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  44: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  45: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  46: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  47: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  49: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  50: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  51: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  52: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  53: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  54: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  55: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  56: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  57: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  58: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  59: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  60: hir_ty::infer::infer_query
  61: salsa::runtime::Runtime::execute_query_implementation
  62: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  63: salsa::derived::slot::Slot<Q,MP>::read
  64: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  65: salsa::QueryTable<Q>::get
  66: <DB as hir_ty::db::HirDatabase>::infer_query
  67: hir_ty::db::infer_wait
  68: hir::source_analyzer::SourceAnalyzer::new_for_body
  69: hir::semantics::SemanticsImpl::analyze_impl
  70: hir::semantics::SemanticsImpl::type_of_pat
  71: ide::inlay_hints::hints
  72: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  73: ide::inlay_hints::inlay_hints
  74: std::panicking::try
  75: rust_analyzer::handlers::handle_inlay_hints
  76: std::panicking::try
  77: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 6:46:11 PM] Request textDocument/inlayHint failed.
  Message: request handler panicked: no entry found for key
  Code: -32603
