### ISSUE TITLE
RA server bootstrap error

### ISSUE THREAD

**Issue by KaoImin** [rust-lang/rust-analyzer#13138]
Type: <b>Bug</b>

When I update the extension to the latest version and reload, the server cannot bootstrap:
```log
INFO [8/29/2022, 3:14:57 PM]: PersistentState: { serverVersion: '0.3.1162' }
INFO [8/29/2022, 3:14:57 PM]: Using server binary at /home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer
ERROR [8/29/2022, 3:14:57 PM]: Bootstrap error [Error: Failed to execute /home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer --version
	at IS (/home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/out/main.js:85:2328)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async kS (/home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/out/main.js:84:1060)
	at async pv (/home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/out/main.js:84:891)
	at async E._activate (/home/user/.vscode-server-insiders/bin/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/api/node/extensionHostProcess.js:85:8224)
	at async E._waitForDepsThenActivate (/home/gao/.vscode-server-insiders/bin/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/api/node/extensionHostProcess.js:85:8166)
	at async E._initialize (/home/user/.vscode-server-insiders/bin/35b971c92d210face8c446a1c6f1e470ad2bcb54/out/vs/workbench/api/node/extensionHostProcess.js:85:7530)]
INFO [8/29/2022, 3:20:12 PM]: Extension version: 0.3.1178
```

Extension version: 0.3.1178
VS Code version: Code - Insiders 1.71.0-insider (35b971c92d210face8c446a1c6f1e470ad2bcb54, 2022-08-26T05:19:46.020Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 4175)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.93GB (28.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 4174)|
|Memory (System)|31.31GB (28.16GB free)|
|VM|0%|
</details>

**Comment by bjorn3** [comment]
What does running `/home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer --version` in WSL output?

**Comment by KaoImin** [comment]
```bash
/home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer)
/home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/user/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1178-linux-x64/server/rust-analyzer)
```

**Comment by bjorn3** [comment]
You need at least glibc 2.29 to run rust-analyzer since recently. You may be able to update your distro running in WSL. If not see https://github.com/rust-lang/rust-analyzer/issues/13081#issuecomment-1222199782 for how to get use rust-analyzer through rustup, which has the same glibc requirements as the rest of rustc.

**Comment by KaoImin** [comment]
> You need at least glibc 2.29 to run rust-analyzer since recently. You may be able to update your distro running in WSL. If not see [#13081 (comment)](https://github.com/rust-lang/rust-analyzer/issues/13081#issuecomment-1222199782) for how to get use rust-analyzer through rustup, which has the same glibc requirements as the rest of rustc.

I have already updated glibc to 2.35, but the problem still occurs.

```bash
ldd (GNU libc) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by michidk** [comment]
Same issue when using the vscode version 1.70.2 and the official Microsoft rust-postgres devcontainer:
```
ERROR [8/30/2022, 12:16:45 PM]: Bootstrap error [Error: Failed to execute /home/vscode/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1186-linux-x64/server/rust-analyzer --version
	at OS (/home/vscode/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1186-linux-x64/out/main.js:85:2328)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async xS (/home/vscode/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1186-linux-x64/out/main.js:84:1220)
	at async fv (/home/vscode/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1186-linux-x64/out/main.js:84:891)
	at async v._activate (/vscode/vscode-server/bin/linux-x64/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async v._waitForDepsThenActivate (/vscode/vscode-server/bin/linux-x64/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async v._initialize (/vscode/vscode-server/bin/linux-x64/e4503b30fc78200f846c62cf8091b76ff5547662/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)]
```

Devcontainer: https://github.com/microsoft/vscode-dev-containers/tree/v0.245.0/containers/rust-postgres
Happens with the latest pre-release and release version available from the extension store.

**Comment by lnicola** [comment]
@michidk Bullseye has GLIBC 2.31, so it should work. Are you sure your container is not based on an older version of Debian, like Buster?

**Comment by lnicola** [comment]
@KaoImin how did you install GLIBC 2.35?

**Comment by michidk** [comment]
> @michidk Bullseye has GLIBC 2.31, so it should work. Are you sure your container is not based on an older version of Debian, like Buster?

You are right. The dockerfile set it to bullseye but the docker-compose file overwrote it with buster.
With bullseye (or the fix to override the path) everything works fine.
```
vscode ➜ /workspace (main ✗) $ ldd --version
ldd (Debian GLIBC 2.31-13+deb11u3) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by lnicola** [comment]
Presumably fixed in https://github.com/rust-lang/rust-analyzer/pull/13214.
