### ISSUE TITLE
Rust analyzer produces errors in LSP logs (vim)

### ISSUE THREAD

**Issue by svalaskevicius** [rust-lang/rust-analyzer#13142]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

```
rust-analyzer --version
rust-analyzer 1.65.0-nightly (ce36e88 2022-08-28)
```

**rustc version**: (eg. output of `rustc -V`)

```
rustc -V
rustc 1.65.0-nightly (ce36e8825 2022-08-28)
```

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)

Running on NixOS via rustup, based on nixpkgs #5acffec125feb371dd86cdada5fa9f90946e75bb

```
thread '<unnamed>' panicked at 'Box<dyn Any>', /home/sarunas/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:472:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/std/src/panicking.rs:616:12
   1: proc_macro_error::abort_now
             at /home/sarunas/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:472:5
   2: proc_macro_error::diagnostic::Diagnostic::abort
             at /home/sarunas/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/diagnostic.rs:182:9
   3: duplicate::abort
             at /home/sarunas/.cargo/registry/src/github.com-1ecc6299db9ec823/duplicate-0.4.1/src/lib.rs:1141:3
   4: duplicate::duplicate_item::{{closure}}
             at /home/sarunas/.cargo/registry/src/github.com-1ecc6299db9ec823/duplicate-0.4.1/src/lib.rs:1011:15
   5: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/core/src/panic/unwind_safe.rs:271:9
   6: std::panicking::try::do_call
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/std/src/panicking.rs:492:40
   7: __rust_try
   8: std::panicking::try
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/std/src/panicking.rs:456:19
   9: std::panic::catch_unwind
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/std/src/panic.rs:137:14
  10: proc_macro_error::entry_point
             at /home/sarunas/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:432:18
  11: duplicate::duplicate_item
             at /home/sarunas/.cargo/registry/src/github.com-1ecc6299db9ec823/duplicate-0.4.1/src/lib.rs:1005:39
  12: core::ops::function::Fn::call
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/core/src/ops/function.rs:77:5
  13: proc_macro::bridge::client::Client<(proc_macro::TokenStream,proc_macro::TokenStream),proc_macro::TokenStream>::expand2::{{closure}}::{{closure}}
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/client.rs:452:21
  14: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}::{{closure}}
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/client.rs:401:30
  15: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/scoped_cell.rs:79:33
  16: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/scoped_cell.rs:74:9
  17: proc_macro::bridge::scoped_cell::ScopedCell<T>::set
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/scoped_cell.rs:79:9
  18: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/client.rs:400:13
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/std/src/thread/local.rs:445:16
  20: std::thread::local::LocalKey<T>::with
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/std/src/thread/local.rs:421:9
  21: proc_macro::bridge::client::run_client::{{closure}}
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/client.rs:399:9
  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/core/src/panic/unwind_safe.rs:271:9
  23: std::panicking::try::do_call
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/std/src/panicking.rs:492:40
  24: __rust_try
  25: std::panicking::try
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/std/src/panicking.rs:456:19
  26: std::panic::catch_unwind
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/std/src/panic.rs:137:14
  27: proc_macro::bridge::client::run_client
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/client.rs:386:5
  28: proc_macro::bridge::client::Client<(proc_macro::TokenStream,proc_macro::TokenStream),proc_macro::TokenStream>::expand2::{{closure}}
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/client.rs:451:17
  29: proc_macro::bridge::selfless_reify::reify_to_extern_c_fn_hrt_bridge::wrapper
             at /rustc/ce36e88256f09078519f8bc6b21e4dc88f88f523/library/proc_macro/src/bridge/selfless_reify.rs:64:17
  30: proc_macro::bridge::server::run_server::<proc_macro_srv::abis::abi_sysroot::ra_server::RustAnalyzer, (proc_macro::bridge::Marked<proc_macro_srv::abis::abi_sysroot::ra_server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>, proc_macro::bridge::Marked<proc_macro_srv::abis::abi_sysroot::ra_server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>), core::option::Option<proc_macro::bridge::Marked<proc_macro_srv::abis::abi_sysroot::ra_server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>>, proc_macro::bridge::server::SameThread>
  31: <proc_macro::bridge::client::Client<(proc_macro::TokenStream, proc_macro::TokenStream), proc_macro::TokenStream>>::run::<proc_macro_srv::abis::abi_sysroot::ra_server::RustAnalyzer, proc_macro::bridge::server::SameThread>
  32: <proc_macro_srv::abis::abi_sysroot::Abi>::expand
  33: <proc_macro_srv::dylib::Expander>::expand
  34: <<crossbeam_utils::thread::ScopedThreadBuilder>::spawn<<proc_macro_srv::ProcMacroSrv>::expand::{closure#2}::{closure#0}, core::result::Result<proc_macro_api::msg::flat::FlatTree, alloc::string::String>>::{closure#0} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by svalaskevicius** [comment]
rustc btw compiles ok and either succeeds or shows correct errors

**Comment by svalaskevicius** [comment]
hmm, some errors appeared after a run of cargo clean... the same stacktrace is logged still though so keeping as open and will try to continue using it

**Comment by lnicola** [comment]
I haven't tested this yet, but here's a fun one @fasterthanlime.

**Comment by bjorn3** [comment]
It looks like that panic happened inside abort_now, which is expected to happen when there are errors reported by the proc macro using proc-macro-error. In other words this panic should be completely harmless. Something else must be the issue.

**Comment by svalaskevicius** [comment]
yeah, after `cargo clean` rust analyzer seems to work well again, I'll rename the issue - please feel free to close if the error is expected. also, the error is only logged when I start vim the first time

**Comment by lnicola** [comment]
It sounds like the proc macro itself was panicking, and there's a feature to make it produce nicer errors when misused. I don't think there's anything we can do about it, unless you figure out it's a real bug on our side.
