### ISSUE TITLE
Bootstrap error [Error: Failed to execute /home/vivek/.config/VSCodium/User/globalStorage

### ISSUE THREAD

**Issue by VivekS98** [rust-lang/rust-analyzer#13241]
Rust Analyser throws error after installation.
```
ERROR [16/9/2022, 5:53:37 pm]: Bootstrap error [Error: Failed to execute /home/vivek/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu --version
	at L0 (/home/vivek/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:3922)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async F0 (/home/vivek/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:1881)
	at async O0 (/home/vivek/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3977)
	at async lC (/home/vivek/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3808)
	at async E._activate (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8224)
	at async E._waitForDepsThenActivate (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8166)
	at async E._initialize (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7530)]
```
```
INFO [16/9/2022, 5:53:37 pm]: Using server binary at /home/vivek/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu
WARN [16/9/2022, 5:53:37 pm]: /home/vivek/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu --version: {
  error: [Error: spawnSync /home/vivek/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu EACCES
  	at Object.spawnSync (node:internal/child_process:1111:20)
  	at spawnSync (node:child_process:823:24)
  	at Yy (/home/vivek/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:61:4063)
  	at L0 (/home/vivek/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:3680)
  	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async F0 (/home/vivek/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:1881)
  	at async O0 (/home/vivek/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3977)
  	at async lC (/home/vivek/.vscode-oss/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3808)
  	at async E._activate (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8224)
  	at async E._waitForDepsThenActivate (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8166)
  	at async E._initialize (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7530)] {
    errno: -13,
    code: 'EACCES',
    syscall: 'spawnSync /home/vivek/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu',
    path: '/home/vivek/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu',
    spawnargs: [ '--version' ]
  },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```

**Comment by bjorn3** [comment]
What does running `/home/vivek/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu --version` show?

**Comment by VivekS98** [comment]
> What does running `/home/vivek/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu --version` show?

`bash: /home/vivek/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu: Permission denied`

**Comment by lnicola** [comment]
See https://github.com/rust-lang/rust-analyzer/issues/11080.

You'll need to grab and install the VSIX from the GitHub releases page.

**Comment by VivekS98** [comment]
> See https://github.com/rust-lang/rust-analyzer/issues/11080.
> 
> You'll need to grab and install the VSIX from the GitHub releases page.

Installed from VSIX... But if an update arrives at `rust-analyesr`, will I be able to update the extension via VScodium itself or should I reinstall the latest VSIX...?

**Comment by lnicola** [comment]
You'll have to update it yourself or change some Codium file to make it use the official Marketplace (at least until the next Codium update).

There's nothing we can do about this.

**Comment by VivekS98** [comment]
> You'll have to update it yourself or change some Codium file to make it use the official Marketplace (at least until the next Codium update).
> 
> There's nothing we can do about this.

And can you please tell me what's that file change?

**Comment by lnicola** [comment]
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#how-to-use-the-vs-code-marketplace

Nice, you don't have to redo it after each update.

**Comment by lnicola** [comment]
@parsifallo read the output, that version is 9 months old. Don't post this as a solution for other users.
