### ISSUE TITLE
panic finding references: called `Option::unwrap()` on a `None` value, crates/hir-ty/src/method_resolution.rs

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust-analyzer#13265]
**rust-analyzer version**: rust-analyzer version: 0.0.0 (81e9571d9 2022-09-15)

**rustc version**: rustc 1.64.0-beta.3 (82bf34178 2022-08-18)

**relevant settings**:
```
; echo $RUSTUP_HOME $CARGO_HOME
/home/jnelson/.local/lib/rustup /home/jnelson/.local/lib/cargo
```

meta: this panic is when hitting F12 on `Canonical` in https://github.com/rust-lang/rust/blob/825a7cc65c4b21fd4f1b8f3b9ad204594de1e8c2/compiler/rustc_middle/src/infer/canonical.rs#L38

```
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', crates/hir-ty/src/method_resolution.rs:992:55
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9243168fa5615ec8ebe9164c6bc2fdcccffd08b6/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9243168fa5615ec8ebe9164c6bc2fdcccffd08b6/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/9243168fa5615ec8ebe9164c6bc2fdcccffd08b6/library/core/src/panicking.rs:48:5
   3: hir_ty::method_resolution::iterate_inherent_methods
   4: hir_ty::method_resolution::iterate_method_candidates_by_receiver
   5: hir_ty::method_resolution::iterate_method_candidates_dyn
   6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
   7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
   8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  11: hir_ty::infer::infer_query
  12: salsa::runtime::Runtime::execute_query_implementation
  13: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  14: salsa::derived::slot::Slot<Q,MP>::read
  15: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  16: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  17: hir_ty::db::infer_wait
  18: hir::source_analyzer::SourceAnalyzer::new_for_body
  19: hir::semantics::SemanticsImpl::analyze_impl
  20: hir::semantics::SemanticsImpl::resolve_path
  21: ide_db::defs::NameRefClass::classify
  22: ide_db::search::FindUsages::search
  23: ide_db::search::FindUsages::all
  24: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  25: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  26: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  27: ide::references::find_all_refs
  28: std::panicking::try
  29: ide::Analysis::find_all_refs
  30: rust_analyzer::handlers::handle_references
  31: std::panicking::try
  32: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 6:52:38 PM] Request textDocument/references failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
```

**Comment by jyn514** [comment]
Ah, looks like this may have been fixed by https://github.com/rust-lang/rust-analyzer/commit/e54f61dbdb9183cc5fdf58cd098dd783178bc3b9

**Comment by jyn514** [comment]
Ok yes switching to the pre-release version fixed it :) thank you @lnicola for fixing this even before I reported  it :laughing:
