### ISSUE TITLE
Some errors in output window

### ISSUE THREAD

**Issue by ice1000** [rust-lang/rust-analyzer#13309]
**rust-analyzer version**: `rust-analyzer version: 0.4.1224-standalone`

**rustc version**: `rustc 1.64.0 (a55dd71d5 2022-09-19)`

**relevant settings**: probably no. I'm using it via ssh. It used to work, but I don't recall which version it was.

Sorry, I was working on a gigantic project and I believe that you don't want to test it. I am unable to find MWE at this point either.

**Comment by ice1000** [comment]
```
[Error - 4:20:39 AM] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
    at Object.dispose (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:29:4495)
    at Object.dispose (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:34:10387)
    at /home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:36:7541
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at fv (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:85:1735)
    at /home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:85:153
    at c._executeContributedCommand (/home/ubuntu/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:63762)
[Error - 4:20:39 AM] Request textDocument/inlayHint failed.
Error: Connection got disposed.
    at Object.dispose (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:29:4495)
    at Object.dispose (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:34:10387)
    at /home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:36:7541
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at fv (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:85:1735)
    at /home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:85:153
    at c._executeContributedCommand (/home/ubuntu/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:63762)
[Error - 4:20:39 AM] Request textDocument/inlayHint failed.
Error: Connection got disposed.
    at Object.dispose (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:29:4495)
    at Object.dispose (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:34:10387)
    at /home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:36:7541
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at fv (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:85:1735)
    at /home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:85:153
    at c._executeContributedCommand (/home/ubuntu/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:63762)
[Error - 4:20:39 AM] Request textDocument/inlayHint failed.
Error: Connection got disposed.
    at Object.dispose (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:29:4495)
    at Object.dispose (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:34:10387)
    at /home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:36:7541
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at fv (/home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:85:1735)
    at /home/ubuntu/.vscode-server/extensions/rust-lang.rust-analyzer-0.4.1224-linux-x64/out/main.js:85:153
    at c._executeContributedCommand (/home/ubuntu/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:63762)
```

**Comment by bjorn3** [comment]
What does it show before that? Those messages are a symptom of rust-analyzer having crashed, not the cause.

**Comment by ice1000** [comment]
@bjorn3 I just checked and they should be caused by the file not being added to the project. Apologies! I should realize this earlier. I haven't been programming in Rust for like 3 yrs and surely I've forgotten something haha
