### ISSUE TITLE
`Internal error, cycle detected: infer_query(ConstId(ConstId(0))), const_eval(ConstId(0))` with missing struct name

### ISSUE THREAD

**Issue by DropDemBits** [rust-lang/rust-analyzer#13378]
Reproduce with:

```rust
struct <const N: usize = 3>([(); N]);
```

**rust-analyzer version**: rust-analyzer version: 0.3.1229-standalone (5c28ad193 2022-10-01)

**rustc version**: rustc 1.64.0 (a55dd71d5 2022-09-19)

<details><summary><strong>Server Output</strong></summary>
<p>

```
Panic context:
> 
version: 0.3.1229-standalone (5c28ad193 2022-10-01)
request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Dev/LocalProjects/rust-analyzer/crates/ide-assists/src/handlers/generate_delegate_methods.rs",
            query: None,
            fragment: None,
        },
    },
    previous_result_id: "4",
}

thread 'Worker' panicked at 'Internal error, cycle detected:

infer_query(ConstId(ConstId(0)))
const_eval(ConstId(0))
', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.17.0-pre.2\src\lib.rs:422:35
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:142
   2: <DB as hir_ty::db::HirDatabase>::infer_query
   3: hir_ty::db::infer_wait
   4: <DB as hir_ty::db::HirDatabase>::infer
   5: hir_ty::consteval::const_eval_variant_query
   6: salsa::runtime::Runtime::execute_query_implementation
   7: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
   8: salsa::derived::slot::Slot<Q,MP>::read
   9: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  10: <DB as hir_ty::db::HirDatabase>::const_eval
  11: hir_ty::consteval::eval_const
  12: hir_ty::consteval::eval_to_const
  13: <core::iter::adapters::rev::Rev<I> as core::iter::traits::iterator::Iterator>::fold
  14: <core::iter::adapters::rev::Rev<I> as core::iter::traits::iterator::Iterator>::fold
  15: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  16: <core::iter::adapters::rev::Rev<I> as core::iter::traits::iterator::Iterator>::fold
  17: <core::iter::adapters::rev::Rev<I> as core::iter::traits::iterator::Iterator>::fold
  18: hir_ty::infer::infer_query
  19: salsa::runtime::Runtime::execute_query_implementation
  20: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as hir_ty::db::HirDatabase>::infer_query
  24: hir_ty::db::infer_wait
  25: <DB as hir_ty::db::HirDatabase>::infer
  26: hir::source_analyzer::SourceAnalyzer::new_for_body
  27: hir::semantics::SemanticsImpl::analyze_impl
  28: ide_db::defs::NameRefClass::classify
  29: ide::syntax_highlighting::highlight::name_like
  30: ide::syntax_highlighting::highlight
  31: salsa::Cancelled::catch
  32: ide::syntax_highlighting::inject::ra_fixture
  33: ide::syntax_highlighting::highlight
  34: std::panicking::try
  35: rust_analyzer::handlers::handle_semantic_tokens_full_delta
  36: std::panicking::try
  37: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:06:39 p.m.] Request textDocument/semanticTokens/full/delta failed.
  Message: request handler panicked: Internal error, cycle detected:

infer_query(ConstId(ConstId(0)))
const_eval(ConstId(0))

  Code: -32603 
```

</p>
</details>

**Comment by lowr** [comment]
Triage: the code still triggers panic with the new consteval infrastructure.

<details>
<summary>Server Output w/ 0.4.1464-standalone</summary>

```
Panic context:
> 
version: 0.4.1464-standalone
request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/user/bug_workbench/i14396/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    previous_result_id: "1",
}

thread 'Worker' panicked at 'Internal error, cycle detected:

infer_query(ConstId(ConstId(5155)))
const_eval((ConstId(5155), []))
mir_body(ConstId(ConstId(5155)))
', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.2/src/lib.rs:422:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
   3: <DB as hir_ty::db::HirDatabase>::infer_query
   4: hir_ty::db::infer_wait
   5: <DB as hir_ty::db::HirDatabase>::infer
   6: hir_ty::mir::lower::mir_body_query
   7: salsa::runtime::Runtime::execute_query_implementation
   8: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   9: salsa::derived::slot::Slot<Q,MP>::read
  10: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  11: <DB as hir_ty::db::HirDatabase>::mir_body::__shim
  12: <DB as hir_ty::db::HirDatabase>::mir_body
  13: hir_ty::consteval::const_eval_query
  14: salsa::runtime::Runtime::execute_query_implementation
  15: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  16: salsa::derived::slot::Slot<Q,MP>::read
  17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  18: salsa::QueryTable<Q>::get
  19: <DB as hir_ty::db::HirDatabase>::const_eval
  20: hir_ty::mir::lower::MirLowerCtx::lower_const
  21: hir_ty::mir::lower::MirLowerCtx::lower_expr_to_place_without_adjust
  22: hir_ty::mir::lower::MirLowerCtx::lower_expr_to_place
  23: hir_ty::mir::lower::lower_to_mir
  24: hir_ty::consteval::eval_to_const
  25: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  26: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  27: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_overloadable_binop
  28: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  29: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  30: hir_ty::infer::infer_query
  31: salsa::runtime::Runtime::execute_query_implementation
  32: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  35: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  36: <DB as hir_ty::db::HirDatabase>::infer_query
  37: hir_ty::db::infer_wait
  38: <DB as hir_ty::db::HirDatabase>::infer
  39: hir::source_analyzer::SourceAnalyzer::new_for_body
  40: hir::semantics::SemanticsImpl::analyze_impl
  41: ide_db::defs::NameRefClass::classify
  42: ide::syntax_highlighting::highlight::name_like
  43: ide::syntax_highlighting::highlight
  44: std::panicking::try
  45: rust_analyzer::handlers::handle_semantic_tokens_full_delta
  46: std::panicking::try
  47: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by lowr** [comment]
Triage: the code still triggers panic with the new consteval infrastructure.

<details>
<summary>Server Output w/ 0.4.1464-standalone</summary>

```
Panic context:
> 
version: 0.4.1464-standalone
request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/path/to/repo/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    previous_result_id: "1",
}

thread 'Worker' panicked at 'Internal error, cycle detected:

infer_query(ConstId(ConstId(5155)))
const_eval((ConstId(5155), []))
mir_body(ConstId(ConstId(5155)))
', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.17.0-pre.2/src/lib.rs:422:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
   3: <DB as hir_ty::db::HirDatabase>::infer_query
   4: hir_ty::db::infer_wait
   5: <DB as hir_ty::db::HirDatabase>::infer
   6: hir_ty::mir::lower::mir_body_query
   7: salsa::runtime::Runtime::execute_query_implementation
   8: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   9: salsa::derived::slot::Slot<Q,MP>::read
  10: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  11: <DB as hir_ty::db::HirDatabase>::mir_body::__shim
  12: <DB as hir_ty::db::HirDatabase>::mir_body
  13: hir_ty::consteval::const_eval_query
  14: salsa::runtime::Runtime::execute_query_implementation
  15: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  16: salsa::derived::slot::Slot<Q,MP>::read
  17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  18: salsa::QueryTable<Q>::get
  19: <DB as hir_ty::db::HirDatabase>::const_eval
  20: hir_ty::mir::lower::MirLowerCtx::lower_const
  21: hir_ty::mir::lower::MirLowerCtx::lower_expr_to_place_without_adjust
  22: hir_ty::mir::lower::MirLowerCtx::lower_expr_to_place
  23: hir_ty::mir::lower::lower_to_mir
  24: hir_ty::consteval::eval_to_const
  25: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  26: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  27: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_overloadable_binop
  28: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  29: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  30: hir_ty::infer::infer_query
  31: salsa::runtime::Runtime::execute_query_implementation
  32: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  35: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  36: <DB as hir_ty::db::HirDatabase>::infer_query
  37: hir_ty::db::infer_wait
  38: <DB as hir_ty::db::HirDatabase>::infer
  39: hir::source_analyzer::SourceAnalyzer::new_for_body
  40: hir::semantics::SemanticsImpl::analyze_impl
  41: ide_db::defs::NameRefClass::classify
  42: ide::syntax_highlighting::highlight::name_like
  43: ide::syntax_highlighting::highlight
  44: std::panicking::try
  45: rust_analyzer::handlers::handle_semantic_tokens_full_delta
  46: std::panicking::try
  47: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by ChayimFriedman2** [comment]
Doesn't panic anymore.
