### ISSUE TITLE
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-solve-0.86.0/src/clauses/builtin_traits/fn_family.rs:90:55

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust-analyzer#13531]
While working on cg_clif:

```
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-solve-0.86.0/src/clauses/builtin_traits/fn_family.rs:90:55
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_recursive::solve::SolveIterationHelpers::solve_from_clauses
   7: chalk_recursive::recursive::<impl chalk_recursive::fixed_point::SolverStuff<chalk_ir::UCanonical<chalk_ir::InEnvironment<chalk_ir::Goal<I>>>,core::result::Result<chalk_solve::solve::Solution<I>,chalk_ir::NoSolution>> for &dyn chalk_solve::RustIrDatabase<I>>::solve_iteration
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_trait_method_candidates
  20: hir_ty::method_resolution::iterate_method_candidates_by_receiver
  21: hir_ty::method_resolution::iterate_method_candidates_dyn
  22: hir::Type::iterate_method_candidates_dyn
  23: hir::Type::iterate_method_candidates
  24: ide_completion::completions::dot::complete_dot
  25: ide_completion::completions::complete_name_ref
  26: ide_completion::completions
  27: std::panicking::try
  28: rust_analyzer::handlers::handle_completion
  29: std::panicking::try
  30: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 2:39:37 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603
```

**rust-analyzer version**: rust-analyzer version: 0.3.1258-standalone

**rustc version**: rustc 1.66.0-nightly (6e95b6da8 2022-10-22)

**relevant settings**: N/A

**Comment by bjorn3** [comment]
The crash in question happens when replacing the `bswap` intrinsic implementation with:

```rust
        sym::bswap => {
            intrinsic_args!(fx, args => (arg); intrinsic);
            let val = arg.load_scalar(fx);

            let res = match fx.bcx.func.dfg.value_type(val) {
                types::I8 => val,
                types::I128 => {
                    // FIXME(bytecodealliance/wasmtime#1092) bswap.i128 is not yet implemented
                    let (lsb, msb) = fx.bcx.ins().isplit(val);
                    let lsb_swap = fx.bcx.ins().bswap(lsb);
                }
                _ =>  fx.bcx.ins().bswap(val),
            };
            let res = CValue::by_val(res, arg.layout());
            ret.write_cvalue(fx, res);
        }
```

**Comment by Absolucy** [comment]
Running into the same panic being spammed whenever I copy-paste this code into a new file: https://pastebin.com/Wnfn30SV
![image](https://user-images.githubusercontent.com/65794972/206065920-3ff1344c-c95a-4590-94de-47cddc3bc655.png)

version: 0.3.1309-standalone (a2beeb8db 2022-12-04)

**Comment by Marcono1234** [comment]
I am also experiencing this with VS Code extension version `v0.3.1348`.
<details>
<summary>VS Code version</summary>

```
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
```

</details>

For me it occurs occasionally when I open VS Code and a `.rs` file is already open from the last time I edited it in VS Code. When I then try to edit that file while rust-analyzer is still loading / indexing and save the file, any edit afterwards causes error dialogs similar to what @Absolucy showed above.

**Comment by IvanKostyuk** [comment]
Reproducible in the version `v0.3.1541`

<details>
<summary>VS Code version</summary>

```
Version: 1.78.2 (system setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```
</details>

I'm trying to autocomplete `String::as_bytes()`

Restarted VS Code - everything works.

**Comment by lowr** [comment]
I've tried to reproduce the crash several times only to fail. This panic *really* shouldn't happen at all, yet it happens somehow, and I'm starting to suspect this might be an issue around salsa's recomputation.

If anyone happens to get the crash reproducible, please report it here -- I'd be more than happy to investigate. Otherwise, please restart rust-analyzer and it should start working just fine again.

**Comment by Easyoakland** [comment]
I have a [repo](https://github.com/Easyoakland/advent-of-code/tree/rust-analyzer-crash) that consistently crashes with this error (in vscode in windows). It continues to work on reload. So consistently that it is very annoying. Open the repo in the `rust-analyzer-crash` branch as a folder/workspace and then open `advent_lib/src/algorithms.rs`. Immediate and repeated:
```
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', crates\hir-expand\src\db.rs:540:51
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\core\src\panicking.rs:117
   3: <hir_expand::db::MacroExpandQuery as salsa::plumbing::QueryFunction>::execute
   4: salsa::runtime::Runtime::execute_query_implementation
   5: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_expand::db::MacroArgNodeQuery>>
   6: salsa::derived::slot::Slot<Q,MP>::read
   7: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   8: <DB as hir_expand::db::ExpandDatabase>::macro_expand
   9: <hir_expand::db::ParseMacroExpansionQuery as salsa::plumbing::QueryFunction>::execute
  10: salsa::runtime::Runtime::execute_query_implementation
  11: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_expand::db::MacroArgNodeQuery>>
  12: salsa::derived::slot::Slot<Q,MP>::read
  13: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  14: <DB as hir_expand::db::ExpandDatabase>::parse_macro_expansion
  15: salsa::runtime::Runtime::execute_query_implementation
  16: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_expand::db::MacroArgNodeQuery>>
  17: salsa::derived::slot::Slot<Q,MP>::read
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  19: <DB as hir_expand::db::ExpandDatabase>::parse_macro_expansion_error
  20: hir_def::nameres::collector::DefCollector::record_resolved_import
  21: hir_def::nameres::collector::collect_defs
  22: <hir_def::db::CrateDefMapQueryQuery as salsa::plumbing::QueryFunction>::execute
  23: salsa::runtime::Runtime::execute_query_implementation
  24: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_def::db::UnionDataWithDiagnosticsQuery>>
  25: salsa::derived::slot::Slot<Q,MP>::read
  26: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  27: <DB as hir_def::db::DefDatabase>::crate_def_map_query
  28: hir_def::db::crate_def_map_wait
  29: hir::semantics::source_to_def::SourceToDefCtx::file_to_def
  30: hir::semantics::source_to_def::SourceToDefCtx::find_container
  31: hir::semantics::SemanticsImpl::analyze_impl
  32: hir::semantics::SemanticsImpl::scope
  33: ide::inlay_hints::inlay_hints
  34: std::panicking::try
  35: rust_analyzer::handlers::request::handle_inlay_hints
  36: core::ops::function::FnOnce::call_once{{vtable.shim}}
```

**Comment by lowr** [comment]
@Easyoakland Thanks for the report, but that seems to be a different problem. This issue tracks panics in `chalk-solve-0.xx.0/src/clauses/builtin_traits/fn_family.rs`. Can you file a new issue?

**Comment by lnicola** [comment]
Just ran into this on code like

![image](https://github.com/rust-lang/rust-analyzer/assets/308347/ed3b28ad-5626-41e8-85b1-032bbbe44758)

Typing `f32::` or `String::` triggered the panic, but it stopped happening after restarting the server.

**Comment by Veykril** [comment]
I feel like this might be another chalk bug as it should not possible for this to happen (especially with a sysroot loaded)

**Comment by lnicola** [comment]
@Veykril could it be that we're hitting `chalk` before we've fully loaded the sysroot? I can trigger it somewhat reliably by triggering completion right after opening a project.

**Comment by Veykril** [comment]
then we should be able to reproduce this easily by setting the sysroot to `null` though

**Comment by lnicola** [comment]
I'm not sure. What if there's a difference between "no sysroot" and "sysroot, but not yet loaded"? I added some logging to `ChalkContext::well_known_trait_id`, reproduced the crash and got:

```
[ERROR hir_ty::chalk_db] FnOnce => None
```

(which seems to get cached, so it fails every time afterwards).

While a normal load yields:

```
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] Fn => Some(TraitId(68))
[ERROR hir_ty::chalk_db] Fn => Some(TraitId(68))
[ERROR hir_ty::chalk_db] FnOnce => Some(TraitId(70))
[ERROR hir_ty::chalk_db] FnMut => Some(TraitId(69))
[ERROR hir_ty::chalk_db] FnMut => Some(TraitId(69))
```

**Comment by Veykril** [comment]
have not seen this in a while, will consider this fixed by the salsa upgrade
