### ISSUE TITLE
Bootstrap error

### ISSUE THREAD

**Issue by uuuuu-diwu** [rust-lang/rust-analyzer#13637]
version info:
rustc 1.65.0 (897e37553 2022-11-02)
ra version:  v0.3.1285,  installed from https://github.com/rust-lang/rust-analyzer/releases/download/2022-11-14/rust-analyzer-linux-x64.vsix
glibc version: ldd (Debian GLIBC 2.24-11+deb9u4) 2.24

Error info:

ERROR [11/19/2022, 12:22:05 PM]: Bootstrap error [Error: Failed to execute /home/wudi.hust/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1285/server/rust-analyzer --version
	at xv (/data00/home/wudi.hust/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1285/out/main.js:82:4727)
	at async da.getOrCreateClient (/data00/home/wudi.hust/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1285/out/main.js:95:1720)
	at async da.start (/data00/home/wudi.hust/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1285/out/main.js:95:2537)
	at async TS (/data00/home/wudi.hust/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1285/out/main.js:99:1282)
	at async RS (/data00/home/wudi.hust/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1285/out/main.js:99:763)
	at async w._activate (/data00/home/wudi.hust/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:90:8304)
	at async w._waitForDepsThenActivate (/data00/home/wudi.hust/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:90:8246)
	at async w._initialize (/data00/home/wudi.hust/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:90:7610)]

**Comment by lnicola** [comment]
Our binaries are built on Ubuntu 18.04, and require a newer GLIBC. You can build one from source (it only takes a couple of minutes and doesn't have any special prerequisites), or get it from rustup (but that one will be older and not always match the Code extension -- some of the custom commands will break at times). You can search for other similar issues.

And you seem to be running Debian Stretch, which is EOL. Given this, and the existence of alternatives, we're not going to support it.
