### ISSUE TITLE
Cannot activate rust-analyzer: "bootstrap error. See the logs in "OUTPUT"

### ISSUE THREAD

**Issue by YisusGaming** [rust-lang/rust-analyzer#13677]
Logs:

```
INFO [25/11/2022 2:10:23 p. m.]: Starting language client
INFO [25/11/2022 2:10:23 p. m.]: Using server binary at c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\server\rust-analyzer.exe
WARN [25/11/2022 2:10:32 p. m.]: c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\server\rust-analyzer.exe --version: {
  error: [Error: spawnSync c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\server\rust-analyzer.exe UNKNOWN
  	at Object.spawnSync (node:internal/child_process:1111:20)
  	at spawnSync (node:child_process:834:24)
  	at Dm (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:39:61396)
  	at xv (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:82:4485)
  	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async da.getOrCreateClient (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:95:1720)
  	at async da.start (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:95:2549)
  	at async TS (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:99:1754)
  	at async RS (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:99:763)
  	at async w._activate (c:\Users\Yusne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:8304)
  	at async w._waitForDepsThenActivate (c:\Users\Yusne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:8246)
  	at async w._initialize (c:\Users\Yusne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:7610)] {
    errno: -4094,
    code: 'UNKNOWN',
    syscall: 'spawnSync c:\\Users\\Yusne\\.vscode\\extensions\\rust-lang.rust-analyzer-0.3.1293\\server\\rust-analyzer.exe',
    path: 'c:\\Users\\Yusne\\.vscode\\extensions\\rust-lang.rust-analyzer-0.3.1293\\server\\rust-analyzer.exe',
    spawnargs: [ '--version' ]
  },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
ERROR [25/11/2022 2:10:32 p. m.]: Bootstrap error [Error: Failed to execute c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\server\rust-analyzer.exe --version
	at xv (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:82:4727)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async da.getOrCreateClient (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:95:1720)
	at async da.start (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:95:2549)
	at async TS (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:99:1754)
	at async RS (c:\Users\Yusne\.vscode\extensions\rust-lang.rust-analyzer-0.3.1293\out\main.js:99:763)
	at async w._activate (c:\Users\Yusne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:8304)
	at async w._waitForDepsThenActivate (c:\Users\Yusne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:8246)
	at async w._initialize (c:\Users\Yusne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:7610)]
```

**Comment by lnicola** [comment]
Do you have a 32-bit system, or..?

**Comment by YisusGaming** [comment]
Yes, I'm using a 32-bit system.
I have install Visual C++ libraries

**Comment by bjorn3** [comment]
Using the precompiled rustup component should also work, right?

**Comment by lnicola** [comment]
It would, but I think we had some recent client changes and there might be some incompatibilities between the extension and the `stable` RA.

**Comment by YisusGaming** [comment]
> We don't even have a 32-bit version of the extension, you shouldn't have been able to install it.
> 
> Anyway, you can build from source in the meanwhile. It's pretty easy, `cargo xtask install --server` should do it, then you can set `rust-analyzer.server.path` to point to it.

Oh ok, I'll try doing that. Thanks!
