### ISSUE TITLE
thread 'Worker' panicked at 'nonscalar layout for layout_scalar_valid_range type on `i686-pc-windows-msvc`

### ISSUE THREAD

**Issue by gaoqiangz** [rust-lang/rust-analyzer#13951]
`x86_64-pc-windows-msvc` target dosn't have this problem.

rustc: 1.65.0-nightly (95a992a68 2022-09-16)
rust-analyzer: 0.3.1361-standalone (f77b68a3c 2023-01-08)
target: i686-pc-windows-msvc
os: Windows 11 22H2

output:
```
Panic context:
> 
version: 0.3.1361-standalone (f77b68a3c 2023-01-08)
request: textDocument/hover HoverParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/d%3A/Projects/pfwx/src/reactor/runtime.rs",
            query: None,
            fragment: None,
        },
    },
    position: Position(
        Position {
            line: 27,
            character: 11,
        },
    ),
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}

thread 'Worker' panicked at 'nonscalar layout for layout_scalar_valid_range type: Layout {
    size: Size(8 bytes),
    align: AbiAndPrefAlign {
        abi: Align(8 bytes),
        pref: Align(8 bytes),
    },
    abi: Aggregate {
        sized: true,
    },
    fields: Arbitrary {
        offsets: [
            Size(0 bytes),
        ],
        memory_index: [
            0,
        ],
    },
    largest_niche: None,
    variants: Single {
        index: RustcEnumVariantIdx(
            Idx::<EnumVariantData>(0),
        ),
    },
}', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hkalbasi-rustc-ap-rustc_abi-0.0.20221221\src\layout.rs:422:22
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
   2: hir_ty::layout::adt::layout_of_adt_query
   3: salsa::runtime::Runtime::execute_query_implementation
   4: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
   5: salsa::derived::slot::Slot<Q,MP>::read
   6: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   7: salsa::QueryTable<Q>::get
   8: <DB as hir_ty::db::HirDatabase>::layout_of_adt
   9: hir_ty::layout::layout_of_ty
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  12: core::iter::adapters::try_process
  13: hir_ty::layout::adt::layout_of_adt_query
  14: salsa::runtime::Runtime::execute_query_implementation
  15: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  16: salsa::derived::slot::Slot<Q,MP>::read
  17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  18: salsa::QueryTable<Q>::get
  19: <DB as hir_ty::db::HirDatabase>::layout_of_adt
  20: hir_ty::layout::layout_of_ty
  21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  23: core::iter::adapters::try_process
  24: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  25: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  26: hir_ty::layout::adt::layout_of_adt_query
  27: salsa::runtime::Runtime::execute_query_implementation
  28: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  29: salsa::derived::slot::Slot<Q,MP>::read
  30: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  31: salsa::QueryTable<Q>::get
  32: <DB as hir_ty::db::HirDatabase>::layout_of_adt
  33: hir_ty::layout::layout_of_ty
  34: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  35: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  36: core::iter::adapters::try_process
  37: hir_ty::layout::adt::layout_of_adt_query
  38: salsa::runtime::Runtime::execute_query_implementation
  39: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  40: salsa::derived::slot::Slot<Q,MP>::read
  41: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  42: salsa::QueryTable<Q>::get
  43: <DB as hir_ty::db::HirDatabase>::layout_of_adt
  44: hir_ty::layout::layout_of_ty
  45: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  46: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  47: core::iter::adapters::try_process
  48: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  49: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  50: hir_ty::layout::adt::layout_of_adt_query
  51: salsa::runtime::Runtime::execute_query_implementation
  52: core::ptr::drop_in_place<salsa::derived::slot::Memo<hir_ty::db::ProgramClausesForChalkEnvQuery>>
  53: salsa::derived::slot::Slot<Q,MP>::read
  54: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  55: salsa::QueryTable<Q>::get
  56: <DB as hir_ty::db::HirDatabase>::layout_of_adt
  57: hir_ty::layout::layout_of_ty
  58: hir::Field::layout
  59: ide::hover::render::definition
  60: ide::hover::hover_for_definition
  61: ide::hover::hover
  62: std::panicking::try
  63: rust_analyzer::handlers::handle_hover
  64: std::panicking::try
  65: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 21:32:55] Request textDocument/hover failed.
  Message: request handler panicked: nonscalar layout for layout_scalar_valid_range type: Layout {
    size: Size(8 bytes),
    align: AbiAndPrefAlign {
        abi: Align(8 bytes),
        pref: Align(8 bytes),
    },
    abi: Aggregate {
        sized: true,
    },
    fields: Arbitrary {
        offsets: [
            Size(0 bytes),
        ],
        memory_index: [
            0,
        ],
    },
    largest_niche: None,
    variants: Single {
        index: RustcEnumVariantIdx(
            Idx::<EnumVariantData>(0),
        ),
    },
}
  Code: -32603 
```

**Comment by Veykril** [comment]
Can you give soem more information regarding this? What type were you hovering when this occured?

**Comment by gaoqiangz** [comment]
`.cargo/config.toml`:
```toml
[build]
target = "i686-pc-windows-msvc"
```

`lib.rs`:
```rust
struct WillPanic {
    f: std::rc::Rc<()>,
}

struct WillPanic2 {
    f: std::sync::Arc<()>,
}

struct WillPanic3 {
    f: std::ptr::NonNull<()>,
}
```

**Comment by lowr** [comment]
I can only guess as I don't have access to Windows at the moment, but here's my two cents: we might be failing to get `target-spec-json` [here](https://github.com/rust-lang/rust-analyzer/blob/6189be13ab2dbd82759733f1106272893b833ef8/crates/project-model/src/target_data_layout.rs#L8). The first command is lanuching rustc rather than cargo, and the second one is passing possibly erroneous argument "rustc" to rustc.

If both commands fail the default `TargetDataLayout` would be used, which [seems to be of ordinary 64bit platform](https://github.com/rust-lang/rust/blob/4b51adf6ffa1ae2286ea436eb48cbaa8771886e6/compiler/rustc_abi/src/lib.rs#L177), making layout computation incorrect on 32bit platform.

**Comment by Veykril** [comment]
Fixed in https://github.com/rust-lang/rust-analyzer/pull/13966
