### ISSUE TITLE
Cannot activate rust-analyzer extension: bootstrap error. See the logs in "OUTPUT"

### ISSUE THREAD

**Issue by TheBigEye** [rust-lang/rust-analyzer#14013]
**rust-analyzer version**: 0.3.1377
**rustc version**: rustc 1.66.1 (90743e729 2023-01-10) (Rev1, Built by MSYS2 project)

**VScode**:  1.74.3
**OS**: Windows 10 x64 19045 (22H2)

VSCode Logs:
```
INFO [23/1/2023 18:59:54]: PersistentState: { serverVersion: '0.3.1377' }
INFO [23/1/2023 18:59:54]: Extension version: 0.3.1377
INFO [23/1/2023 18:59:54]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  restartServerOnConfigChange: false,
  typing: {
    continueCommentsOnNewline: true,
    autoClosingAngleBrackets: { enable: false }
  },
  diagnostics: {
    previewRustcOutput: false,
    useRustcErrorCode: false,
    disabled: [],
    enable: true,
    experimental: { enable: false },
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  assist: { emitMustUse: false, expressionFillDefault: 'todo' },
  cachePriming: { enable: true, numThreads: 0 },
  cargo: {
    autoreload: true,
    buildScripts: {
      enable: true,
      invocationLocation: 'workspace',
      invocationStrategy: 'per_workspace',
      overrideCommand: null,
      useRustcWrapper: true
    },
    extraEnv: {},
    features: [],
    noDefaultFeatures: false,
    sysroot: 'C:\\msys64\\mingw64',
    target: null,
    unsetTest: [ 'core' ]
  },
  checkOnSave: true,
  check: {
    allTargets: true,
    command: 'check',
    extraArgs: [],
    extraEnv: {},
    features: null,
    invocationLocation: 'workspace',
    invocationStrategy: 'per_workspace',
    noDefaultFeatures: null,
    overrideCommand: null,
    targets: null
  },
  completion: {
    autoimport: { enable: true },
    autoself: { enable: true },
    callable: { snippets: 'fill_arguments' },
    postfix: { enable: true },
    privateEditable: { enable: false },
    snippets: {
      custom: {
        'Arc::new': {
          postfix: 'arc',
          body: 'Arc::new(${receiver})',
          requires: 'std::sync::Arc',
          description: 'Put the expression into an `Arc`',
          scope: 'expr'
        },
        'Rc::new': {
          postfix: 'rc',
          body: 'Rc::new(${receiver})',
          requires: 'std::rc::Rc',
          description: 'Put the expression into an `Rc`',
          scope: 'expr'
        },
        'Box::pin': {
          postfix: 'pinbox',
          body: 'Box::pin(${receiver})',
          requires: 'std::boxed::Box',
          description: 'Put the expression into a pinned `Box`',
          scope: 'expr'
        },
        Ok: {
          postfix: 'ok',
          body: 'Ok(${receiver})',
          description: 'Wrap the expression in a `Result::Ok`',
          scope: 'expr'
        },
        Err: {
          postfix: 'err',
          body: 'Err(${receiver})',
          description: 'Wrap the expression in a `Result::Err`',
          scope: 'expr'
        },
        Some: {
          postfix: 'some',
          body: 'Some(${receiver})',
          description: 'Wrap the expression in an `Option::Some`',
          scope: 'expr'
        }
      }
    }
  },
  files: { excludeDirs: [], watcher: 'client' },
  highlightRelated: {
    breakPoints: { enable: true },
    exitPoints: { enable: true },
    references: { enable: true },
    yieldPoints: { enable: true }
  },
  hover: {
    actions: {
      debug: { enable: true },
      enable: true,
      gotoTypeDef: { enable: true },
      implementations: { enable: true },
      references: { enable: false },
      run: { enable: true }
    },
    documentation: { enable: true, keywords: { enable: true } },
    links: { enable: true }
  },
  imports: {
    granularity: { enforce: false, group: 'crate' },
    group: { enable: true },
    merge: { glob: true },
    prefer: { no: { std: false } },
    prefix: 'plain'
  },
  inlayHints: {
    bindingModeHints: { enable: false },
    chainingHints: { enable: true },
    closingBraceHints: { enable: true, minLines: 25 },
    closureReturnTypeHints: { enable: 'never' },
    discriminantHints: { enable: 'never' },
    expressionAdjustmentHints: { enable: 'never', hideOutsideUnsafe: false, mode: 'prefix' },
    lifetimeElisionHints: { enable: 'never', useParameterNames: false },
    maxLength: 25,
    parameterHints: { enable: true },
    reborrowHints: { enable: 'never' },
    renderColons: true,
    typeHints: {
      enable: true,
      hideClosureInitialization: false,
      hideNamedConstructor: false
    }
  },
  joinLines: {
    joinAssignments: true,
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true
  },
  lens: {
    debug: { enable: true },
    enable: true,
    forceCustomCommands: true,
    implementations: { enable: true },
    location: 'above_name',
    references: {
      adt: { enable: false },
      enumVariant: { enable: false },
      method: { enable: false },
      trait: { enable: false }
    },
    run: { enable: true }
  },
  linkedProjects: [],
  lru: { capacity: null },
  notifications: { cargoTomlNotFound: true },
  numThreads: null,
  procMacro: {
    attributes: { enable: true },
    enable: true,
    ignored: {},
    server: null
  },
  references: { excludeImports: false },
  runnables: { command: null, extraArgs: [] },
  rustc: { source: null },
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    rangeFormatting: { enable: false }
  },
  semanticHighlighting: {
    doc: { comment: { inject: { enable: true } } },
    operator: { enable: true, specialization: { enable: false } },
    punctuation: {
      enable: false,
      separate: { macro: { bang: false } },
      specialization: { enable: false }
    },
    strings: { enable: true }
  },
  signatureInfo: { detail: 'full', documentation: { enable: true } },
  workspace: {
    symbol: { search: { kind: 'only_types', limit: 128, scope: 'workspace' } }
  }
}
INFO [23/1/2023 18:59:54]: Starting language client
INFO [23/1/2023 18:59:55]: Using server binary at c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\server\rust-analyzer.exe
ERROR [23/1/2023 18:59:56]: Bootstrap error [Error: Failed to execute c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\server\rust-analyzer.exe --version
	at Vv (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:83:4925)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Ca.getOrCreateClient (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:96:1720)
	at async Ca.start (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:96:2549)
	at async K_ (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:100:1948)
	at async z_ (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:100:763)
	at async v.n (c:\Users\creep\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:7006)
	at async v.m (c:\Users\creep\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6969)
	at async v.l (c:\Users\creep\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6426)]
INFO [23/1/2023 19:02:49]: Starting language client
INFO [23/1/2023 19:02:50]: Using server binary at c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\server\rust-analyzer.exe
ERROR [23/1/2023 19:02:50]: Bootstrap error [Error: Failed to execute c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\server\rust-analyzer.exe --version
	at Vv (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:83:4925)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Ca.getOrCreateClient (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:96:1720)
	at async Ca.start (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:96:2549)
	at async c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:101:293
	at async s.h (c:\Users\creep\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:107614)]
```

- I tried to install previous versions, I even reinstalled the extension using VSIX, but the problem continues.

**Comment by Veykril** [comment]
Looks like the important log is being logged to `debug` instead of `warn` which gets filtered out. Can you enable `"rust-analyzer.trace.extension": true` in your settings and check the logs again?

**Comment by TheBigEye** [comment]
```
INFO [24/1/2023 13:20:19]: PersistentState: { serverVersion: '0.3.1377' }
INFO [24/1/2023 13:20:19]: Extension version: 0.3.1377
INFO [24/1/2023 13:20:19]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: true },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  restartServerOnConfigChange: false,
  typing: {
    continueCommentsOnNewline: true,
    autoClosingAngleBrackets: { enable: false }
  },
  diagnostics: {
    previewRustcOutput: false,
    useRustcErrorCode: false,
    disabled: [],
    enable: true,
    experimental: { enable: false },
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  assist: { emitMustUse: false, expressionFillDefault: 'todo' },
  cachePriming: { enable: true, numThreads: 0 },
  cargo: {
    autoreload: true,
    buildScripts: {
      enable: true,
      invocationLocation: 'workspace',
      invocationStrategy: 'per_workspace',
      overrideCommand: null,
      useRustcWrapper: true
    },
    extraEnv: {},
    features: [],
    noDefaultFeatures: false,
    sysroot: 'discover',
    target: null,
    unsetTest: [ 'core' ]
  },
  checkOnSave: true,
  check: {
    allTargets: true,
    command: 'check',
    extraArgs: [],
    extraEnv: {},
    features: null,
    invocationLocation: 'workspace',
    invocationStrategy: 'per_workspace',
    noDefaultFeatures: null,
    overrideCommand: null,
    targets: null
  },
  completion: {
    autoimport: { enable: true },
    autoself: { enable: true },
    callable: { snippets: 'fill_arguments' },
    postfix: { enable: true },
    privateEditable: { enable: false },
    snippets: {
      custom: {
        'Arc::new': {
          postfix: 'arc',
          body: 'Arc::new(${receiver})',
          requires: 'std::sync::Arc',
          description: 'Put the expression into an `Arc`',
          scope: 'expr'
        },
        'Rc::new': {
          postfix: 'rc',
          body: 'Rc::new(${receiver})',
          requires: 'std::rc::Rc',
          description: 'Put the expression into an `Rc`',
          scope: 'expr'
        },
        'Box::pin': {
          postfix: 'pinbox',
          body: 'Box::pin(${receiver})',
          requires: 'std::boxed::Box',
          description: 'Put the expression into a pinned `Box`',
          scope: 'expr'
        },
        Ok: {
          postfix: 'ok',
          body: 'Ok(${receiver})',
          description: 'Wrap the expression in a `Result::Ok`',
          scope: 'expr'
        },
        Err: {
          postfix: 'err',
          body: 'Err(${receiver})',
          description: 'Wrap the expression in a `Result::Err`',
          scope: 'expr'
        },
        Some: {
          postfix: 'some',
          body: 'Some(${receiver})',
          description: 'Wrap the expression in an `Option::Some`',
          scope: 'expr'
        }
      }
    }
  },
  files: { excludeDirs: [], watcher: 'client' },
  highlightRelated: {
    breakPoints: { enable: true },
    exitPoints: { enable: true },
    references: { enable: true },
    yieldPoints: { enable: true }
  },
  hover: {
    actions: {
      debug: { enable: true },
      enable: true,
      gotoTypeDef: { enable: true },
      implementations: { enable: true },
      references: { enable: false },
      run: { enable: true }
    },
    documentation: { enable: true, keywords: { enable: true } },
    links: { enable: true }
  },
  imports: {
    granularity: { enforce: false, group: 'crate' },
    group: { enable: true },
    merge: { glob: true },
    prefer: { no: { std: false } },
    prefix: 'plain'
  },
  inlayHints: {
    bindingModeHints: { enable: false },
    chainingHints: { enable: true },
    closingBraceHints: { enable: true, minLines: 25 },
    closureReturnTypeHints: { enable: 'never' },
    discriminantHints: { enable: 'never' },
    expressionAdjustmentHints: { enable: 'never', hideOutsideUnsafe: false, mode: 'prefix' },
    lifetimeElisionHints: { enable: 'never', useParameterNames: false },
    maxLength: 25,
    parameterHints: { enable: true },
    reborrowHints: { enable: 'never' },
    renderColons: true,
    typeHints: {
      enable: true,
      hideClosureInitialization: false,
      hideNamedConstructor: false
    }
  },
  joinLines: {
    joinAssignments: true,
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true
  },
  lens: {
    debug: { enable: true },
    enable: true,
    forceCustomCommands: true,
    implementations: { enable: true },
    location: 'above_name',
    references: {
      adt: { enable: false },
      enumVariant: { enable: false },
      method: { enable: false },
      trait: { enable: false }
    },
    run: { enable: true }
  },
  linkedProjects: [],
  lru: { capacity: null },
  notifications: { cargoTomlNotFound: true },
  numThreads: null,
  procMacro: {
    attributes: { enable: true },
    enable: true,
    ignored: {},
    server: null
  },
  references: { excludeImports: false },
  runnables: { command: null, extraArgs: [] },
  rustc: { source: null },
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    rangeFormatting: { enable: false }
  },
  semanticHighlighting: {
    doc: { comment: { inject: { enable: true } } },
    operator: { enable: true, specialization: { enable: false } },
    punctuation: {
      enable: false,
      separate: { macro: { bang: false } },
      specialization: { enable: false }
    },
    strings: { enable: true }
  },
  signatureInfo: { detail: 'full', documentation: { enable: true } },
  workspace: {
    symbol: { search: { kind: 'only_types', limit: 128, scope: 'workspace' } }
  }
}
INFO [24/1/2023 13:20:19]: Starting language client
INFO [24/1/2023 13:20:20]: Extension version: 0.3.1377
INFO [24/1/2023 13:20:20]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: true },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  restartServerOnConfigChange: false,
  typing: {
    continueCommentsOnNewline: true,
    autoClosingAngleBrackets: { enable: false }
  },
  diagnostics: {
    previewRustcOutput: false,
    useRustcErrorCode: false,
    disabled: [],
    enable: true,
    experimental: { enable: false },
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  assist: { emitMustUse: false, expressionFillDefault: 'todo' },
  cachePriming: { enable: true, numThreads: 0 },
  cargo: {
    autoreload: true,
    buildScripts: {
      enable: true,
      invocationLocation: 'workspace',
      invocationStrategy: 'per_workspace',
      overrideCommand: null,
      useRustcWrapper: true
    },
    extraEnv: {},
    features: [],
    noDefaultFeatures: false,
    sysroot: 'discover',
    target: null,
    unsetTest: [ 'core' ]
  },
  checkOnSave: true,
  check: {
    allTargets: true,
    command: 'check',
    extraArgs: [],
    extraEnv: {},
    features: null,
    invocationLocation: 'workspace',
    invocationStrategy: 'per_workspace',
    noDefaultFeatures: null,
    overrideCommand: null,
    targets: null
  },
  completion: {
    autoimport: { enable: true },
    autoself: { enable: true },
    callable: { snippets: 'fill_arguments' },
    postfix: { enable: true },
    privateEditable: { enable: false },
    snippets: {
      custom: {
        'Arc::new': {
          postfix: 'arc',
          body: 'Arc::new(${receiver})',
          requires: 'std::sync::Arc',
          description: 'Put the expression into an `Arc`',
          scope: 'expr'
        },
        'Rc::new': {
          postfix: 'rc',
          body: 'Rc::new(${receiver})',
          requires: 'std::rc::Rc',
          description: 'Put the expression into an `Rc`',
          scope: 'expr'
        },
        'Box::pin': {
          postfix: 'pinbox',
          body: 'Box::pin(${receiver})',
          requires: 'std::boxed::Box',
          description: 'Put the expression into a pinned `Box`',
          scope: 'expr'
        },
        Ok: {
          postfix: 'ok',
          body: 'Ok(${receiver})',
          description: 'Wrap the expression in a `Result::Ok`',
          scope: 'expr'
        },
        Err: {
          postfix: 'err',
          body: 'Err(${receiver})',
          description: 'Wrap the expression in a `Result::Err`',
          scope: 'expr'
        },
        Some: {
          postfix: 'some',
          body: 'Some(${receiver})',
          description: 'Wrap the expression in an `Option::Some`',
          scope: 'expr'
        }
      }
    }
  },
  files: { excludeDirs: [], watcher: 'client' },
  highlightRelated: {
    breakPoints: { enable: true },
    exitPoints: { enable: true },
    references: { enable: true },
    yieldPoints: { enable: true }
  },
  hover: {
    actions: {
      debug: { enable: true },
      enable: true,
      gotoTypeDef: { enable: true },
      implementations: { enable: true },
      references: { enable: false },
      run: { enable: true }
    },
    documentation: { enable: true, keywords: { enable: true } },
    links: { enable: true }
  },
  imports: {
    granularity: { enforce: false, group: 'crate' },
    group: { enable: true },
    merge: { glob: true },
    prefer: { no: { std: false } },
    prefix: 'plain'
  },
  inlayHints: {
    bindingModeHints: { enable: false },
    chainingHints: { enable: true },
    closingBraceHints: { enable: true, minLines: 25 },
    closureReturnTypeHints: { enable: 'never' },
    discriminantHints: { enable: 'never' },
    expressionAdjustmentHints: { enable: 'never', hideOutsideUnsafe: false, mode: 'prefix' },
    lifetimeElisionHints: { enable: 'never', useParameterNames: false },
    maxLength: 25,
    parameterHints: { enable: true },
    reborrowHints: { enable: 'never' },
    renderColons: true,
    typeHints: {
      enable: true,
      hideClosureInitialization: false,
      hideNamedConstructor: false
    }
  },
  joinLines: {
    joinAssignments: true,
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true
  },
  lens: {
    debug: { enable: true },
    enable: true,
    forceCustomCommands: true,
    implementations: { enable: true },
    location: 'above_name',
    references: {
      adt: { enable: false },
      enumVariant: { enable: false },
      method: { enable: false },
      trait: { enable: false }
    },
    run: { enable: true }
  },
  linkedProjects: [],
  lru: { capacity: null },
  notifications: { cargoTomlNotFound: true },
  numThreads: null,
  procMacro: {
    attributes: { enable: true },
    enable: true,
    ignored: {},
    server: null
  },
  references: { excludeImports: false },
  runnables: { command: null, extraArgs: [] },
  rustc: { source: null },
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    rangeFormatting: { enable: false }
  },
  semanticHighlighting: {
    doc: { comment: { inject: { enable: true } } },
    operator: { enable: true, specialization: { enable: false } },
    punctuation: {
      enable: false,
      separate: { macro: { bang: false } },
      specialization: { enable: false }
    },
    strings: { enable: true }
  },
  signatureInfo: { detail: 'full', documentation: { enable: true } },
  workspace: {
    symbol: { search: { kind: 'only_types', limit: 128, scope: 'workspace' } }
  }
}
INFO [24/1/2023 13:20:20]: Using server binary at c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\server\rust-analyzer.exe
DEBUG [24/1/2023 13:20:20]: Checking availability of a binary at c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\server\rust-analyzer.exe
DEBUG [24/1/2023 13:20:22]: c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\server\rust-analyzer.exe --version: {
  status: 3221225781,
  signal: null,
  output: [ null, '', '' ],
  pid: 4832,
  stdout: '',
  stderr: ''
}
ERROR [24/1/2023 13:20:22]: Bootstrap error [Error: Failed to execute c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\server\rust-analyzer.exe --version
	at Vv (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:83:4925)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Ca.getOrCreateClient (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:96:1720)
	at async Ca.start (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:96:2549)
	at async K_ (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:100:1948)
	at async z_ (c:\Users\creep\.vscode\extensions\rust-lang.rust-analyzer-0.3.1377\out\main.js:100:763)
	at async v.n (c:\Users\creep\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:7006)
	at async v.m (c:\Users\creep\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6969)
	at async v.l (c:\Users\creep\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6426)]
```

**Comment by Veykril** [comment]
That is `STATUS_DLL_NOT_FOUND`, can you try running the rust-analyzer server manually? You seem to be missing some dependency.

**Comment by TheBigEye** [comment]
I see, `VCRUNTIME140.DLL` not found
