### ISSUE TITLE
thread 'Worker' panicked at 'overflow depth reached', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/vendor/chalk-recursive/src/fixed_point/stack.rs:51:13

### ISSUE THREAD

**Issue by deepink-mas** [rust-lang/rust-analyzer#14028]
**rust-analyzer version**: rust-analyzer 1.66.1-nightly

**rustc version**: rustc 1.66.1-nightly (90743e729 2023-01-10) (gentoo)

I'm running into a panic while working on a workspace containing a few custom crates based around Parity's Substrate blockchain framework:

Panic context:
> 
version: 1.66.1-nightly
request: textDocument/hover HoverParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/werk/Code/genesis-dao-node/pallets/dao-votes/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    position: Position(
        Position {
            line: 75,
            character: 71,
        },
    ),
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
}

thread 'Worker' panicked at 'overflow depth reached', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/vendor/chalk-recursive/src/fixed_point/stack.rs:51:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 1.66.1-nightly
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/werk/Code/genesis-dao-node/pallets/dao-votes/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 76,
            character: 0,
        },
        end: Position {
            line: 76,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at 'overflow depth reached', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/vendor/chalk-recursive/src/fixed_point/stack.rs:51:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'Worker' panicked at 'overflow depth reached', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/vendor/chalk-recursive/src/fixed_point/stack.rs:51:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 1.66.1-nightly
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/werk/Code/genesis-dao-node/pallets/dao-votes/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 74,
            character: 0,
        },
        end: Position {
            line: 74,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at 'overflow depth reached', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/vendor/chalk-recursive/src/fixed_point/stack.rs:51:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 1.66.1-nightly
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/werk/Code/genesis-dao-node/pallets/dao-votes/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 74,
            character: 0,
        },
        end: Position {
            line: 74,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at 'overflow depth reached', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/vendor/chalk-recursive/src/fixed_point/stack.rs:51:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 1.66.1-nightly
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/werk/Code/genesis-dao-node/pallets/dao-votes/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 114,
            character: 0,
        },
        end: Position {
            line: 114,
            character: 0,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at 'overflow depth reached', /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/vendor/chalk-recursive/src/fixed_point/stack.rs:51:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by ChayimFriedman2** [comment]
Unlikely to be reproducible anymore therefore closing.
