### ISSUE TITLE
Extension fails to start with "Unexpected function type in substitution"

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rust-analyzer#14022]
**rust-analyzer version**: v0.4.1379

**rustc version**: rustc 1.68.0-nightly (9e75dddf6 2023-01-15)

As of the latest prerelease, I am getting
```
2023-01-24 21:59:13.388 [error] Activating extension rust-lang.rust-analyzer failed due to an error:
2023-01-24 21:59:13.389 [error] Error: Unexpected function type in substitution
	at Yr (c:\Users\aaron\.vscode\extensions\rust-lang.rust-analyzer-0.4.1379-win32-x64\out\main.js:41:5460)
	at Yr (c:\Users\aaron\.vscode\extensions\rust-lang.rust-analyzer-0.4.1379-win32-x64\out\main.js:41:5420)
	at wa.getOrCreateClient (c:\Users\aaron\.vscode\extensions\rust-lang.rust-analyzer-0.4.1379-win32-x64\out\main.js:96:2623)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async wa.start (c:\Users\aaron\.vscode\extensions\rust-lang.rust-analyzer-0.4.1379-win32-x64\out\main.js:96:2959)
	at async V_ (c:\Users\aaron\.vscode\extensions\rust-lang.rust-analyzer-0.4.1379-win32-x64\out\main.js:100:1948)
	at async K_ (c:\Users\aaron\.vscode\extensions\rust-lang.rust-analyzer-0.4.1379-win32-x64\out\main.js:100:763)
	at async v.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:7006)
	at async v.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6969)
	at async v.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:6426)
```

**Comment by Veykril** [comment]
Kicked off a nightly with the fix, should be available in a 1-2 hours hopefully
