### ISSUE TITLE
Memory Leak in vscode/RA/Windows(11) ?

### ISSUE THREAD

**Issue by PRTGC** [rust-lang/rust-analyzer#14304]
**VSCode** Version: 1.76.0 (system setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**rust-analyzer version:** 0.3.1426-standalone (0a956ec93 2023-03-05)

**rustc version**: rustc 1.68.0 (2c8cc3432 2023-03-06)

**relevant settings**: no changes from Default

Hi...

It seems there may be a memory problem in Windows11 / vscode...
After it runs for a while I get this:
```
Image			PID	HFaults/sec	Commit (KB)	Working Set (KB)	Shareable (KB)	Private (KB)
rust-analyzer.exe	2628	0		24,842,288	733,548			12,400		721,148
```
It releases when I restart it...
After Indexing it is back
Thoughts ?
Thanks
  JR

**Comment by PRTGC** [comment]
Hi...
Thanks for getting back to me..

It happens when I have multiple folders/project open in a workspace.
As an example..
One project by itself is 5gig.
When I add all the other's it creeps up to 25gig.
The strange thing is that these are all the libs that make up the project.
Which should share all the crates

**Comment by CaptainBern** [comment]
It seems like it's leaking on Arch Linux as well. 

In my case it happens a couple minutes after starting vs code (version 1.76.0) using version 0.3.1426 of the rust-analyzer extension. Maybe it's `rustc` related? I'm getting 
```
[ 2878.696686] Out of memory: Killed process 10041 (rustc) total-vm:65385048kB, anon-rss:12284688kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:25132kB oom_score_adj:0
```
in dmesg.

I ran `rust-analyzer diagnostics ./` in the root of my project directory while simultaneously having dmesg open. Before any output was displayed, the oom-killer kicked in 2 times before finally showing the result of the diagnostics command.

Next up I ran `rust-analyzer analysis-stats --memory-usage ./` in my workspace. This time the oom-killer kicked in 3 times, and the command had the following output:
```
❯ rust-analyzer analysis-stats --memory-usage ./
Database loaded:     22.96s, 92minstr, 40mb (metadata 751.52ms, 4063kinstr, 129kb; build 21.68s, 8817kinstr, 40kb)
  crates: 5, mods: 35, decls: 771, fns: 453
Item Collection:     4.97s, 31ginstr, 157mb
  exprs: 7486, ??ty: 150 (2%), ?ty: 32 (0%), !ty: 0
  pats: 897, ??ty: 0 (0%), ?ty: 0 (0%), !ty: 0
Inference:           2.95s, 15ginstr, 81mb
Total:               7.92s, 46ginstr, 239mb
```

I'm posting this here since it seems the issues are related, but let me know if it's more appropriate to create a separate issue.

**Comment by PRTGC** [comment]
I ran the '>rust-analyzer (debug command): Memory Usage (Clears Database)'
It started out qat 14 gig, when it was done It was using 3-ish gig, and crashed
```
Per-query memory usage:
  2541mb HygieneFrameQuery
  1229mb FileItemTreeQuery
  1169mb CrateDefMapQueryQuery
  1124mb AttrsQuery
  1030mb InternMacroCallQuery
   768mb InferQueryQuery
   734mb TraitImplsInDepsQuery
   675mb BodyWithSourceMapQuery
   581mb TraitSolveQueryQuery
    67mb FileTextQuery
    40mb InternFunctionQuery
    19mb ImplDataQuery
    15mb MacroExpandQuery
    15mb ParseMacroExpansionQuery
    15mb AstIdMapQuery
    14mb MacroArgTextQuery
    13mb GenericParamsQuery
     9mb ImplSelfTyQuery
     4mb InternStructQuery
  3940kb InternConstQuery
  1288kb CrateGraphQuery
      0b ParseQuery
      0b FileSourceRootQuery
      0b SourceRootQuery
      0b SourceRootCratesQuery
      0b MacroDefQuery
      0b FieldsAttrsQuery
      0b FieldsAttrsSourceMapQuery
      0b VariantsAttrsSourceMapQuery
      0b StructDataQuery
      0b UnionDataQuery
      0b AssociatedTyDataQuery
      0b InternImplTraitIdQuery
      0b InternTypeOrConstParamIdQuery
      0b LibrarySymbolsQuery
      0b LocalRootsQuery
    -8kb LibraryRootsQuery
   -16kb InternTypeOrConstParamIdQuery
   -28kb InternClosureQuery
   -32kb InternEnumQuery
   -48kb AssociatedTyDataQuery
  -196kb TraitDatumQuery
  -288kb StaticDataQuery
  -408kb ConstDataQuery
  -456kb InternTraitQuery
  -592kb InternStaticQuery
  -672kb LangItemQuery
  -684kb InternCallableDefQuery
  -708kb InternUnionQuery
 -1288kb InternTypeAliasQuery
 -1292kb FunctionDataQuery
 -1592kb FnDefDatumQuery
 -1692kb InternImplQuery
 -1780kb FieldTypesQuery
 -2236kb GenericPredicatesForParamQuery
 -2276kb StructDatumQuery
 -2728kb VariantsAttrsQuery
 -3416kb TyQuery
 -3488kb ReturnTypeImplTraitsQuery
 -3564kb ValueTyQuery
    -4mb TraitDataQuery
    -4mb TraitEnvironmentQuery
    -6mb TypeAliasDataQuery
    -7mb CallableItemSignatureQuery
    -7mb BlockDefMapQuery
   -12mb EnumDataQuery
   -14mb AssociatedTyValueQuery
   -15mb GenericPredicatesQuery
   -18mb ExprScopesQuery
   -22mb InherentImplsInCrateQuery
   -26mb CrateLangItemsQuery
   -27mb LineIndexQuery
   -29mb ImplTraitQuery
   -52mb BodyQuery
   -73mb ModuleSymbolsQuery
   -88mb GenericDefaultsQuery
  -100mb TraitImplsInCrateQuery
  -121mb ImplDatumQuery
  -227mb ImportMapQuery
  6417mb Remaining

(note: database has been cleared)
```
```stack
thread 'Worker' panicked at 'no value set for FileTextQuery(FileId(667))', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.17.0-pre.2\src\input.rs:106:32
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
   2: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   3: <DB as base_db::SourceDatabaseExt>::file_text
   4: <ide_db::LineIndexQuery as salsa::plumbing::QueryFunction>::execute
   5: salsa::runtime::Runtime::execute_query_implementation
   6: core::ptr::drop_in_place<alloc::sync::Arc<ide_db::symbol_index::SymbolIndex>>
   7: salsa::derived::slot::Slot<Q,MP>::read
   8: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   9: std::panicking::try
  10: rust_analyzer::global_state::GlobalStateSnapshot::file_line_index
  11: rust_analyzer::from_proto::file_range
  12: rust_analyzer::handlers::handle_hover
  13: std::panicking::try
  14: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'Worker' panicked at 'no value set for FileTextQuery(FileId(666))', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.17.0-pre.2\src\input.rs:106:32
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
   2: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   3: <DB as base_db::SourceDatabaseExt>::file_text
   4: <ide_db::LineIndexQuery as salsa::plumbing::QueryFunction>::execute
   5: salsa::runtime::Runtime::execute_query_implementation
   6: core::ptr::drop_in_place<alloc::sync::Arc<ide_db::symbol_index::SymbolIndex>>
   7: salsa::derived::slot::Slot<Q,MP>::read
   8: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   9: std::panicking::try
  10: rust_analyzer::global_state::GlobalStateSnapshot::file_line_index
  11: rust_analyzer::handlers::publish_diagnostics
  12: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  13: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'LspServer' panicked at 'no value set for FileSourceRootQuery(FileId(343))', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.17.0-pre.2\src\input.rs:106:32
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
   2: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   3: <DB as base_db::SourceDatabaseExt>::file_source_root
   4: base_db::change::Change::apply
   5: ide_db::apply_change::<impl ide_db::RootDatabase>::apply_change
   6: rust_analyzer::global_state::GlobalState::new
   7: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   8: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   9: rust_analyzer::main_loop::main_loop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', lib\lsp-server\src\stdio.rs:26:37
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\panicking.rs:64
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library\core\src\result.rs:1791
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 11:31:50 PM] Connection to server got closed. Server will restart.
```

**Comment by PRTGC** [comment]
Here is the output with Pre-Release version:
```
INFO [3/14/2023, 12:40:59 PM]: Using server binary at ...\.vscode\extensions\rust-lang.rust-analyzer-0.4.1436-win32-x64\server\rust-analyzer.exe
INFO [3/14/2023, 12:41:00 PM]: ...\.vscode\extensions\rust-lang.rust-analyzer-0.4.1436-win32-x64\server\rust-analyzer.exe --version: {
  status: 0,
  signal: null,
  output: [
    null,
    'rust-analyzer 0.4.1436-standalone (954975335 2023-03-13)\n',
    ''
  ],
  pid: 24044,
  stdout: 'rust-analyzer 0.4.1436-standalone (954975335 2023-03-13)\n',
  stderr: ''
```

It started out at 25gig
```
Per-query memory usage:
  6845mb HygieneFrameQuery
  3431mb FileItemTreeQuery
  3099mb CrateDefMapQueryQuery
  2263mb AttrsQuery
  1489mb MacroDefQuery
  1149mb ExprScopesQuery
   880mb EnumDataWithDiagnosticsQuery
   852mb ImportMapQuery
   677mb TraitImplsInCrateQuery
   594mb TraitSolveQueryQuery
   582mb MirBodyQuery
   417mb InternMacroRulesQuery
   358mb GenericDefaultsQuery
   334mb GenericPredicatesQuery
   316mb InternImplQuery
   281mb ImplTraitQuery
   250mb InternConstQuery
   218mb InternBlockQuery
   193mb InternMacroCallQuery
   166mb ImplDatumQuery
   149mb ProgramClausesForChalkEnvQuery
   132mb InternTypeAliasQuery
   104mb TraitImplsInDepsQuery
    95mb InternProcMacroQuery
    77mb InternFunctionQuery
    67mb FileTextQuery
    31mb MacroArgTextQuery
    30mb AstIdMapQuery
    30mb ParseMacroExpansionQuery
    30mb MacroExpandErrorQuery
    30mb MacroExpandQuery
    23mb ImplDataQuery
     9mb InternStructQuery
     6mb ImplSelfTyQuery
  2576kb CrateGraphQuery
  1200kb InternTraitQuery
   932kb InternEnumQuery
   768kb InternCallableDefQuery
   428kb InternStaticQuery
    68kb LocalRootsQuery
      0b ParseQuery
      0b FileSourceRootQuery
      0b SourceRootQuery
      0b SourceRootCratesQuery
      0b StructDataQuery
      0b UnionDataQuery
      0b UnionDataWithDiagnosticsQuery
      0b TraitAliasDataQuery
      0b ConstDataQuery
      0b StaticDataQuery
      0b Macro2DataQuery
      0b MacroRulesDataQuery
      0b ProcMacroDataQuery
      0b VariantsAttrsSourceMapQuery
      0b FieldsAttrsSourceMapQuery
      0b CrateSupportsNoStdQuery
      0b ConstEvalQuery
      0b InternLifetimeParamIdQuery
      0b InternImplTraitIdQuery
      0b InternGeneratorQuery
      0b FnDefVarianceQuery
      0b LibrarySymbolsQuery
      0b LibraryRootsQuery
      0b InternTraitAliasQuery
   -48kb FunctionVisibilityQuery
  -148kb ConstEvalDiscriminantQuery
  -228kb FnDefDatumQuery
  -268kb ConstVisibilityQuery
  -332kb ConstParamTyQuery
  -496kb InternClosureQuery
  -520kb FieldVisibilitiesQuery
  -520kb InternMacro2Query
  -524kb ValueTyQuery
  -688kb TraitImplsInBlockQuery
 -1004kb InternUnionQuery
 -1292kb InternTypeOrConstParamIdQuery
 -1480kb FieldsAttrsQuery
 -1872kb InherentImplsInBlockQuery
 -1900kb AssociatedTyDataQuery
 -1936kb FieldTypesQuery
 -2348kb ReturnTypeImplTraitsQuery
 -2464kb TraitDataQuery
 -2628kb StructDataWithDiagnosticsQuery
 -2696kb IncoherentInherentImplCratesQuery
    -4mb TraitDatumQuery
    -4mb TargetDataLayoutQuery
    -5mb StructDatumQuery
    -5mb TyQuery
    -9mb LayoutOfAdtQuery
   -10mb GenericPredicatesForParamQuery
   -11mb CallableItemSignatureQuery
   -13mb ExpandProcMacroQuery
   -13mb BlockDefMapQuery
   -14mb FunctionDataQuery
   -15mb TraitEnvironmentQuery
   -16mb LineIndexQuery
   -16mb VariantsAttrsQuery
   -17mb AdtVarianceQuery
   -18mb LangItemQuery
   -25mb EnumDataQuery
   -42mb BodyWithSourceMapQuery
   -49mb BodyQuery
   -53mb InherentImplsInCrateQuery
   -58mb AssociatedTyValueQuery
   -60mb BorrowckQuery
   -64mb InternExternBlockQuery
   -65mb CrateLangItemsQuery
   -95mb GenericParamsQuery
   -99mb InferQueryQuery
  -102mb ModuleSymbolsQuery
  -103mb TypeAliasDataQuery
  -117mb ImplDataWithDiagnosticsQuery
  -241mb TraitDataWithDiagnosticsQuery
   907mb Remaining

(note: database has been cleared)
```

**Comment by pcjentsch** [comment]
This is also happening for me on arch linux and ubuntu, rust-analyzer will pin all cpus at 100% and use over 64gb of RAM.

**Comment by Veykril** [comment]
I'll close this, we had some improvements regarding certain memory hogging things (VFS duplicating all files in memory, `HygieneFrameqQuery` being gone). Please file a new issue if you run into something that looks like a leak again.

**Comment by PRTGC** [comment]
@Veykril .

It's looking much better..
 It's been running for 6hrs now and the memory consumption seams fairly stable..
 The Active vs committed memory is fairly close..
 
 Thanks for getting it fixed...
   JR
