### ISSUE TITLE
Panic in `inline_call` assist

### ISSUE THREAD

**Issue by VincentWo** [rust-lang/rust-analyzer#14339]
Going on the marked line in this snippet of code gives the correct diagnostic of missing match arms, but requesting code actions leads to a panic in rust-analyzer. 
```
use std::str::FromStr;
enum Test {}

impl FromStr for Test {
    type Err = ();

    fn from_str(_s: &str) -> Result<Self, Self::Err> {
        todo!()
    }
}

fn test_function() {
    let test = "test";

    match test.parse::<Test>() {} // Crashes here
}

fn main() {
    let _ = test_function();
}
```

The panic message is:
```
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', crates/syntax/src/ast/node_ext.rs:45:71\n"
stack backtrace:\n"
   0: _rust_begin_unwind\n"
   1: core::panicking::panic_fmt\n"
   2: core::panicking::panic\n"
   3: syntax::ast::node_ext::text_of_first_token\n"
   4: <hir_expand::hygiene::Hygiene>::name_ref_to_name\n"
   5: hir_def::path::lower::lower_path\n"
   6: <hir::semantics::SemanticsScope>::speculative_resolve\n"
   7: <ide_db::path_transform::Ctx>::apply\n"
   8: <ide_db::path_transform::PathTransform>::apply\n"
   9: ide_assists::handlers::inline_call::inline\n"
  10: <ide_assists::assist_context::Assists>::add::<alloc::string::String, ide_assists::handlers::inline_call::inline_call::{closure#0}>::{closure#0}\n"
  11: <ide_assists::assist_context::Assists>::add_impl\n"
  12: <ide_assists::assist_context::Assists>::add::<alloc::string::String, ide_assists::handlers::inline_call::inline_call::{closure#0}>\n"
  13: ide_assists::handlers::inline_call::inline_call\n"
  14: ide_assists::assists\n"
  15: std::panicking::try::<alloc::vec::Vec<ide_db::assists::Assist>, <ide::Analysis>::with_db<<ide::Analysis>::assists_with_fixes::{closure#1}, alloc::vec::Vec<ide_db::assists::Assist>>::{closure#0}>\n"
  16: <ide::Analysis>::assists_with_fixes\n"
  17: rust_analyzer::handlers::handle_code_action\n"
  18: std::panicking::try::<core::result::Result<core::option::Option<alloc::vec::Vec<rust_analyzer::lsp_ext::CodeAction>>, alloc::boxed::Box<dyn core::error::Error + core::marker::Sync + core::marker::Send>>, <rust_analyzer::dispatch::RequestDispatcher>::on<rust_analyzer::lsp_ext::CodeActionRequest>::{closure#0}::{closure#0}>\n"
  19: <<rust_analyzer::task_pool::TaskPool<rust_analyzer::main_loop::Task>>::spawn<<rust_analyzer::dispatch::RequestDispatcher>::on<rust_analyzer::lsp_ext::CodeActionRequest>::{closure#0}>::{closure#0} as threadpool::FnBox>::call_box\n"
```
I already tried reducing the example by providing my own version of the `parse` function and the `FromStr` Trait, but this led to no longer being able to produce the error.

I hope that this information is helpful :)

Attached the log (quite long): [logfile.zip](https://github.com/rust-lang/rust-analyzer/files/10958702/logfile.zip)

**rust-analyzer version**: rust-analyzer 1.70.0-nightly (7b4f4892 2023-03-12)

**rustc version**: rustc 1.70.0-nightly (7b4f48927 2023-03-12)

**relevant settings**: Reproduced without any settings, on MacOS

<details>
  <summary>
    And the whole Panic Context, if helpfull:
  </summary>

```
Panic context:\n"
version: 1.70.0-nightly (7b4f4892 2023-03-12)\n"
request: textDocument/codeAction CodeActionParams {\n"
    text_document: TextDocumentIdentifier {\n"
        uri: Url {\n"
            scheme: \"file\",\n"
            cannot_be_a_base: false,\n"
            username: \"\",\n"
            password: None,\n"
            host: None,\n"
            port: None,\n"
            path: \"/Users/titania/programming/rustanalyzer-crash/src/main.rs\",\n"
            query: None,\n"
            fragment: None,\n"
        },\n"
    },\n"
    range: Range {\n"
        start: Position {\n"
            line: 14,\n"
            character: 18,\n"
        },\n"
        end: Position {\n"
            line: 14,\n"
            character: 19,\n"
        },\n"
    },\n"
    context: CodeActionContext {\n"
        diagnostics: [\n"
            Diagnostic {\n"
                range: Range {\n"
                    start: Position {\n"
                        line: 14,\n"
                        character: 10,\n"
                    },\n"
                    end: Position {\n"
                        line: 14,\n"
                        character: 30,\n"
                    },\n"
                },\n"
                severity: Some(\n"
                    Error,\n"
                ),\n"
                code: Some(\n"
                    String(\n"
                        \"E0004\",\n"
                    ),\n"
                ),\n"
                code_description: None,\n"
                source: Some(\n"
                    \"rustc\",\n"
                ),\n"
                message: \"non-exhaustive patterns: `Ok(_)` and `Err(_)` not covered\\nthe matched value is of type `std::result::Result<Test, ()>`\",\n"
                related_information: None,\n"
                tags: None,\n"
                data: Some(\n"
                    Object {\n"
                        \"rendered\": String(\"error[E0004]: non-exhaustive patterns: `Ok(_)` and `Err(_)` not covered\\n   --> src/main.rs:15:11\\n    |\\n15  |     match test.parse::<Test>() {} // It crashes here\\n    |           ^^^^^^^^^^^^^^^^^^^^ patterns `Ok(_)` and `Err(_)` not covered\\n    |\\nnote: `std::result::Result<Test, ()>` defined here\\n   --> /Users/titania/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:507:5\\n    |\\n503 | pub enum Result<T, E> {\\n    | ---------------------\\n...\\n507 |     Ok(#[stable(feature = \\\"rust1\\\", since = \\\"1.0.0\\\")] T),\\n    |     ^^ not covered\\n...\\n512 |     Err(#[stable(feature = \\\"rust1\\\", since = \\\"1.0.0\\\")] E),\\n    |     ^^^ not covered\\n    = note: the matched value is of type `std::result::Result<Test, ()>`\\nhelp: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern, a match arm with multiple or-patterns as shown, or multiple match arms\\n    |\\n15  ~     match test.parse::<Test>() {\\n16  +         Ok(_) | Err(_) => todo!(),\\n17  ~     } // It crashes here\\n    |\\n\\n\"),\n"
                    },\n"
                ),\n"
            },\n"
        ],\n"
        only: None,\n"
        trigger_kind: None,\n"
    },\n"
    work_done_progress_params: WorkDoneProgressParams {\n"
        work_done_token: None,\n"
    },\n"
    partial_result_params: PartialResultParams {\n"
        partial_result_token: None,\n"
    },\n"
}\n"
\n"
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', crates/syntax/src/ast/node_ext.rs:45:71\n"
stack backtrace:\n"
   0: _rust_begin_unwind\n"
   1: core::panicking::panic_fmt\n"
   2: core::panicking::panic\n"
   3: syntax::ast::node_ext::text_of_first_token\n"
   4: <hir_expand::hygiene::Hygiene>::name_ref_to_name\n"
   5: hir_def::path::lower::lower_path\n"
   6: <hir::semantics::SemanticsScope>::speculative_resolve\n"
   7: <ide_db::path_transform::Ctx>::apply\n"
   8: <ide_db::path_transform::PathTransform>::apply\n"
   9: ide_assists::handlers::inline_call::inline\n"
  10: <ide_assists::assist_context::Assists>::add::<alloc::string::String, ide_assists::handlers::inline_call::inline_call::{closure#0}>::{closure#0}\n"
  11: <ide_assists::assist_context::Assists>::add_impl\n"
  12: <ide_assists::assist_context::Assists>::add::<alloc::string::String, ide_assists::handlers::inline_call::inline_call::{closure#0}>\n"
  13: ide_assists::handlers::inline_call::inline_call\n"
  14: ide_assists::assists\n"
  15: std::panicking::try::<alloc::vec::Vec<ide_db::assists::Assist>, <ide::Analysis>::with_db<<ide::Analysis>::assists_with_fixes::{closure#1}, alloc::vec::Vec<ide_db::assists::Assist>>::{closure#0}>\n"
  16: <ide::Analysis>::assists_with_fixes\n"
  17: rust_analyzer::handlers::handle_code_action\n"
  18: std::panicking::try::<core::result::Result<core::option::Option<alloc::vec::Vec<rust_analyzer::lsp_ext::CodeAction>>, alloc::boxed::Box<dyn core::error::Error + core::marker::Sync + core::marker::Send>>, <rust_analyzer::dispatch::RequestDispatcher>::on<rust_analyzer::lsp_ext::CodeActionRequest>::{closure#0}::{closure#0}>\n"
  19: <<rust_analyzer::task_pool::TaskPool<rust_analyzer::main_loop::Task>>::spawn<<rust_analyzer::dispatch::RequestDispatcher>::on<rust_analyzer::lsp_ext::CodeActionRequest>::{closure#0}>::{closure#0} as threadpool::FnBox>::call_box\n"
```
</details>

**Comment by lnicola** [comment]
Can you try with a more recent server binary (e.g. from GitHub Releases)?

**Comment by VincentWo** [comment]
Yes, I am and will try

**Comment by lnicola** [comment]
Never mind, I can reproduce the crash by choosing "Inline `parse`".

**Comment by VincentWo** [comment]
Interesting, even with the downloaded binary I don't even need to choose anything. But this could be just a difference in the client implementation since I am using Helix
