### ISSUE TITLE
internal error: entered unreachable code: MIR lower implementation bug: unsized temporaries

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust-analyzer#14545]
```text

thread 'Worker' panicked at 'internal error: entered unreachable code: MIR lower implementation bug: unsized temporaries', crates\hir-ty\src\mir\lower.rs:122:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library\std\src\panicking.rs:579
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library\core\src\panicking.rs:64
   2: core::ptr::drop_in_place<hir_ty::mir::Place>
   3: hir_ty::mir::lower::as_place::<impl hir_ty::mir::lower::MirLowerCtx>::lower_expr_as_place
   4: hir_ty::mir::lower::MirLowerCtx::lower_block_to_place
   5: hir_ty::mir::lower::MirLowerCtx::lower_expr_to_some_operand
   6: hir_ty::mir::lower::MirLowerCtx::lower_expr_to_some_operand
   7: hir_ty::mir::lower::MirLowerCtx::lower_expr_to_some_operand
   8: hir_ty::mir::lower::lower_to_mir
   9: hir_ty::mir::lower::mir_body_query
  10: salsa::runtime::Runtime::execute_query_implementation
  11: core::ptr::drop_in_place<core::option::Option<chalk_ir::Variances<hir_ty::interner::Interner>>>
  12: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  13: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  14: hir_ty::db::HirDatabaseGroupStorage__::maybe_changed_since
  15: <ide_db::RootDatabase as salsa::plumbing::DatabaseOps>::maybe_changed_since
  16: salsa::derived::slot::MemoRevisions::validate_memoized_value
  17: core::ptr::drop_in_place<core::option::Option<chalk_ir::Variances<hir_ty::interner::Interner>>>
  18: salsa::derived::slot::Slot<Q,MP>::read
  19: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  20: <DB as hir_ty::db::HirDatabase>::borrowck::__shim
  21: <DB as hir_ty::db::HirDatabase>::borrowck
  22: hir::DefWithBody::diagnostics
  23: hir::Module::diagnostics
  24: ide_diagnostics::diagnostics
  25: std::panicking::try
  26: ide::Analysis::assists_with_fixes
  27: rust_analyzer::handlers::handle_code_action
  28: std::panicking::try
  29: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Veykril** [comment]
Actually I was on an older pinned version so this might be outdated
