### ISSUE TITLE
Tuple pattern parameter + array let binding causes panic

### ISSUE THREAD

**Issue by vallentin** [rust-lang/rust-analyzer#14624]
Having a function with a tuple pattern as a parameter + an array let binding in the function body, causes rust-analyzer to panic.

Reproducing is as simple as `cargo new foo` or `cargo new --lib foo` and pasting the following in `main.rs`/`lib.rs`:

```rust
fn foo((x,): (u32,)) {
    let foo = [0; 3];
}
```

or

```rust
fn foo((x, y): (f32, f32)) {
    let foo = [10; 5];
}
```

or

```rust
fn foo((x, y, z): (bool, bool, bool)) {
    let foo = [123; 10];
}
```

or

```rust
fn foo((x, (y, z)): (bool, (bool, bool))) {
    let foo = [(1, 2); 10];
}
```

![image](https://user-images.githubusercontent.com/17464404/233756238-78cc8d12-7ed7-44d5-8673-c3af9d891781.png)

**Output:**

```text
[Error - 4:14:54 AM] Request textDocument/semanticTokens/full/delta failed.
  Message: request handler panicked: index out of bounds: the len is 0 but the index is 0
  Code: -32603 
thread 'Worker' panicked at 'index out of bounds: the len is 0 but the index is 0', crates\hir-ty\src\mir\lower\pattern_matching.rs:132:36
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
   2: core::panicking::panic_bounds_check
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:159
   3: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   4: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   5: hir_ty::mir::lower::lower_to_mir
   6: hir_ty::consteval::eval_to_const
   7: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   8: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  10: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  11: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  12: hir_ty::infer::infer_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as hir_ty::db::HirDatabase>::infer_query
  18: hir_ty::db::infer_wait
  19: <DB as hir_ty::db::HirDatabase>::infer
  20: hir::DefWithBody::diagnostics
  21: hir::ModuleDef::diagnostics
  22: hir::Module::diagnostics
  23: ide_diagnostics::diagnostics
  24: salsa::Cancelled::catch
  25: ide::Analysis::diagnostics
  26: rust_analyzer::handlers::publish_diagnostics
  27: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  28: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.3.1481-standalone (bab80dae4 2023-04-16)
request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Users/vallentin/Desktop/foo/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    previous_result_id: "155",
}

thread 'Worker' panicked at 'index out of bounds: the len is 0 but the index is 0', crates\hir-ty\src\mir\lower\pattern_matching.rs:132:36
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
   2: core::panicking::panic_bounds_check
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:159
   3: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   4: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   5: hir_ty::mir::lower::lower_to_mir
   6: hir_ty::consteval::eval_to_const
   7: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   8: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  10: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  11: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  12: hir_ty::infer::infer_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as hir_ty::db::HirDatabase>::infer_query
  18: hir_ty::db::infer_wait
  19: <DB as hir_ty::db::HirDatabase>::infer
  20: hir::source_analyzer::SourceAnalyzer::new_for_body
  21: hir::semantics::SemanticsImpl::analyze_impl
  22: ide_db::defs::NameClass::classify
  23: ide::syntax_highlighting::highlight::name_like
  24: ide::syntax_highlighting::highlight
  25: std::panicking::try
  26: rust_analyzer::handlers::handle_semantic_tokens_full_delta
  27: std::panicking::try
  28: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```text
[Error - 4:14:56 AM] Request textDocument/inlayHint failed.
  Message: request handler panicked: index out of bounds: the len is 0 but the index is 0
  Code: -32603 
Panic context:
> 
version: 0.3.1481-standalone (bab80dae4 2023-04-16)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Users/vallentin/Desktop/foo/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 15,
            character: 0,
        },
    },
}

thread 'Worker' panicked at 'index out of bounds: the len is 0 but the index is 0', crates\hir-ty\src\mir\lower\pattern_matching.rs:132:36
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
   2: core::panicking::panic_bounds_check
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:159
   3: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   4: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   5: hir_ty::mir::lower::lower_to_mir
   6: hir_ty::consteval::eval_to_const
   7: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   8: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  10: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  11: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  12: hir_ty::infer::infer_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as hir_ty::db::HirDatabase>::infer_query
  18: hir_ty::db::infer_wait
  19: <DB as hir_ty::db::HirDatabase>::infer
  20: hir::source_analyzer::SourceAnalyzer::new_for_body
  21: hir::semantics::SemanticsImpl::analyze_impl
  22: ide::inlay_hints::hints
  23: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  24: std::panicking::try
  25: rust_analyzer::handlers::handle_inlay_hints
  26: std::panicking::try
  27: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 4:14:56 AM] Request textDocument/inlayHint failed.
  Message: request handler panicked: index out of bounds: the len is 0 but the index is 0
  Code: -32603 
Panic context:
> 
version: 0.3.1481-standalone (bab80dae4 2023-04-16)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Users/vallentin/Desktop/foo/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 15,
            character: 0,
        },
    },
}

thread 'Worker' panicked at 'index out of bounds: the len is 0 but the index is 0', crates\hir-ty\src\mir\lower\pattern_matching.rs:132:36
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
   2: core::panicking::panic_bounds_check
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:159
   3: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   4: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   5: hir_ty::mir::lower::lower_to_mir
   6: hir_ty::consteval::eval_to_const
   7: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   8: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  10: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  11: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  12: hir_ty::infer::infer_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as hir_ty::db::HirDatabase>::infer_query
  18: hir_ty::db::infer_wait
  19: <DB as hir_ty::db::HirDatabase>::infer
  20: hir::source_analyzer::SourceAnalyzer::new_for_body
  21: hir::semantics::SemanticsImpl::analyze_impl
  22: ide::inlay_hints::hints
  23: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  24: std::panicking::try
  25: rust_analyzer::handlers::handle_inlay_hints
  26: std::panicking::try
  27: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```text
[Error - 4:16:47 AM] Request textDocument/definition failed.
  Message: request handler panicked: index out of bounds: the len is 0 but the index is 0
  Code: -32603 
Panic context:
> 
version: 0.3.1481-standalone (bab80dae4 2023-04-16)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Users/vallentin/Desktop/foo/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 15,
            character: 0,
        },
    },
}

thread 'Worker' panicked at 'index out of bounds: the len is 0 but the index is 0', crates\hir-ty\src\mir\lower\pattern_matching.rs:132:36
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
   2: core::panicking::panic_bounds_check
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:159
   3: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   4: hir_ty::diagnostics::match_check::deconstruct_pat::DeconstructedPat::to_pat
   5: hir_ty::mir::lower::lower_to_mir
   6: hir_ty::consteval::eval_to_const
   7: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   8: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
   9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_assignee_expr
  10: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  11: hir_ty::chalk_db::<impl chalk_solve::RustIrDatabase<hir_ty::interner::Interner> for hir_ty::traits::ChalkContext>::unification_database
  12: hir_ty::infer::infer_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as hir_ty::db::HirDatabase>::infer_query
  18: hir_ty::db::infer_wait
  19: <DB as hir_ty::db::HirDatabase>::infer
  20: hir::source_analyzer::SourceAnalyzer::new_for_body
  21: hir::semantics::SemanticsImpl::analyze_impl
  22: ide::inlay_hints::hints
  23: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  24: std::panicking::try
  25: rust_analyzer::handlers::handle_inlay_hints
  26: std::panicking::try
  27: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

-----

**rust-analyzer version**: 0.3.1481-standalone (bab80dae4 2023-04-16)
**rustc version**: rustc 1.68.2 (9eb3afe9e 2023-03-27)

**Comment by gcoakes** [comment]
Some regression details. The bug is not observed in the VSCode extension version `v0.3.1443`. I didn't verify if it is absent in any subsequent versions except `v0.3.1481` and the latest prerelease version as of today. I was just doing this to find a working version for my editor not because I was intentionally trying to debug this issue. However, I would assume knowing a good/bad version will help the maintainers fix the issue.

Incidentally, anyone who is looking to workaround this issue in the interim can downgrade to `v0.3.1443`.
