### ISSUE TITLE
rust-analyzer errors and shuts down almost constantly

### ISSUE THREAD

**Issue by lesleyrs** [rust-lang/rust-analyzer#14679]
rust-analyzer 1.69.0 (84c898d6 2023-04-16)
rustc 1.69.0 (84c898d65 2023-04-16)
Windows 10

Ever since updating my editor (helix) to 23.03 the lsp has not been working well at all. It happens in different projects.

The logs are filled with `StreamClosed` and `BrokenPipe` etc:
```
2023-04-28T21:43:58.005 helix_lsp::transport [ERROR] err <- "Panic context:\n"
2023-04-28T21:43:58.005 helix_lsp::transport [ERROR] err <- "> \n"
2023-04-28T21:43:58.005 helix_lsp::transport [ERROR] err <- "version: 1.69.0 (84c898d6 2023-04-16)\n"
2023-04-28T21:43:58.005 helix_lsp::transport [ERROR] err <- "notification: textDocument/didChange\n"
2023-04-28T21:43:58.005 helix_lsp::transport [ERROR] err <- "\n"
2023-04-28T21:43:58.005 helix_lsp::transport [ERROR] err <- "thread 'LspServer' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\\library\\alloc\\src\\string.rs:1819:29\n"
2023-04-28T21:43:58.006 helix_lsp::transport [ERROR] err <- "stack backtrace:\n"
2023-04-28T21:43:58.057 helix_lsp::transport [ERROR] err <- "note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
2023-04-28T21:43:58.061 helix_lsp::transport [ERROR] err <- "thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: \"SendError(..)\"', lib\\lsp-server\\src\\stdio.rs:26:37\n"
2023-04-28T21:43:58.062 helix_lsp::transport [ERROR] err <- "stack backtrace:\n"
2023-04-28T21:43:58.063 helix_lsp::transport [ERROR] err <- "note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
```

I asked them about it and they said this:
>Since 23.03 helix uses utf-8 instead of utf-16 to communicate with RA (which is more efficent because both RA and helix use utf-8 internally) so this could very well be an upstream bug.

There's no relevant issue in their repo. The issue is quite big though, I have to restart r-a multiple times an hour sometimes, pls help.

**Comment by pascalkuthe** [comment]
This is a bug on our (helix) end, should be fixed by https://github.com/helix-editor/helix/pull/6921
