### ISSUE TITLE
Rust-Analyzer doesn't want to find libclang on linux

### ISSUE THREAD

**Issue by TheVonKanar** [rust-lang/rust-analyzer#14771]
Hi there!

I wanted to use the nokhwa crate, but Rust-Analyzer panics right after adding the crate to my (empty) project. I get the error:

`process didn't exit successfully: `/home/tvk/Documents/microbit-experiments/app/target/debug/build/v4l2-sys-mit-f74cb4212a5a55e7/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/tvk/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.56.0/src/lib.rs:1922:31
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
     1: core::panicking::panic_fmt
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
     2: core::result::unwrap_failed
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
     3: core::result::Result<T,E>::expect
     4: core::ops::function::FnOnce::call_once
     5: lazy_static::lazy::Lazy<T>::get::{{closure}}
     6: std::sync::once::Once::call_once::{{closure}}
     7: std::sys_common::once::futex::Once::call
     8: std::sync::once::Once::call_once
     9: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
    10: bindgen::ensure_libclang_is_loaded
    11: bindgen::Bindings::generate
    12: bindgen::Builder::generate
    13: build_script_build::main
    14: core::ops::function::FnOnce::call_once`

I have tried installing clang, libclang-dev and so on, to no avail. I also tried setting the env variable LIBCLANG_PATH to where the .so file is, both using export in the terminal and as an extraEnv in the analyzer settings, but it doesn't work either.

I'm a bit lost as to why this is happening and running low on ideas.

I'm using pop!_OS distrib (based on ubuntu).
rust-analyzer version => v0.3.1506
rustc -V => 1.69.0

**Comment by lnicola** [comment]
You shouldn't need to set any environment variable.

Does it work if you run `cargo build` from a terminal?

**Comment by zRegle** [comment]
> You shouldn't need to set any environment variable.
> 
> Does it work if you run `cargo build` from a terminal?

same problem happens to me. any advice now?

**Comment by vhscom** [comment]
Seeing libclang missing error right after adding bingen using a [2-minute ffi tutorial](https://www.youtube.com/watch?v=KWrfxKUBIuo) for beginners. I'm running Analyzer in the VSCodium Flatpak and have configured it to run correctly using Flatseal [per the manual](https://rust-analyzer.github.io/manual.html#vs-code-or-vscodium-in-flatpak). It's only after trying to add a build depends on `bindgen` and using `cc` to compile C in a `build.rs` file that this error appears for me in the `rust-analyzer` output. I do not see the error when I run `cargo build`.

**Comment by vhscom** [comment]
Installed VSCodium *without* the Flatpak sandbox, installed the rust-analyzer once again and my clang compiler issues disappeared. Before bailing on the VSCodium Flatpak I did install LLVM from `org.gnome.Sdk` and `locate libclang.so` locates it but something about the Flatpak sandbox gets in the way at this point even after following the rust-analyzer setup docs.

**Comment by ChayimFriedman2** [comment]
Likely irrelevant by now.
