### ISSUE TITLE
rust-analyzer installation error

### ISSUE THREAD

**Issue by emirhanyasin** [rust-lang/rust-analyzer#14877]
Hi,

I have the below error when installing rust-analyzer extension for VS-Code. I am using v0.3.1377 since as I see, newer versions require GLIBC_2.25 and centos does not support it. How can I resolve the below issue? I think it is about paths, since I can run the rust-analyzer --version command when I go into the file and run it manually. (Note: Everything is done on remote server)

INFO [5/23/2023, 2:06:25 PM]: Starting language client
INFO [5/23/2023, 2:06:26 PM]: Using server binary at /home/centos/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1377-linux-x64/server/rust-analyzer
ERROR [5/23/2023, 2:06:26 PM]: Bootstrap error [Error: Failed to execute /home/centos/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1377-linux-x64/server/rust-analyzer --version
	at Vv (/home/centos/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1377-linux-x64/out/main.js:83:4925)
	at async Ca.getOrCreateClient (/home/centos/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1377-linux-x64/out/main.js:96:1720)
	at async Ca.start (/home/centos/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1377-linux-x64/out/main.js:96:2549)
	at async /home/centos/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1377-linux-x64/out/main.js:101:293
	at async e.ExtHostCommands.h (/home/centos/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:99:125307)]

Thanks,

**Comment by lnicola** [comment]
You can build from source on your CentOS 7, place the binary somewhere and set the path to it in settings.

**Comment by ChayimFriedman2** [comment]
Probably irrelevant by now.
