### ISSUE TITLE
`cannot find attr at index AttrId { id: 96 }` when browsing `ndarray`

### ISSUE THREAD

**Issue by SludgePhD** [rust-lang/rust-analyzer#15007]
In ndarray 0.15.6, scrolling around in `lib.rs` near the definition of `ArrayBase` causes loads of panics like this:

```
thread 'Worker' panicked at 'cannot find attr at index AttrId { id: 96 }', crates/hir-def/src/attr.rs:662:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: ide::syntax_highlighting::inject::doc_comment
   3: ide::syntax_highlighting::highlight
   4: std::panicking::try
   5: rust_analyzer::handlers::request::handle_semantic_tokens_range
   6: std::panicking::try
   7: <F as threadpool::FnBox>::call_box
```

**Comment by Veykril** [comment]
Can't reproduce this so likely got fixed over time
