### ISSUE TITLE
Unable to load and parse grammar for scope `rustdoc.markdown.injection`

### ISSUE THREAD

**Issue by ulugbekna** [rust-lang/rust-analyzer#15011]
# Description

Opening vscode insiders, I see this error in the dev console: 

```
  ERR Unable to load and parse grammar for scope rustdoc.markdown.injection from file:///Users/ulugbekna/.vscode-insiders/extensions/rust-lang.rust-analyzer-0.3.1541-darwin-arm64/rustdoc.markdown.injection.tmGrammar.json Error: Unable to read file '/Users/ulugbekna/.vscode-insiders/extensions/rust-lang.rust-analyzer-0.3.1541-darwin-arm64/rustdoc.markdown.injection.tmGrammar.json' (Error: Unable to resolve nonexistent file '/Users/ulugbekna/.vscode-insiders/extensions/rust-lang.rust-analyzer-0.3.1541-darwin-arm64/rustdoc.markdown.injection.tmGrammar.json')
    at e.FileService.w (fileService.ts:607:10)
    at e.FileService.v (fileService.ts:592:15)
    at async e.FileService.u (fileService.ts:504:18)
    at async e.ExtensionResourceLoaderService.readExtensionResource (extensionResourceLoaderService.ts:36:18)
    at async Object.loadGrammar (TMGrammarFactory.ts:54:22)
    at async t.Registry._doLoadSingleGrammar (main.js:85:15)
    at async Promise.all (index 15)
    at async t.Registry._loadGrammar (main.js:72:47)
    at async L.createGrammar (TMGrammarFactory.ts:141:14)
    at async e.TextMateTokenizationFeature.L (textMateTokenizationFeatureImpl.ts:270:14)
    at async R.i (tokenizationRegistry.ts:148:17)
    at async L.getOrCreate (tokenizationRegistry.ts:76:3)
```

# Version info

**rust-analyzer version**: v0.3.1541

**rustc version**: rustc 1.68.2 (9eb3afe9e 2023-03-27)

**vscode version**
```
Version: 1.79.0-insider
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:33:06.501Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by AndreasBackx** [comment]
This is fixed in #15032.
