### ISSUE TITLE
Panic: "internal error: entered unreachable code: Terminator should be none only in construction"

### ISSUE THREAD

**Issue by Philipp-M** [rust-lang/rust-analyzer#15029]
Rust analyzer crashes, when navigating the helix-editor code base (if relevant: file that was opened when the crash occurs: `helix-term/src/ui/completion.rs`), this is the log of helix:

<details>
  <summary>Log</summary>

  ```
2023-06-11T21:18:00.778 helix_lsp::transport [ERROR] rust-analyzer err <- "Panic context:\n"
2023-06-11T21:18:00.778 helix_lsp::transport [ERROR] rust-analyzer err <- "> publish_diagnostics\n"
2023-06-11T21:18:00.778 helix_lsp::transport [ERROR] rust-analyzer err <- "\n"
2023-06-11T21:18:00.778 helix_lsp::transport [ERROR] rust-analyzer err <- "thread 'Worker' panicked at 'internal error: entered unreachable code: Terminator should be none only in construction', crates/hir-ty/src/mir/borrowck.rs:270:13\n"
2023-06-11T21:18:00.778 helix_lsp::transport [ERROR] rust-analyzer err <- "stack backtrace:\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   0: rust_begin_unwind\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "             at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/panicking.rs:593:5\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   1: core::panicking::panic_fmt\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "             at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/core/src/panicking.rs:67:14\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   2: core::panicking::unreachable_display\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   3: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   4: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   5: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   6: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   7: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   8: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "   9: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  10: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  11: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  12: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  13: hir_ty::mir::borrowck::ever_initialized_map::dfs\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  14: hir_ty::mir::borrowck::mutability_of_locals\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  17: core::iter::adapters::try_process\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  18: hir_ty::mir::borrowck::borrowck_query\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  19: salsa::runtime::Runtime::execute_query_implementation\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  21: salsa::derived::slot::Slot<Q,MP>::read\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  23: <DB as hir_ty::db::HirDatabase>::borrowck::__shim\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  24: <DB as hir_ty::db::HirDatabase>::borrowck\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  25: hir::DefWithBody::diagnostics\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  26: hir::Module::diagnostics\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  27: ide_diagnostics::diagnostics\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  28: salsa::Cancelled::catch\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  29: ide::Analysis::diagnostics\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  30: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  31: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "  32: core::ops::function::FnOnce::call_once{{vtable.shim}}\n"
2023-06-11T21:18:00.785 helix_lsp::transport [ERROR] rust-analyzer err <- "note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"
  ```
</details>

**rust-analyzer version**: b7497fcdfadf0e6fec60803d6a668897158e7ba7
**rustc version**: rustc 1.72.0-nightly (498553fc0 2023-05-29)
**relevant settings**:
<details>
  <summary>TOML configuration of helix</summary>

```
[language-server.rust-analyzer.config.rust-analyzer]
[language-server.rust-analyzer.config.rust-analyzer.cargo]
loadOutDirsFromCheck = true

[language-server.rust-analyzer.config.rust-analyzer.checkOnSave]
command = "clippy"

[language-server.rust-analyzer.config.rust-analyzer.completion]
[language-server.rust-analyzer.config.rust-analyzer.completion.autoimport]
enable = true

[language-server.rust-analyzer.config.rust-analyzer.completion.snippets.custom."thread spawn"]
body = ["thread::spawn(move || {", "\t$0", "});"]
description = "Insert a thread::spawn call"
prefix = ["spawn", "tspawn"]
requires = "std::thread"
scope = "expr"

[language-server.rust-analyzer.config.rust-analyzer.experimental]
procAttrMacros = true

[language-server.rust-analyzer.config.rust-analyzer.lens]
methodReferences = true
references = true

[language-server.rust-analyzer.config.rust-analyzer.procMacro]
enable = true
```
</details>

**Comment by Philipp-M** [comment]
Hmm I couldn't even compile rust-analyzer with that rustc version (at first, I should probably open an issue for that...)
For reference:

<details>
  <summary>rustc panic</summary>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:22:85
stack backtrace:
   0:     0x7f2da4616ae1 - std::backtrace_rs::backtrace::libunwind::trace::h49c88cf40170b5d6
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f2da4616ae1 - std::backtrace_rs::backtrace::trace_unsynchronized::hdc6cc34fd8a53678
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2da4616ae1 - std::sys_common::backtrace::_print_fmt::h0c7289f3a8de0b23
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f2da4616ae1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc8e96ca3c7ab0680
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2da46774ff - core::fmt::rt::Argument::fmt::h304ace7fe8bb186b
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/core/src/fmt/rt.rs:138:9
   5:     0x7f2da46774ff - core::fmt::write::ha469f5b722d475f3
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f2da4609cb1 - std::io::Write::write_fmt::h9a4844905af525b3
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/io/mod.rs:1713:15
   7:     0x7f2da46168f5 - std::sys_common::backtrace::_print::ha35f1d4a0d8accc0
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2da46168f5 - std::sys_common::backtrace::print::h690d5e347a585903
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2da46195b7 - std::panicking::default_hook::{{closure}}::h819f1ab5f2b6d32d
  10:     0x7f2da46193a4 - std::panicking::default_hook::hcdf96a30790dc6bb
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/panicking.rs:288:9
  11:     0x7f2da7841c9b - rustc_driver_impl[a4d4d3a5571ac365]::install_ice_hook::{closure#0}
  12:     0x7f2da4619cfd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4d61e66e458ff2d1
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/alloc/src/boxed.rs:1999:9
  13:     0x7f2da4619cfd - std::panicking::rust_panic_with_hook::hb101d99ddd165575
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/panicking.rs:709:13
  14:     0x7f2da4619a51 - std::panicking::begin_panic_handler::{{closure}}::h6826cb5e0c9d0ead
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/panicking.rs:595:13
  15:     0x7f2da4616f16 - std::sys_common::backtrace::__rust_end_short_backtrace::h7a916e155aec8921
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys_common/backtrace.rs:151:18
  16:     0x7f2da46197e2 - rust_begin_unwind
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/panicking.rs:593:5
  17:     0x7f2da4673773 - core::panicking::panic_fmt::h1e09a982e3a0f5bf
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/core/src/panicking.rs:67:14
  18:     0x7f2da4673803 - core::panicking::panic::h6095d4fd94a5d06f
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/core/src/panicking.rs:117:5
  19:     0x7f2da58c189a - <rustc_query_system[87a405621ff42eeb]::dep_graph::dep_node::DepNode<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind> as rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  20:     0x7f2da71f41b3 - <rustc_query_impl[afbf20227aeececa]::plumbing::query_callback<rustc_query_impl[afbf20227aeececa]::query_impl::type_of::QueryType>::{closure#0} as core[f3286e9e8706f8b]::ops::function::FnOnce<(rustc_middle[bbe864f0e242db2d]::ty::context::TyCtxt, rustc_query_system[87a405621ff42eeb]::dep_graph::dep_node::DepNode<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>)>>::call_once
  21:     0x7f2da5a0af5f - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  22:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  23:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  24:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  25:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  26:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  27:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  28:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  29:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  30:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  31:     0x7f2da5a0af01 - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  32:     0x7f2da69edcc7 - rustc_query_system[87a405621ff42eeb]::query::plumbing::try_execute_query::<rustc_query_impl[afbf20227aeececa]::DynamicConfig<rustc_query_system[87a405621ff42eeb]::query::caches::DefaultCache<rustc_middle[bbe864f0e242db2d]::infer::canonical::Canonical<rustc_middle[bbe864f0e242db2d]::ty::ParamEnvAnd<rustc_middle[bbe864f0e242db2d]::ty::Predicate>>, rustc_middle[bbe864f0e242db2d]::query::erase::Erased<[u8; 2usize]>>, false, false, false>, rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt, true>
  33:     0x7f2da69ecb10 - rustc_query_impl[afbf20227aeececa]::query_impl::evaluate_obligation::get_query_incr::__rust_end_short_backtrace
  34:     0x7f2da5aec18b - <rustc_trait_selection[fc83303d8296db2e]::traits::fulfill::FulfillProcessor as rustc_data_structures[12a824cacca4925c]::obligation_forest::ObligationProcessor>::process_obligation
  35:     0x7f2da5ae85c1 - <rustc_data_structures[12a824cacca4925c]::obligation_forest::ObligationForest<rustc_trait_selection[fc83303d8296db2e]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[fc83303d8296db2e]::traits::fulfill::FulfillProcessor>
  36:     0x7f2da6048fef - <rustc_trait_selection[fc83303d8296db2e]::traits::engine::ObligationCtxt>::select_all_or_error
  37:     0x7f2da64d89fb - rustc_hir_analysis[503f58c00922a1fe]::check::wfcheck::check_well_formed
  38:     0x7f2da588ed1c - rustc_query_impl[afbf20227aeececa]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[afbf20227aeececa]::query_impl::check_well_formed::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bbe864f0e242db2d]::query::erase::Erased<[u8; 0usize]>>
  39:     0x7f2da588ecfc - <rustc_query_impl[afbf20227aeececa]::query_impl::check_well_formed::dynamic_query::{closure#2} as core[f3286e9e8706f8b]::ops::function::FnOnce<(rustc_middle[bbe864f0e242db2d]::ty::context::TyCtxt, rustc_hir[d9b9f9911f40a0f6]::hir_id::OwnerId)>>::call_once
  40:     0x7f2da69e9c1b - rustc_query_system[87a405621ff42eeb]::query::plumbing::try_execute_query::<rustc_query_impl[afbf20227aeececa]::DynamicConfig<rustc_query_system[87a405621ff42eeb]::query::caches::VecCache<rustc_hir[d9b9f9911f40a0f6]::hir_id::OwnerId, rustc_middle[bbe864f0e242db2d]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt, true>
  41:     0x7f2da700d054 - rustc_query_system[87a405621ff42eeb]::query::plumbing::force_query::<rustc_query_impl[afbf20227aeececa]::DynamicConfig<rustc_query_system[87a405621ff42eeb]::query::caches::VecCache<rustc_hir[d9b9f9911f40a0f6]::hir_id::OwnerId, rustc_middle[bbe864f0e242db2d]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  42:     0x7f2da700cf21 - <rustc_query_impl[afbf20227aeececa]::plumbing::query_callback<rustc_query_impl[afbf20227aeececa]::query_impl::check_well_formed::QueryType>::{closure#0} as core[f3286e9e8706f8b]::ops::function::FnOnce<(rustc_middle[bbe864f0e242db2d]::ty::context::TyCtxt, rustc_query_system[87a405621ff42eeb]::dep_graph::dep_node::DepNode<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>)>>::call_once
  43:     0x7f2da5a0af5f - <rustc_query_system[87a405621ff42eeb]::dep_graph::graph::DepGraphData<rustc_middle[bbe864f0e242db2d]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  44:     0x7f2da67cc90e - rustc_query_system[87a405621ff42eeb]::query::plumbing::ensure_must_run::<rustc_query_impl[afbf20227aeececa]::DynamicConfig<rustc_query_system[87a405621ff42eeb]::query::caches::VecCache<rustc_span[117707134523a002]::def_id::LocalDefId, rustc_middle[bbe864f0e242db2d]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt>
  45:     0x7f2da71c13d6 - rustc_query_impl[afbf20227aeececa]::query_impl::check_mod_type_wf::get_query_incr::__rust_end_short_backtrace
  46:     0x7f2da6d01355 - std[6a6a68b8bee01aeb]::panicking::try::<(), core[f3286e9e8706f8b]::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures[12a824cacca4925c]::sync::par_for_each_in<&[rustc_hir[d9b9f9911f40a0f6]::hir_id::OwnerId], <rustc_middle[bbe864f0e242db2d]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[503f58c00922a1fe]::check_crate::{closure#5}::{closure#0}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}>>
  47:     0x7f2da6d01277 - rustc_data_structures[12a824cacca4925c]::sync::par_for_each_in::<&[rustc_hir[d9b9f9911f40a0f6]::hir_id::OwnerId], <rustc_middle[bbe864f0e242db2d]::hir::map::Map>::par_for_each_module<rustc_hir_analysis[503f58c00922a1fe]::check_crate::{closure#5}::{closure#0}::{closure#0}>::{closure#0}>
  48:     0x7f2da6d01047 - <rustc_session[11feaee98d748366]::session::Session>::track_errors::<rustc_hir_analysis[503f58c00922a1fe]::check_crate::{closure#5}, ()>
  49:     0x7f2da6cfef8f - rustc_hir_analysis[503f58c00922a1fe]::check_crate
  50:     0x7f2da6cf53b5 - rustc_interface[2e6570d1ddb09ae6]::passes::analysis
  51:     0x7f2da6d4d69a - rustc_query_impl[afbf20227aeececa]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[afbf20227aeececa]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[bbe864f0e242db2d]::query::erase::Erased<[u8; 1usize]>>
  52:     0x7f2da6d4d689 - <rustc_query_impl[afbf20227aeececa]::query_impl::analysis::dynamic_query::{closure#2} as core[f3286e9e8706f8b]::ops::function::FnOnce<(rustc_middle[bbe864f0e242db2d]::ty::context::TyCtxt, ())>>::call_once
  53:     0x7f2da7053f7c - rustc_query_system[87a405621ff42eeb]::query::plumbing::try_execute_query::<rustc_query_impl[afbf20227aeececa]::DynamicConfig<rustc_query_system[87a405621ff42eeb]::query::caches::SingleCache<rustc_middle[bbe864f0e242db2d]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[afbf20227aeececa]::plumbing::QueryCtxt, true>
  54:     0x7f2da7053b24 - rustc_query_impl[afbf20227aeececa]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  55:     0x7f2da6a932e2 - <rustc_interface[2e6570d1ddb09ae6]::queries::QueryResult<&rustc_middle[bbe864f0e242db2d]::ty::context::GlobalCtxt>>::enter::<core[f3286e9e8706f8b]::result::Result<(), rustc_span[117707134523a002]::ErrorGuaranteed>, rustc_driver_impl[a4d4d3a5571ac365]::run_compiler::{closure#1}::{closure#2}::{closure#4}>
  56:     0x7f2da6a92245 - <rustc_interface[2e6570d1ddb09ae6]::interface::Compiler>::enter::<rustc_driver_impl[a4d4d3a5571ac365]::run_compiler::{closure#1}::{closure#2}, core[f3286e9e8706f8b]::result::Result<core[f3286e9e8706f8b]::option::Option<rustc_interface[2e6570d1ddb09ae6]::queries::Linker>, rustc_span[117707134523a002]::ErrorGuaranteed>>
  57:     0x7f2da6a90343 - std[6a6a68b8bee01aeb]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2e6570d1ddb09ae6]::util::run_in_thread_pool_with_globals<rustc_interface[2e6570d1ddb09ae6]::interface::run_compiler<core[f3286e9e8706f8b]::result::Result<(), rustc_span[117707134523a002]::ErrorGuaranteed>, rustc_driver_impl[a4d4d3a5571ac365]::run_compiler::{closure#1}>::{closure#0}, core[f3286e9e8706f8b]::result::Result<(), rustc_span[117707134523a002]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f3286e9e8706f8b]::result::Result<(), rustc_span[117707134523a002]::ErrorGuaranteed>>
  58:     0x7f2da70dd825 - <<std[6a6a68b8bee01aeb]::thread::Builder>::spawn_unchecked_<rustc_interface[2e6570d1ddb09ae6]::util::run_in_thread_pool_with_globals<rustc_interface[2e6570d1ddb09ae6]::interface::run_compiler<core[f3286e9e8706f8b]::result::Result<(), rustc_span[117707134523a002]::ErrorGuaranteed>, rustc_driver_impl[a4d4d3a5571ac365]::run_compiler::{closure#1}>::{closure#0}, core[f3286e9e8706f8b]::result::Result<(), rustc_span[117707134523a002]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f3286e9e8706f8b]::result::Result<(), rustc_span[117707134523a002]::ErrorGuaranteed>>::{closure#1} as core[f3286e9e8706f8b]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  59:     0x7f2da4624225 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h21e0e0330758bd13
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/alloc/src/boxed.rs:1985:9
  60:     0x7f2da4624225 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h07c258ba6721b777
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/alloc/src/boxed.rs:1985:9
  61:     0x7f2da4624225 - std::sys::unix::thread::Thread::new::thread_start::h3bd04e8df530c8c3
                               at /rustc/498553fc04f6a3fdc53412320f4e913bc53bc267/library/std/src/sys/unix/thread.rs:108:17
  62:     0x7f2da43afe24 - start_thread
  63:     0x7f2da44319b0 - __clone3
  64:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0-nightly (498553fc0 2023-05-29) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `salsa::lru::Lru<salsa::derived::slot::Slot<hir_ty::db::ConstEvalQuery, salsa::derived::AlwaysMemoizeValue>>: core::marker::Sync`
#1 [check_well_formed] checking that `<impl at crates/ide-db/src/lib.rs:321:1: 321:46>` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 TraitSelect(24500c03c0a23ccc-4784803b0771aedf)
#1 TraitSelect(71c98113f3108ba4-97c33c08f028d442)
#2 TraitSelect(b524eb1ce9539211-ab250f4c59da53c9)
#3 TraitSelect(f29833ab896abe6f-f1583f1b8708643e)
#4 TraitSelect(bf1ff8f419855503-b0ebb53201f0ca69)
#5 TraitSelect(aef4ecd5597b21c4-45c4eedcf643e601)
#6 TraitSelect(673d7afc5e0ab6cc-63fd9f29a77c3636)
#7 TraitSelect(caf81344316907e-ded0683c2dcf023c)
#8 TraitSelect(63f532b1c26c0420-bc3ce263bd7ad324)
#9 TraitSelect(ad9c77ba967db5ed-d8993f48843797ae)
#10 evaluate_obligation(375d1d3a617465aa-7609ac755e61ac76)
end of try_mark_green dep node stack
there was a panic while trying to force a dep node
try_mark_green dep node stack:
#0 check_mod_type_wf(ide_db[240d])
end of try_mark_green dep node stack
error: could not compile `ide-db` (lib)
error: failed to compile `rust-analyzer v0.0.0 (/home/philm/dev/personal/rust/rust-analyzer/crates/rust-analyzer)`, intermediate artifacts can be found at `/home/philm/dev/personal/rust/rust-analyzer/target`
Error: install server

Caused by:
    command exited with non-zero code `cargo install --path crates/rust-analyzer --locked --force --features force-always-assert`: 101
```
</details>

Then I switched to a newer nightly rust version and haven't had the panic, out of curiosity I switched back to the old nightly (which I had the issue(s) with) and compilation went through, weird. Maybe broken intermediate state that caused an issue that was "cleaned up" when switching between the rust versions.

Anyway I couldn't reproduce the issue anymore (with either rust versions), I guess I'm closing it for now, and if it occurs again, I'll reopen it, thanks for investigating!

**Comment by lnicola** [comment]
> Hmm I couldn't even compile rust-analyzer with that rustc version (at first, I should probably open an issue for that...)

`cargo clean` usually fixes those.

**Comment by Philipp-M** [comment]
Yeah, I have also deleted the target dir in between. It would be interesting, if this issue, was a compiler bug (because of dirty intermediate/incremental state) and somehow introduced a bug into rust-analyzer as well.

**Comment by HKalbasi** [comment]
> It would be interesting, if this issue, was a compiler bug (because of dirty intermediate/incremental state) and somehow introduced a bug into rust-analyzer as well.

And also very scary :)
