### ISSUE TITLE
cannot find `yaml.h` even after setting the `PKG_CONFIG_PATH`

### ISSUE THREAD

**Issue by ezntek** [rust-lang/rust-analyzer#15023]
I'm writing a project that depends on `serde_yaml`, and everything works on my linux machine, but then on my mac i get this error when i first launch VSCode (i tried on vscodium, vscode and the insiders version):

```
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: failed to run custom build command for `yaml v0.3.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/easontek/Sources/askme-rs/target/debug/build/yaml-263983e0e3dc9eaf/build-script-build` (exit status: 101)
  --- stderr
  Command `"gcc" "src/codegen/type_size.c" "-o" "/Users/easontek/Sources/askme-rs/target/debug/build/yaml-dcbc2a1ecc69e477/out/codegen"` failedthread 'main' panicked at 'src/codegen/type_size.c:1:10: fatal error: yaml.h: No such file or directory
      1 | #include <yaml.h>
        |          ^~~~~~~~
  compilation terminated.
  ', /Users/easontek/.cargo/registry/src/github.com-1ecc6299db9ec823/yaml-0.3.0/build.rs:14:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
     1: core::panicking::panic_fmt
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
     2: core::panicking::panic_display
     3: build_script_build::run_cmd
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

can someone help, please? i also did install `libyaml` through brew.

**Comment by flodiebold** [comment]
Does running `cargo check` in the terminal work?

**Comment by ezntek** [comment]
nope, it also complains about the missing header.

**Comment by lnicola** [comment]
Are you using `serde_yaml` or `yaml`? The former has its own Rust translation of `libyaml`, and seems to need no C compiler. But your error is in `/Users/easontek/.cargo/registry/src/github.com-1ecc6299db9ec823/yaml-0.3.0/build.rs:14:13`, which is a crate last published 5 years ago.

**Comment by ezntek** [comment]
i am using serde_yaml, as specified in my Cargo.toml, but it seems to have an `unsafe_libyaml` dependency.

**Comment by lnicola** [comment]
Try `cargo tree`. There is a `yaml` crate in your dependency tree.

**Comment by ezntek** [comment]
oh well, turns out there is. probably my teammate because i dont remember adding it at all
