### ISSUE TITLE
Computing `original_range` in `add_missing_match_arms` for nested macros panics due to `Bad range: ...`

### ISSUE THREAD

**Issue by oeb25** [rust-lang/rust-analyzer#15103]
**rust-analyzer version**: `rust-analyzer version: 0.3.1557-standalone (cd3bf9fe5 2023-06-18)`, and `rust-analyzer version: 0.0.0 (6d333e587 2023-06-21)` built from master

**rustc version**: `rustc 1.70.0 (90c541806 2023-05-31)`

**relevant settings**: NA

---

## Reproduction

rust-analyzer panics when hovering `match()` in the current example in an otherwise empty crate:

```rs
fn add_missing_match_arms_panics() {format_args!("{:?}",match(){()=>panic!()});}
```

The following examples do not seem to panic reliably:

```rs
fn formatted_doesnt() {
    format_args!(
        "{:?}",
        match () {
            () => panic!(),
        }
    );
}
```

```rs
fn no_panic_doesnt() {format_args!("{:?}",match(){()=>line!()});}
```

The actual example where this occurred is [here](https://github.com/oeb25/mist/blob/8c8d668889fcc95c14431888bf24374c25932373/crates/lsp/src/hover.rs#L72-L79), which I managed to reduce to the above.

## Stacktrace

```
thread 'Worker' panicked at 'Bad range: node range 86..118, range 169..170', /Users/oeb25/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.11/src/cursor.rs:786:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/114fb86ca08cfa6a99087e0f0bc264d03590dc37/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/114fb86ca08cfa6a99087e0f0bc264d03590dc37/library/core/src/panicking.rs:67:14
   2: rowan::cursor::SyntaxNode::covering_element
   3: rowan::api::SyntaxNode<L>::covering_element
   4: hir_expand::ExpansionInfo::map_token_up
   5: hir_expand::ascend_call_token
   6: hir_expand::ascend_node_border_tokens
   7: hir_expand::InFile<&rowan::api::SyntaxNode<syntax::syntax_node::RustLanguage>>::original_file_range_opt
   8: hir_expand::InFile<&rowan::api::SyntaxNode<syntax::syntax_node::RustLanguage>>::original_file_range
   9: hir::semantics::SemanticsImpl::original_range
  10: hir::semantics::Semantics<DB>::original_range
  11: ide_assists::handlers::add_missing_match_arms::add_missing_match_arms
  12: ide_assists::assists::{{closure}}
  13: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
  14: ide_assists::assists
  15: ide::Analysis::assists_with_fixes::{{closure}}
  16: ide::Analysis::with_db::{{closure}}
  17: std::panicking::try::do_call
  18: ___rust_try
  19: std::panicking::try
  20: std::panic::catch_unwind
  21: salsa::Cancelled::catch
  22: ide::Analysis::with_db
  23: ide::Analysis::assists_with_fixes
  24: rust_analyzer::handlers::request::handle_code_action
  25: rust_analyzer::dispatch::RequestDispatcher::on_with_thread_intent::{{closure}}::{{closure}}
  26: std::panicking::try::do_call
  27: ___rust_try
  28: std::panicking::try
  29: std::panic::catch_unwind
  30: rust_analyzer::dispatch::RequestDispatcher::on_with_thread_intent::{{closure}}
  31: rust_analyzer::task_pool::TaskPool<T>::spawn::{{closure}}
  32: stdx::thread::pool::Pool::spawn::{{closure}}
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}
  34: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
  35: stdx::thread::pool::Pool::new::{{closure}}
  36: stdx::thread::Builder::spawn::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Thoughts

- It seems to be white-space sensitive due to the above non-panicking examples.
- It is sufficient for the outer macro can be any format-related macro, but trivial macros (perhaps all mbe?) do not cause a crash:
  ```rs
  macro_rules! m {
      ($($t:tt)*) => { ($($t)*) };
  }
  fn all_ok() {m!("{:?}",match(){()=>print!("")});}
  ```
- It also seems to matter that the inner macro is of some specific kind:
  - `todo`, `panic`, and `print` cause the crash,
  - but `line` or something trivial like `macro_rules! m { () => { () }; }` does not.
- I've tried adding a test to both `add_missing_match_arms` and `hover`, but I've failed to reproduce in that environment:
  - `add_missing_match_arms` said the action wasn't applicable.
  - `hover` unwraps `None` [here](https://github.com/rust-lang/rust-analyzer/blob/6d333e587d0563355d865babec9de44365f55fb5/crates/ide/src/hover/tests.rs#L42), which is perhaps related but I can't tell.

**Comment by vgrossmann** [comment]
I simply have
```
fn main() {
    println!("{:?}", vec![1,2,3]);
}
```
When I type a dot after the vector, I get the same panic (in rowan-0.15.11/src/cursor.rs:786:13).

Also, maybe related: hovering over vec! doesn't do anything. When vec! is outside println!, it works.

I tried with both rust-analyzer v0.3.1557 and v0.4.1561 in VS Code.

**Comment by viktorlott** [comment]
Hey, could someone please fix this issue -- because my browser keeps crashing.
![issue](https://github.com/rust-lang/rust-analyzer/assets/22944008/a5b17afe-9811-4be8-994f-5c9734bef396)

**Comment by gtsiam** [comment]
I'm running into this a lot with a miette project. rust-analyzer keeps crashing to the point of being almost unusable.

@Veykril After some bisecting, I found the offending commit to be a02b9b279.

I gave fixing the bug a shot, but I can't for the life of me work out how the macro expansion code is supposed to work.

**Comment by Veykril** [comment]
Ye sorry, I'll try looking into fixing this next week (or at least prevent the crash)

**Comment by Veykril** [comment]
This should be fixed in tomorrows nightly release, https://github.com/rust-analyzer/rust-analyzer/commit/215b149
