### ISSUE TITLE
Chalk panics when `discriminant_value` intrinsic is called with inference variable

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust-analyzer#15113]
This panics:
```Rust
use core::intrinsics::discriminant_value;
use core::marker::DiscriminantKind;
const GOAL: bool = {
    discriminant_value(&Some(2)) == discriminant_value(&Some(5))
        && discriminant_value(&Some(2)) != discriminant_value(&None)
};
```
But this is fine:
```Rust
use core::intrinsics::discriminant_value;
use core::marker::DiscriminantKind;
const GOAL: bool = {
    discriminant_value(&Some(2i32)) == discriminant_value(&Some(5i32))
        && discriminant_value(&Some(2i32)) != discriminant_value(&None::<i32>)
};
```
The panic log is:
```
thread 'Worker' panicked at 'assertion failed: `(left == right)`
  left: `^1`,
 right: `^0`', /home/hamid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chalk-ir-0.91.0/src/lib.rs:2820:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: <chalk_ir::SubstFolder<I,A> as chalk_ir::fold::TypeFolder<I>>::fold_free_var_ty
   5: chalk_ir::fold::TypeSuperFoldable::super_fold_with
   6: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::GenericArg<I>>::try_fold_with
   7: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   8: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::Substitution<I>>::try_fold_with
   9: chalk_ir::fold::TypeSuperFoldable::super_fold_with
  10: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::GenericArg<I>>::try_fold_with
  11: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  12: chalk_ir::fold::boring_impls::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::Substitution<I>>::try_fold_with
  13: chalk_ir::_::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::DomainGoal<I>>::try_fold_with
  14: chalk_ir::_::<impl chalk_ir::fold::TypeFoldable<I> for chalk_ir::ProgramClauseImplication<I>>::try_fold_with
  15: chalk_solve::infer::instantiate::<impl chalk_solve::infer::InferenceTable<I>>::instantiate_binders_existentially
  16: chalk_recursive::fulfill::Fulfill<I,Solver>::new_with_clause
  17: chalk_recursive::solve::SolveIteration::solve_iteration
  18: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  19: chalk_recursive::fulfill::Fulfill<I,Solver>::prove
  20: chalk_recursive::fulfill::Fulfill<I,Solver>::solve
  21: chalk_recursive::solve::SolveIteration::solve_iteration
  22: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  23: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  24: hir_ty::traits::trait_solve_query
  25: salsa::runtime::Runtime::execute_query_implementation
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::read
  28: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  29: salsa::QueryTable<Q>::get
  30: <DB as hir_ty::db::HirDatabase>::trait_solve_query::__shim
  31: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  32: hir_ty::db::trait_solve_wait
  33: <DB as hir_ty::db::HirDatabase>::trait_solve
  34: hir_ty::infer::unify::InferenceTable::register_obligation_in_env
  35: hir_ty::infer::unify::InferenceTable::normalize_projection_ty
  36: <hir_ty::fold_tys_and_consts::TyFolder<F> as chalk_ir::fold::TypeFolder<hir_ty::interner::Interner>>::fold_ty
  37: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  38: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  39: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_overloadable_binop
  40: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  41: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  42: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  43: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  44: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::with_breakable_ctx
  45: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  46: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  47: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  48: hir_ty::infer::infer_query
  49: salsa::runtime::Runtime::execute_query_implementation
  50: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  51: salsa::derived::slot::Slot<Q,MP>::read
  52: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  53: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  54: <DB as hir_ty::db::HirDatabase>::infer_query
  55: hir_ty::db::infer_wait
  56: <DB as hir_ty::db::HirDatabase>::infer
  57: hir::source_analyzer::SourceAnalyzer::new_for_body
  58: hir::semantics::SemanticsImpl::analyze_impl
  59: hir::semantics::SemanticsImpl::type_of_expr
  60: ide::inlay_hints::param_name::hints
  61: ide::inlay_hints::hints
  62: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  63: ide::inlay_hints::inlay_hints
  64: std::panicking::try
  65: ide::Analysis::inlay_hints
  66: rust_analyzer::handlers::request::handle_inlay_hints
  67: std::panicking::try
  68: core::ops::function::FnOnce::call_once{{vtable.shim}}
```

**Comment by ChayimFriedman2** [comment]
Doesn't panic anymore.
