### ISSUE TITLE
Frequent Crashing

### ISSUE THREAD

**Issue by manglemix** [rust-lang/rust-analyzer#15123]
**rust-analyzer version**: 0.3.1557-standalone (cd3bf9fe5 2023-06-18)

**rustc version**: 1.69.0-nightly (34e6673a0 2023-02-25)

**relevant settings**: Nothing out of the ordinary

Rust Analyzer is currently unusable by me. Crashes too frequently, and when it is not it does not provide as much insight and actions as it used to.

Small project I am working on now where I first noticed this: https://github.com/manglemix/funder

Here are some of the crash logs:
```
Panic context:
> 
version: 0.3.1557-standalone (cd3bf9fe5 2023-06-18)
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/GitRepos/funder/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 35,
            character: 24,
        },
        end: Position {
            line: 35,
            character: 42,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
        trigger_kind: Some(
            Automatic,
        ),
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at 'called `Result::unwrap()` on an `Err` value: SyntheticSyntax', crates\hir\src\lib.rs:2823:61
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
   3: hir::Local::primary_source
   4: ide_diagnostics::handlers::mutability_errors::unused_mut
   5: ide_diagnostics::diagnostics
   6: std::panicking::try
   7: rust_analyzer::handlers::request::handle_code_action
   8: std::panicking::try
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> publish_diagnostics

Panic context:
thread '> Workerpublish_diagnostics' panicked at '

called `Result::unwrap()` on an `Err` value: SyntheticSyntaxthread '', crates\hir\src\lib.rs:Worker' panicked at 'called `Result::unwrap()` on an `Err` value: SyntheticSyntax2823:', 61crates\hir\src\lib.rs
:2823:stack backtrace:
61
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
   3: hir::Local::primary_source
   4: ide_diagnostics::handlers::mutability_errors::unused_mut
   5: ide_diagnostics::diagnostics
   6: std::panicking::try
   7: ide::Analysis::diagnostics
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   9: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
   3: hir::Local::primary_source
   4: ide_diagnostics::handlers::mutability_errors::unused_mut
   5: ide_diagnostics::diagnostics
   6: std::panicking::try
   7: ide::Analysis::diagnostics
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   9: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> publish_diagnostics

thread 'Worker' panicked at 'called `Result::unwrap()` on an `Err` value: SyntheticSyntax', crates\hir\src\lib.rs:2823:61
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
   3: hir::Local::primary_source
   4: ide_diagnostics::handlers::mutability_errors::unused_mut
   5: ide_diagnostics::diagnostics
   6: std::panicking::try
   7: ide::Analysis::diagnostics
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   9: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'LspServer' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', D:\a\rust-analyzer\rust-analyzer\crates\stdx\src\thread\pool.rs:86:35
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
   3: stdx::thread::pool::Pool::spawn
   4: rust_analyzer::dispatch::RequestDispatcher::on
   5: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   6: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   7: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   8: rust_analyzer::main_loop::main_loop
   9: rust_analyzer::run_server
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', lib\lsp-server\src\stdio.rs:26:37
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\jod-thread-0.1.2\src\lib.rs:33:22
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\result.rs:1687
   3: jod_thread::JoinHandle<T>::join
   4: lsp_types::moniker::_::<impl serde::ser::Serialize for lsp_types::moniker::MonikerServerCapabilities>::serialize
   5: lsp_types::moniker::_::<impl serde::ser::Serialize for lsp_types::moniker::MonikerServerCapabilities>::serialize
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 4:15:37 PM] The Rust Analyzer Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by Veykril** [comment]
This should be fixed on current nightly/next week's monday stable release

**Comment by manglemix** [comment]
Good to know. Reverting to rust-analyzer version: 0.3.1524-standalone (7ac161ce7 2023-05-21) works for now
