### ISSUE TITLE
Random crash while writing in vscode.

### ISSUE THREAD

**Issue by PunchCakee** [rust-lang/rust-analyzer#15225]
rustc 1.70.0 (90c541806 2023-05-31)

rust-analyzer version: 0.3.1575-standalone (ff485b63b 2023-07-02)

Operating system:
```
Edition	Windows 10 Pro
Version	22H2
Installed on	‎7/‎6/‎2023
OS build	19045.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0
```

System info:
```
Device name	DESKTOP-SCHT1LN
Processor	Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
Installed RAM	32.0 GB (31.8 GB usable)
Device ID	956E29D9-BA24-455D-820F-E3BD165E88A4
Product ID	00330-80000-00000-AA046
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

```
log:
```
Panic context:
> 
version: 0.3.1575-standalone (ff485b63b 2023-07-02)
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/c%3A/Users/faisal/Desktop/something/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 8,
            character: 9,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-solve-0.92.0\src\clauses\builtin_traits\fn_family.rs:90:55
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:117
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_solve::clauses::program_clauses_that_could_match
   7: chalk_recursive::solve::SolveIteration::solve_iteration
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_method_candidates_dyn
  20: hir_ty::method_resolution::iterate_method_candidates_dyn
  21: hir_ty::method_resolution::iterate_method_candidates_dyn
  22: hir::Type::iterate_method_candidates_dyn
  23: hir::Type::iterate_method_candidates_with_traits
  24: ide_completion::completions::dot::complete_undotted_self
  25: ide_completion::completions::complete_name_ref
  26: ide_completion::completions
  27: std::panicking::try
  28: rust_analyzer::handlers::request::handle_completion
  29: std::panicking::try
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:43:38 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: 0.3.1575-standalone (ff485b63b 2023-07-02)
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/c%3A/Users/faisal/Desktop/something/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 8,
            character: 10,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-solve-0.92.0\src\clauses\builtin_traits\fn_family.rs:90:55
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:117
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_solve::clauses::program_clauses_that_could_match
   7: chalk_recursive::solve::SolveIteration::solve_iteration
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_method_candidates_dyn
  20: hir_ty::method_resolution::iterate_method_candidates_dyn
  21: hir_ty::method_resolution::iterate_method_candidates_dyn
  22: hir::Type::iterate_method_candidates_dyn
  23: hir::Type::iterate_method_candidates_with_traits
  24: ide_completion::completions::dot::complete_undotted_self
  25: ide_completion::completions::complete_name_ref
  26: ide_completion::completions
  27: std::panicking::try
  28: rust_analyzer::handlers::request::handle_completion
  29: std::panicking::try
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:43:38 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: 0.3.1575-standalone (ff485b63b 2023-07-02)
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/c%3A/Users/faisal/Desktop/something/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 8,
            character: 11,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-solve-0.92.0\src\clauses\builtin_traits\fn_family.rs:90:55
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:117
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_solve::clauses::program_clauses_that_could_match
   7: chalk_recursive::solve::SolveIteration::solve_iteration
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_method_candidates_dyn
  20: hir_ty::method_resolution::iterate_method_candidates_dyn
  21: hir_ty::method_resolution::iterate_method_candidates_dyn
  22: hir::Type::iterate_method_candidates_dyn
  23: hir::Type::iterate_method_candidates_with_traits
  24: ide_completion::completions::dot::complete_undotted_self
  25: ide_completion::completions::complete_name_ref
  26: ide_completion::completions
  27: std::panicking::try
  28: rust_analyzer::handlers::request::handle_completion
  29: std::panicking::try
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:43:38 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: 0.3.1575-standalone (ff485b63b 2023-07-02)
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/c%3A/Users/faisal/Desktop/something/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 8,
            character: 14,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-solve-0.92.0\src\clauses\builtin_traits\fn_family.rs:90:55
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:117
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_solve::clauses::program_clauses_that_could_match
   7: chalk_recursive::solve::SolveIteration::solve_iteration
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_method_candidates_dyn
  20: hir_ty::method_resolution::iterate_method_candidates_dyn
  21: hir_ty::method_resolution::iterate_method_candidates_dyn
  22: hir::Type::iterate_method_candidates_dyn
  23: hir::Type::iterate_method_candidates_with_traits
  24: ide_completion::completions::dot::complete_undotted_self
  25: ide_completion::completions::complete_name_ref
  26: ide_completion::completions
  27: std::panicking::try
  28: rust_analyzer::handlers::request::handle_completion
  29: std::panicking::try
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:43:39 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: 0.3.1575-standalone (ff485b63b 2023-07-02)
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/c%3A/Users/faisal/Desktop/something/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 8,
            character: 9,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-solve-0.92.0\src\clauses\builtin_traits\fn_family.rs:90:55
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:117
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_solve::clauses::program_clauses_that_could_match
   7: chalk_recursive::solve::SolveIteration::solve_iteration
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_method_candidates_dyn
  20: hir_ty::method_resolution::iterate_method_candidates_dyn
  21: hir_ty::method_resolution::iterate_method_candidates_dyn
  22: hir::Type::iterate_method_candidates_dyn
  23: hir::Type::iterate_method_candidates_with_traits
  24: ide_completion::completions::dot::complete_undotted_self
  25: ide_completion::completions::complete_name_ref
  26: ide_completion::completions
  27: std::panicking::try
  28: rust_analyzer::handlers::request::handle_completion
  29: std::panicking::try
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:43:40 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: 0.3.1575-standalone (ff485b63b 2023-07-02)
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/c%3A/Users/faisal/Desktop/something/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 8,
            character: 10,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-solve-0.92.0\src\clauses\builtin_traits\fn_family.rs:90:55
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:117
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_solve::clauses::program_clauses_that_could_match
   7: chalk_recursive::solve::SolveIteration::solve_iteration
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_method_candidates_dyn
  20: hir_ty::method_resolution::iterate_method_candidates_dyn
  21: hir_ty::method_resolution::iterate_method_candidates_dyn
  22: hir::Type::iterate_method_candidates_dyn
  23: hir::Type::iterate_method_candidates_with_traits
  24: ide_completion::completions::dot::complete_undotted_self
  25: ide_completion::completions::complete_name_ref
  26: ide_completion::completions
  27: std::panicking::try
  28: rust_analyzer::handlers::request::handle_completion
  29: std::panicking::try
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:43:40 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: 0.3.1575-standalone (ff485b63b 2023-07-02)
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/c%3A/Users/faisal/Desktop/something/src/main.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 8,
            character: 8,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-solve-0.92.0\src\clauses\builtin_traits\fn_family.rs:90:55
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\core\src\panicking.rs:117
   3: chalk_solve::clauses::builtin_traits::fn_family::add_fn_trait_program_clauses
   4: chalk_solve::clauses::builder::ClauseBuilder<I>::push_binders
   5: chalk_solve::clauses::builtin_traits::add_builtin_program_clauses
   6: chalk_solve::clauses::program_clauses_that_could_match
   7: chalk_recursive::solve::SolveIteration::solve_iteration
   8: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
   9: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  10: hir_ty::traits::trait_solve_query
  11: salsa::runtime::Runtime::execute_query_implementation
  12: core::ptr::drop_in_place<salsa::derived::slot::QueryState<hir_ty::db::ConstEvalDiscriminantQuery>>
  13: salsa::derived::slot::Slot<Q,MP>::read
  14: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  15: salsa::QueryTable<Q>::get
  16: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  17: hir_ty::db::trait_solve_wait
  18: <DB as hir_ty::db::HirDatabase>::trait_solve
  19: hir_ty::method_resolution::iterate_method_candidates_dyn
  20: hir_ty::method_resolution::iterate_method_candidates_dyn
  21: hir_ty::method_resolution::iterate_method_candidates_dyn
  22: hir::Type::iterate_method_candidates_dyn
  23: hir::Type::iterate_method_candidates_with_traits
  24: ide_completion::completions::dot::complete_undotted_self
  25: ide_completion::completions::complete_name_ref
  26: ide_completion::completions
  27: std::panicking::try
  28: rust_analyzer::handlers::request::handle_completion
  29: std::panicking::try
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:43:49 PM] Request textDocument/completion failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 

```

**Comment by lnicola** [comment]
This appears to be the same as #13531. Please post there if you find a reliable way to reproduce it.
