### ISSUE TITLE
rust-analyzer crashed

### ISSUE THREAD

**Issue by yuchunzhou** [rust-lang/rust-analyzer#15525]
rustc version: rustc 1.72.0 (5680fa18f 2023-08-23)  
rust-analyzer version: rust-analyzer 1.72.0 (5680fa1 2023-08-23)  
error log:  
```
Panic context:
> publish_diagnostics

thread 'Worker' panicked at 'called `Result::unwrap()` on an `Err` value: SyntheticSyntax', crates/hir/src/lib.rs:2823:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: <hir::Local>::primary_source
   4: ide_diagnostics::handlers::mutability_errors::unused_mut
   5: ide_diagnostics::diagnostics
   6: <salsa::Cancelled>::catch::<<ide::Analysis>::with_db<<ide::Analysis>::diagnostics::{closure#0}, alloc::vec::Vec<ide_diagnostics::Diagnostic>>::{closure#0}, alloc::vec::Vec<ide_diagnostics::Diagnostic>>
   7: <ide::Analysis>::diagnostics
   8: <&mut <rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}::{closure#0} as core::ops::function::FnMut<(vfs::FileId,)>>::call_mut
   9: <alloc::vec::Vec<(vfs::FileId, alloc::vec::Vec<lsp_types::Diagnostic>)> as alloc::vec::spec_from_iter::SpecFromIter<(vfs::FileId, alloc::vec::Vec<lsp_types::Diagnostic>), core::iter::adapters::map::Map<core::iter::adapters::filter_map::FilterMap<alloc::vec::into_iter::IntoIter<vfs::FileId>, <rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}::{closure#0}>, <rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}::{closure#1}>>>::from_iter
  10: <<stdx::thread::pool::Pool>::spawn<<rust_analyzer::task_pool::TaskPool<rust_analyzer::main_loop::Task>>::spawn<<rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}>::{closure#0}>::{closure#0} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> publish_diagnostics

thread 'Worker' panicked at 'called `Result::unwrap()` on an `Err` value: SyntheticSyntax', crates/hir/src/lib.rs:2823:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: <hir::Local>::primary_source
   4: ide_diagnostics::handlers::mutability_errors::unused_mut
   5: ide_diagnostics::diagnostics
   6: <salsa::Cancelled>::catch::<<ide::Analysis>::with_db<<ide::Analysis>::diagnostics::{closure#0}, alloc::vec::Vec<ide_diagnostics::Diagnostic>>::{closure#0}, alloc::vec::Vec<ide_diagnostics::Diagnostic>>
   7: <ide::Analysis>::diagnostics
   8: <&mut <rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}::{closure#0} as core::ops::function::FnMut<(vfs::FileId,)>>::call_mut
   9: <alloc::vec::Vec<(vfs::FileId, alloc::vec::Vec<lsp_types::Diagnostic>)> as alloc::vec::spec_from_iter::SpecFromIter<(vfs::FileId, alloc::vec::Vec<lsp_types::Diagnostic>), core::iter::adapters::map::Map<core::iter::adapters::filter_map::FilterMap<alloc::vec::into_iter::IntoIter<vfs::FileId>, <rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}::{closure#0}>, <rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}::{closure#1}>>>::from_iter
  10: <<stdx::thread::pool::Pool>::spawn<<rust_analyzer::task_pool::TaskPool<rust_analyzer::main_loop::Task>>::spawn<<rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}>::{closure#0}>::{closure#0} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'LspServer' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/src/tools/rust-analyzer/crates/stdx/src/thread/pool.rs:86:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: <stdx::thread::pool::Pool>::spawn::<<rust_analyzer::task_pool::TaskPool<rust_analyzer::main_loop::Task>>::spawn<<rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}>::{closure#0}>
   4: <rust_analyzer::global_state::GlobalState>::handle_event
   5: <rust_analyzer::global_state::GlobalState>::run
   6: rust_analyzer::main_loop::main_loop
   7: rust_analyzer::run_server
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', lib/lsp-server/src/stdio.rs:26:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /cargo/registry/src/index.crates.io-6f17d22bba15001f/jod-thread-0.1.2/src/lib.rs:33:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: <jod_thread::JoinHandle<core::result::Result<(), alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>>>>::join
   4: <stdx::thread::JoinHandle<core::result::Result<(), alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>>>>::join
   5: rust_analyzer::with_extra_thread::<&str, rust_analyzer::run_server>
   6: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process rust-analyzer stderr finished
```

**Comment by lnicola** [comment]
Can you try running a GitHub binary instead? This is #15123.

**Comment by lnicola** [comment]
Closing as a duplicate.
