### ISSUE TITLE
Recursive typestate pattern leads to panic

### ISSUE THREAD

**Issue by Psy-Kai** [rust-lang/rust-analyzer#15671]
**rust-analyzer version**: 0.3.1673-standalone

**rustc version**: 1.72.1 (d5c2e9c34 2023-09-13)

**relevant settings**: just clean project in vscode devcontainer

Hello,

the following code just leads to a panic

```rust
#[derive(Debug, PartialEq)]
struct A;
type B = Vec<C<A>>;

#[derive(Debug)]
struct C<T = B> {
    t: T,
}
```

This is completely valid rust. The compiler does not have any problem with this.

<details>
<summary>rust-analyzer output</summary>

```
Panic context:
> 
version: 0.3.1673-standalone
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/workspaces/rustanalyzer_recursive_type_bug/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 10,
            character: 23,
        },
        end: Position {
            line: 10,
            character: 23,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
        trigger_kind: Some(
            Automatic,
        ),
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/salsa-0.17.0-pre.2/src/runtime.rs:306:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
   3: salsa::runtime::Runtime::report_unexpected_cycle
   4: salsa::derived::slot::Slot<Q,MP>::read
   5: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   6: salsa::QueryTable<Q>::get
   7: <DB as hir_ty::db::HirDatabase>::generic_defaults
   8: hir_ty::lower::TyLoweringContext::substs_from_args_and_bindings
   9: hir_ty::lower::TyLoweringContext::lower_path_inner
  10: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  11: hir_ty::lower::TyLoweringContext::lower_ty_ext
  12: hir_ty::lower::TyLoweringContext::substs_from_args_and_bindings
  13: hir_ty::lower::TyLoweringContext::lower_path_inner
  14: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  15: hir_ty::lower::TyLoweringContext::lower_ty_ext
  16: hir_ty::lower::ty_query
  17: salsa::runtime::Runtime::execute_query_implementation
  18: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  19: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  20: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  21: salsa::derived::slot::MemoRevisions::validate_memoized_value
  22: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  25: salsa::derived::slot::MemoRevisions::validate_memoized_value
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  28: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  29: salsa::derived::slot::MemoRevisions::validate_memoized_value
  30: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  31: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  32: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  33: salsa::derived::slot::MemoRevisions::validate_memoized_value
  34: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  35: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  36: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  37: salsa::derived::slot::MemoRevisions::validate_memoized_value
  38: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  39: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  40: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  41: salsa::derived::slot::MemoRevisions::validate_memoized_value
  42: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  43: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  44: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  45: salsa::derived::slot::MemoRevisions::validate_memoized_value
  46: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  47: salsa::derived::slot::Slot<Q,MP>::read
  48: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  49: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  50: <DB as hir_ty::db::HirDatabase>::infer_query
  51: hir_ty::db::infer_wait
  52: <DB as hir_ty::db::HirDatabase>::infer
  53: hir::DefWithBody::diagnostics
  54: hir::ModuleDef::diagnostics
  55: hir::Module::diagnostics
  56: ide_diagnostics::diagnostics
  57: std::panicking::try
  58: ide::Analysis::assists_with_fixes
  59: rust_analyzer::handlers::request::handle_code_action
  60: std::panicking::try
  61: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> fetch_native_diagnostics

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/salsa-0.17.0-pre.2/src/runtime.rs:306:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
   3: salsa::runtime::Runtime::report_unexpected_cycle
   4: salsa::derived::slot::Slot<Q,MP>::read
   5: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   6: salsa::QueryTable<Q>::get
   7: <DB as hir_ty::db::HirDatabase>::generic_defaults
   8: hir_ty::lower::TyLoweringContext::substs_from_args_and_bindings
   9: hir_ty::lower::TyLoweringContext::lower_path_inner
  10: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  11: hir_ty::lower::TyLoweringContext::lower_ty_ext
  12: hir_ty::lower::TyLoweringContext::substs_from_args_and_bindings
  13: hir_ty::lower::TyLoweringContext::lower_path_inner
  14: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  15: hir_ty::lower::TyLoweringContext::lower_ty_ext
  16: hir_ty::lower::ty_query
  17: salsa::runtime::Runtime::execute_query_implementation
  18: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  19: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  20: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  21: salsa::derived::slot::MemoRevisions::validate_memoized_value
  22: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  25: salsa::derived::slot::MemoRevisions::validate_memoized_value
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  28: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  29: salsa::derived::slot::MemoRevisions::validate_memoized_value
  30: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  31: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  32: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  33: salsa::derived::slot::MemoRevisions::validate_memoized_value
  34: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  35: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  36: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  37: salsa::derived::slot::MemoRevisions::validate_memoized_value
  38: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  39: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  40: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  41: salsa::derived::slot::MemoRevisions::validate_memoized_value
  42: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  43: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  44: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  45: salsa::derived::slot::MemoRevisions::validate_memoized_value
  46: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  47: salsa::derived::slot::Slot<Q,MP>::read
  48: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  49: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  50: <DB as hir_ty::db::HirDatabase>::infer_query
  51: hir_ty::db::infer_wait
  52: <DB as hir_ty::db::HirDatabase>::infer
  53: hir::DefWithBody::diagnostics
  54: hir::ModuleDef::diagnostics
  55: hir::Module::diagnostics
  56: ide_diagnostics::diagnostics
  57: salsa::Cancelled::catch
  58: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  59: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  60: rust_analyzer::diagnostics::fetch_native_diagnostics
  61: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.3.1673-standalone
request: codeLens/resolve CodeLens {
    range: Range {
        start: Position {
            line: 9,
            character: 7,
        },
        end: Position {
            line: 9,
            character: 8,
        },
    },
    command: None,
    data: Some(
        Object {
            "version": Number(129),
            "kind": Object {
                "impls": Object {
                    "textDocument": Object {
                        "uri": String("file:///workspaces/rustanalyzer_recursive_type_bug/src/main.rs"),
                    },
                    "position": Object {
                        "line": Number(9),
                        "character": Number(7),
                    },
                },
            },
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/salsa-0.17.0-pre.2/src/runtime.rs:306:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
   3: salsa::runtime::Runtime::report_unexpected_cycle
   4: salsa::derived::slot::Slot<Q,MP>::read
   5: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   6: salsa::QueryTable<Q>::get
   7: <DB as hir_ty::db::HirDatabase>::generic_defaults
   8: hir_ty::lower::TyLoweringContext::substs_from_args_and_bindings
   9: hir_ty::lower::TyLoweringContext::lower_path_inner
  10: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  11: hir_ty::lower::TyLoweringContext::lower_ty_ext
  12: hir_ty::lower::TyLoweringContext::substs_from_args_and_bindings
  13: hir_ty::lower::TyLoweringContext::lower_path_inner
  14: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  15: hir_ty::lower::TyLoweringContext::lower_ty_ext
  16: hir_ty::lower::ty_query
  17: salsa::runtime::Runtime::execute_query_implementation
  18: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  19: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  20: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  21: salsa::derived::slot::MemoRevisions::validate_memoized_value
  22: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  25: salsa::derived::slot::MemoRevisions::validate_memoized_value
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  28: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  29: salsa::derived::slot::MemoRevisions::validate_memoized_value
  30: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  31: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  32: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  33: salsa::derived::slot::MemoRevisions::validate_memoized_value
  34: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  35: salsa::derived::slot::Slot<Q,MP>::read
  36: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  37: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  38: hir::Impl::all_for_type
  39: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  40: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  41: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  42: ide::goto_implementation::goto_implementation
  43: ide::annotations::resolve_annotation
  44: std::panicking::try
  45: rust_analyzer::handlers::request::handle_code_lens_resolve
  46: std::panicking::try
  47: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 1:25:42 PM] Request codeLens/resolve failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: 0.3.1673-standalone
request: codeLens/resolve CodeLens {
    range: Range {
        start: Position {
            line: 5,
            character: 7,
        },
        end: Position {
            line: 5,
            character: 8,
        },
    },
    command: None,
    data: Some(
        Object {
            "version": Number(129),
            "kind": Object {
                "impls": Object {
                    "textDocument": Object {
                        "uri": String("file:///workspaces/rustanalyzer_recursive_type_bug/src/main.rs"),
                    },
                    "position": Object {
                        "line": Number(5),
                        "character": Number(7),
                    },
                },
            },
        },
    ),
}

thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/salsa-0.17.0-pre.2/src/runtime.rs:306:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
   3: salsa::runtime::Runtime::report_unexpected_cycle
   4: salsa::derived::slot::Slot<Q,MP>::read
   5: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   6: salsa::QueryTable<Q>::get
   7: <DB as hir_ty::db::HirDatabase>::generic_defaults
   8: hir_ty::lower::TyLoweringContext::substs_from_args_and_bindings
   9: hir_ty::lower::TyLoweringContext::lower_path_inner
  10: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  11: hir_ty::lower::TyLoweringContext::lower_ty_ext
  12: hir_ty::lower::TyLoweringContext::substs_from_args_and_bindings
  13: hir_ty::lower::TyLoweringContext::lower_path_inner
  14: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
  15: hir_ty::lower::TyLoweringContext::lower_ty_ext
  16: hir_ty::lower::ty_query
  17: salsa::runtime::Runtime::execute_query_implementation
  18: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  19: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  20: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  21: salsa::derived::slot::MemoRevisions::validate_memoized_value
  22: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  23: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  24: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  25: salsa::derived::slot::MemoRevisions::validate_memoized_value
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  28: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  29: salsa::derived::slot::MemoRevisions::validate_memoized_value
  30: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  31: salsa::derived::slot::Slot<Q,MP>::maybe_changed_since
  32: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::maybe_changed_since
  33: salsa::derived::slot::MemoRevisions::validate_memoized_value
  34: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  35: salsa::derived::slot::Slot<Q,MP>::read
  36: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  37: <DB as hir_ty::db::HirDatabase>::trait_impls_in_crate::__shim
  38: hir::Impl::all_for_type
  39: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  40: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  41: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  42: ide::goto_implementation::goto_implementation
  43: ide::annotations::resolve_annotation
  44: std::panicking::try
  45: rust_analyzer::handlers::request::handle_code_lens_resolve
  46: std::panicking::try
  47: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 1:25:42 PM] Request codeLens/resolve failed.
  Message: request handler panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 

```
</details>

**Comment by Veykril** [comment]
well that's a fun cyclic definition ...

**Comment by Veykril** [comment]
This no longer panics
