### ISSUE TITLE
Result::unwrap() on an Err value: SyntheticSyntax (Internal Error)

### ISSUE THREAD

**Issue by snyball** [rust-lang/rust-analyzer#15689]
### The crash

```
thread 'Worker' panicked at 'called `Result::unwrap()` on an `Err` value: SyntheticSyntax', crates/hir/src/lib.rs:2823:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1651:5
   3: <hir::Local>::primary_source
   4: ide_diagnostics::handlers::mutability_errors::unused_mut
   5: ide_diagnostics::diagnostics
   6: <salsa::Cancelled>::catch::<<ide::Analysis>::with_db<<ide::Analysis>::diagnostics::{closure#0}, alloc::vec::Vec<ide_diagnostics::Diagnostic>>::{closure#0}, alloc::vec::Vec<ide_diagnostics::Diagnostic>>
   7: <ide::Analysis>::diagnostics
   8: <&mut <rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}::{closure#0} as core::ops::function::FnMut<(vfs::FileId,)>>::call_mut
   9: <alloc::vec::Vec<(vfs::FileId, alloc::vec::Vec<lsp_types::Diagnostic>)> as alloc::vec::spec_from_iter::SpecFromIter<(vfs::FileId, alloc::vec::Vec<lsp_types::Diagnostic>), core::iter::adapters::map::Map<core::iter::adapters::filter_map::FilterMap<alloc::vec::into_iter::IntoIter<vfs::FileId>, <rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}::{closure#0}>, <rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}::{closure#1}>>>::from_iter
  10: <<stdx::thread::pool::Pool>::spawn<<rust_analyzer::task_pool::TaskPool<rust_analyzer::main_loop::Task>>::spawn<<rust_analyzer::global_state::GlobalState>::update_diagnostics::{closure#2}>::{closure#0}>::{closure#0} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Steps to reproduce

1. `cargo new ra-crash`
2. replace main.rs with
```rust
fn main() {
    return;
    for _ in &[1] {}
}
```
3. Open `main.rs` and add a new line at the start of `main` and enter any code

**rust-analyzer version**: 1.72.1 (d5c2e9c 2023-09-13)

**rustc version**: 1.72.1 (d5c2e9c34 2023-09-13)

**Comment by lnicola** [comment]
I think this is now fixed.
