### ISSUE TITLE
work node crashes

### ISSUE THREAD

**Issue by sehz** [rust-lang/rust-analyzer#15737]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)

rust-analyzer version: 0.3.1689-standalone (b1f89a84a 2023-10-06)

**rustc version**: (eg. output of `rustc -V`)

rustc 1.72.0 (5680fa18f 2023-08-23)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

```
thread '<unnamed>' panicked at 'unsupported character `'{'`', library/proc_macro/src/lib.rs:947:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: proc_macro::Punct::new
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/proc_macro/src/lib.rs:947:13
   3: proc_macro2::imp::into_compiler_token
   4: core::ops::function::FnMut::call_mut
   5: core::iter::adapters::map::map_fold::{{closure}}
   6: core::iter::traits::iterator::Iterator::fold
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   8: core::iter::traits::iterator::Iterator::for_each
   9: <proc_macro::TokenStream as core::iter::traits::collect::FromIterator<proc_macro::TokenTree>>::from_iter
  10: core::iter::traits::iterator::Iterator::collect
  11: <proc_macro2::imp::TokenStream as core::iter::traits::collect::FromIterator<proc_macro2::TokenTree>>::from_iter
  12: core::iter::traits::iterator::Iterator::collect
  13: <proc_macro2::TokenStream as core::iter::traits::collect::FromIterator<proc_macro2::TokenTree>>::from_iter
  14: core::iter::traits::iterator::Iterator::collect
  15: syn::buffer::Cursor::token_stream
  16: <proc_macro2::TokenStream as syn::parse::Parse>::parse::{{closure}}
  17: syn::parse::ParseBuffer::step
  18: <proc_macro2::TokenStream as syn::parse::Parse>::parse
  19: syn::parse::ParseBuffer::parse
  20: <tracing_attributes::MaybeItemFn as syn::parse::Parse>::parse
  21: core::ops::function::FnOnce::call_once
  22: <F as syn::parse::Parser>::parse2
  23: syn::parse::Parser::parse
  24: syn::parse
  25: tracing_attributes::instrument_speculative
  26: tracing_attributes::instrument::{{closure}}
  27: core::result::Result<T,E>::unwrap_or_else
  28: tracing_attributes::instrument
  29: core::ops::function::Fn::call
  30: proc_macro::bridge::client::Client<(proc_macro::TokenStream,proc_macro::TokenStream),proc_macro::TokenStream>::expand2::{{closure}}::{{closure}}
  31: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}::{{closure}}
  32: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}
  33: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
  34: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}
  35: std::thread::local::LocalKey<T>::try_with
  36: proc_macro::bridge::client::run_client::{{closure}}
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  38: std::panicking::try::do_call
  39: ___rust_try
  40: std::panicking::try
  41: proc_macro::bridge::client::run_client
  42: proc_macro::bridge::client::Client<(proc_macro::TokenStream,proc_macro::TokenStream),proc_macro::TokenStream>::expand2::{{closure}}
  43: proc_macro::bridge::selfless_reify::reify_to_extern_c_fn_hrt_bridge::wrapper
  44: proc_macro::bridge::server::run_server::<proc_macro_srv::server::RustAnalyzer, (proc_macro::bridge::Marked<proc_macro_srv::server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>, proc_macro::bridge::Marked<proc_macro_srv::server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>), core::option::Option<proc_macro::bridge::Marked<proc_macro_srv::server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>>, proc_macro::bridge::server::SameThread>
  45: <proc_macro_srv::proc_macros::ProcMacros>::expand
  46: <proc_macro_srv::dylib::Expander>::expand
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'unsupported character `'{'`', library/proc_macro/src/lib.rs:947:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: proc_macro::Punct::new
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/proc_macro/src/lib.rs:947:13
   3: proc_macro2::imp::into_compiler_token
   4: core::ops::function::FnMut::call_mut
   5: core::iter::adapters::map::map_fold::{{closure}}
   6: core::iter::traits::iterator::Iterator::fold
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   8: core::iter::traits::iterator::Iterator::for_each
   9: <proc_macro::TokenStream as core::iter::traits::collect::FromIterator<proc_macro::TokenTree>>::from_iter
  10: core::iter::traits::iterator::Iterator::collect
  11: <proc_macro2::imp::TokenStream as core::iter::traits::collect::FromIterator<proc_macro2::TokenTree>>::from_iter
  12: core::iter::traits::iterator::Iterator::collect
  13: <proc_macro2::TokenStream as core::iter::traits::collect::FromIterator<proc_macro2::TokenTree>>::from_iter
  14: core::iter::traits::iterator::Iterator::collect
  15: syn::buffer::Cursor::token_stream
  16: <proc_macro2::TokenStream as syn::parse::Parse>::parse::{{closure}}
  17: syn::parse::ParseBuffer::step
  18: <proc_macro2::TokenStream as syn::parse::Parse>::parse
  19: syn::parse::ParseBuffer::parse
  20: <tracing_attributes::MaybeItemFn as syn::parse::Parse>::parse
  21: core::ops::function::FnOnce::call_once
  22: <F as syn::parse::Parser>::parse2
  23: syn::parse::Parser::parse
  24: syn::parse
  25: tracing_attributes::instrument_speculative
  26: tracing_attributes::instrument::{{closure}}
  27: core::result::Result<T,E>::unwrap_or_else
  28: tracing_attributes::instrument
  29: core::ops::function::Fn::call
  30: proc_macro::bridge::client::Client<(proc_macro::TokenStream,proc_macro::TokenStream),proc_macro::TokenStream>::expand2::{{closure}}::{{closure}}
  31: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}::{{closure}}
  32: proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}
  33: proc_macro::bridge::scoped_cell::ScopedCell<T>::replace
  34: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}
  35: std::thread::local::LocalKey<T>::try_with
  36: proc_macro::bridge::client::run_client::{{closure}}
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  38: std::panicking::try::do_call
  39: ___rust_try
  40: std::panicking::try
  41: proc_macro::bridge::client::run_client
  42: proc_macro::bridge::client::Client<(proc_macro::TokenStream,proc_macro::TokenStream),proc_macro::TokenStream>::expand2::{{closure}}
  43: proc_macro::bridge::selfless_reify::reify_to_extern_c_fn_hrt_bridge::wrapper
  44: proc_macro::bridge::server::run_server::<proc_macro_srv::server::RustAnalyzer, (proc_macro::bridge::Marked<proc_macro_srv::server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>, proc_macro::bridge::Marked<proc_macro_srv::server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>), core::option::Option<proc_macro::bridge::Marked<proc_macro_srv::server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>>, proc_macro::bridge::server::SameThread>
  45: <proc_macro_srv::proc_macros::ProcMacros>::expand
  46: <proc_macro_srv::dylib::Expander>::expand
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.3.1689-standalone (b1f89a84a 2023-10-06)
request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/Users/sehyo/git/infinyon/fluvio-expirements/mv/ss-engine/src/io/mod",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 0,
            character: 21,
        },
    },
}

thread 'Worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.11/src/cursor.rs:786:13:
Bad range: node range 0..20, range 0..21
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rowan::cursor::SyntaxNode::covering_element
   3: ide::syntax_highlighting::highlight
   4: std::panicking::try
   5: rust_analyzer::handlers::request::handle_semantic_tokens_range
   6: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.3.1689-standalone (b1f89a84a 2023-10-06)
request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/Users/sehyo/git/infinyon/fluvio-expirements/mv/ss-engine/src/io/mod",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 0,
            character: 17,
        },
    },
}

thread 'Worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.11/src/cursor.rs:786:13:
Bad range: node range 0..16, range 0..17
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rowan::cursor::SyntaxNode::covering_element
   3: ide::syntax_highlighting::highlight
   4: std::panicking::try
   5: rust_analyzer::handlers::request::handle_semantic_tokens_range
   6: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Veykril** [comment]
This needs a reproducer, the stacktrace doesn't tell what went wrong.
