### ISSUE TITLE
thread Worker panicked

### ISSUE THREAD

**Issue by tomers** [rust-lang/rust-analyzer#15936]
I got this error while working in VSCode. I am sorry that I do not have any further info at this moment.

Version: `rust-analyzer version: 0.3.1730-standalone`
```
❯ rustc -V
rustc 1.73.0 (cc66ad468 2023-10-03)
```

```
thread 'Worker' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.11/src/cursor.rs:786:13:
Bad range: node range 0..19458, range 19467..19469
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: rowan::cursor::SyntaxNode::covering_element
   3: ide::inlay_hints::inlay_hints
   4: salsa::Cancelled::catch
   5: rust_analyzer::handlers::request::handle_inlay_hints_resolve
   6: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 18:50:25] Request inlayHint/resolve failed.
  Message: request handler panicked: Bad range: node range 0..19458, range 19467..19469
  Code: -32603 
```

**Comment by tomers** [comment]
I  cannot reproduce, as it happened in my VS code environment. I don't know how to reproduce, and how to toggle this environment variable to that extension. Closing the ticket.

**Comment by eflukx** [comment]
Same (similar?) issue here:

```
thread 'Worker' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.11/src/cursor.rs:786:13:
Bad range: node range 0..18091, range 656..26433
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: rowan::cursor::SyntaxNode::covering_element
   3: hir_expand::files::InFileWrapper<base_db::span::HirFileId,N>::original_ast_node
   4: hir::semantics::SemanticsImpl::original_ast_node
   5: ide_db::imports::insert_use::ImportScope::find_insert_use_container
   6: ide_completion::completions::snippet::add_custom_completions
   7: ide_completion::completions::snippet::complete_expr_snippet
   8: ide_completion::completions
   9: salsa::Cancelled::catch
  10: rust_analyzer::handlers::request::handle_completion
  11: std::panicking::try
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 5:56:08 PM] Request textDocument/completion failed.
  Message: request handler panicked: Bad range: node range 0..18091, range 656..26433
  Code: -32603 
```

**Comment by eflukx** [comment]
> ```
>  /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/line-index-0.1.0-pre.1/src/lib.rs:148:35:
> invalid offset
> stack backtrace:
>    0: _rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::option::expect_failed
>    3: rust_analyzer::lsp::to_proto::range
>    4: rust_analyzer::lsp::to_proto::location
>    5: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
>    6: rust_analyzer::lsp::to_proto::code_lens
>    7: rust_analyzer::handlers::request::handle_code_lens_resolve
>    8: std::panicking::try
>    9: core::ops::function::FnOnce::call_once{{vtable.shim}}
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [Error - 01:03:40] Request codeLens/resolve failed.
>   Message: request handler panicked: invalid offset
>   Code: -32603 
> ```

How is this related?

**Comment by jtmoon79** [comment]
Occurring here

```

thread 'Worker' panicked at crates/hir-ty/src/diagnostics/match_check.rs:147:50:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: hir_ty::diagnostics::match_check::PatCtxt::lower_pattern
   4: hir_ty::diagnostics::expr::ExprValidator::lower_pattern
   5: hir_ty::diagnostics::expr::BodyValidationDiagnostic::collect
   6: hir::DefWithBody::diagnostics
   7: hir::Module::diagnostics
   8: ide_diagnostics::diagnostics
   9: std::panicking::try
  10: ide::Analysis::assists_with_fixes
  11: rust_analyzer::handlers::request::handle_code_action
  12: std::panicking::try
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Using VS Code 1.87.0, rustc 1.67.0, rust-analyzer v0.3.1860, running on Windows 11 and using a project via WSL Ubuntu 22.04.  Up until now, the _rust-analyzer_ has been very stable.

Unfortunately it's probably related the specifics of the code I'm editing and I'd prefer not to upload all that.
