### ISSUE TITLE
Implement default members on trait with multiple default implementations, got panicked

### ISSUE THREAD

**Issue by kolulu23** [rust-lang/rust-analyzer#15999]
**rust-analyzer version**: `0.3.1748-standalone (237712fa3 2023-11-26)`

**rustc version**: `rustc 1.73.0 (cc66ad468 2023-10-03)`

**relevant settings**: Nothing special

# Reproduce

```rust
trait Demo<O1, O2 = O1> {
    fn process_1(&mut self) -> Result<O1, String> {
        Err("Problem part one is not solved".into())
    }
    fn process_2(&mut self) -> Result<O2, String> {
        Err("Problem part two is not solved".into())
    }
}

struct Mine {}

impl Demo<usize> for Mine {}
```
For these piece of code, VS Code Quick Fix action "Implement default memebers" will cause a panic: 
> thread 'Worker' panicked at crates\syntax\src\ted.rs:137:41: called `Option::unwrap()` on a `None` value

rust-analyser logs:
```rust
Panic context:
> 
version: 0.3.1748-standalone (237712fa3 2023-11-26)
request: codeAction/resolve CodeAction {
    title: "Implement default members",
    group: None,
    kind: Some(
        CodeActionKind(
            "quickfix",
        ),
    ),
    command: None,
    edit: None,
    is_preferred: None,
    data: Some(
        CodeActionData {
            code_action_params: CodeActionParams {
                text_document: TextDocumentIdentifier {
                    uri: Url {
                        scheme: "file",
                        cannot_be_a_base: false,
                        username: "",
                        password: None,
                        host: None,
                        port: None,
                        path: "/RustProjects/temp/src/main.rs",
                        query: None,
                        fragment: None,
                    },
                },
                range: Range {
                    start: Position {
                        line: 15,
                        character: 8,
                    },
                    end: Position {
                        line: 15,
                        character: 8,
                    },
                },
                context: CodeActionContext {
                    diagnostics: [],
                    only: None,
                    trigger_kind: Some(
                        Invoked,
                    ),
                },
                work_done_progress_params: WorkDoneProgressParams {
                    work_done_token: None,
                },
                partial_result_params: PartialResultParams {
                    partial_result_token: None,
                },
            },
            id: "add_impl_default_members:QuickFix:0",
        },
    ),
}

thread 'Worker' panicked at crates\syntax\src\ted.rs:137:41:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\std\src\panicking.rs:597
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\panicking.rs:72
   2: core::panicking::panic
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\panicking.rs:127
   3: syntax::ted::replace_all
   4: syntax::ted::replace
   5: ide_db::path_transform::Ctx::apply
   6: ide_db::path_transform::PathTransform::build_ctx
   7: ide_db::path_transform::PathTransform::apply
   8: ide_assists::utils::add_trait_assoc_items_to_impl
   9: ide_assists::assist_context::Assists::add::{{closure}}
  10: ide_assists::assist_context::Assists::add_impl
  11: ide_assists::assist_context::Assists::add
  12: ide_assists::handlers::add_missing_impl_members::add_missing_default_members
  13: ide_assists::handlers::add_missing_impl_members::add_missing_default_members
  14: ide_assists::assists
  15: std::panicking::try
  16: ide::Analysis::assists_with_fixes
  17: rust_analyzer::handlers::request::handle_code_action_resolve
  18: std::panicking::try
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

# Note
If one of the default methods is removed then the Quick Fix action works fine.

**Comment by lnicola** [comment]
Fixed by https://github.com/rust-lang/rust-analyzer/pull/17805.
