### ISSUE TITLE
Request codeLens/resolve failed (very simple 100% repro included!)

### ISSUE THREAD

**Issue by darksylinc** [rust-lang/rust-analyzer#16108]
Using Visual Studio Code with rust-analyzer extension I get the following panic:

```
Panic context:
> 
version: 0.3.1766-standalone
request: codeLens/resolve CodeLens {
    range: Range {
        start: Position {
            line: 13,
            character: 11,
        },
        end: Position {
            line: 13,
            character: 32,
        },
    },
    command: None,
    data: Some(
        Object {
            "version": Number(37),
            "kind": Object {
                "impls": Object {
                    "textDocument": Object {
                        "uri": String("file:///home/matias/WMI/test/rust2/src/main.rs"),
                    },
                    "position": Object {
                        "line": Number(13),
                        "character": Number(11),
                    },
                },
            },
        },
    ),
}

thread 'Worker' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/line-index-0.1.0-pre.1/src/lib.rs:148:35:
invalid offset
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:168:5
   3: core::panicking::panic_str
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:152:5
   4: core::option::expect_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/option.rs:1988:5
   5: rust_analyzer::lsp::to_proto::range
   6: rust_analyzer::lsp::to_proto::location
   7: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   8: rust_analyzer::lsp::to_proto::code_lens
   9: rust_analyzer::handlers::request::handle_code_lens_resolve
  10: std::panicking::try
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 8:36:47 PM] Request codeLens/resolve failed.
  Message: request handler panicked: invalid offset
  Code: -32603 

```

Trying to hover over a variable with the mouse cursor results in a crash. **It seems rust analyzer really doesn't like the 2nd struct (but defining just one fixes the problem):**

```rust
#[macro_use]
extern crate rocket;

use rocket::serde::Serialize;

#[derive(Debug, FromForm, Serialize)]
#[serde(crate = "rocket::serde")]
struct AuthParam<'a> {
    pub username: Option<&'a str>,
}

#[derive(Debug, FromForm, Serialize)]
#[serde(crate = "rocket::serde")]
pub struct RegisterAccountParams<'a> {
    pub username: Option<&'a str>,
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![])
}
```

**rust-analyzer version**: 0.3.1766-standalone

**rustc version**: rustc 1.74.1 (a28077b28 2023-12-04)

**relevant settings**:
```
CARGO_HOME=/home/matias/.local/share/cargo
RUSTUP_HOME=/home/matias/.local/share/rustup
```

# Repro

[bug_repro.7z.zip](https://github.com/rust-lang/rust-analyzer/files/13654216/bug_repro.7z.zip)

**Note:** The file is a 7z file not zip. Github won't let me upload it with 7z extension. Just rename the file to bug_repro.7z and extract it.

**Comment by Veykril** [comment]
This is fixed on the latest nightly release
