### ISSUE TITLE
ice: `None` in crates/hir-def/src/generics.rs

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-analyzer#16281]
````rust
struct Foo<T>(T);

trait GoodBye {
    type Forget;
}
impl<T> GoodBye for T {
    type Forget = ();
}

trait NeedsWf<'a, 'b> {
    type Assoc;
}

impl<'a, 'b#[cfg(lifetime)] NeedsWf<'a, 'a> for Map<<&'a MessageListeners<'b> as GoodBye>::Forget> {
    type Assoc = &'a &'b ();
}
````

`rust-analyzer highlight < file.rs`

```
thread 'main' panicked at crates/hir-def/src/generics.rs:605:33:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/panicking.rs:144:5
   3: <hir_def::GenericDefId as hir_def::child_by_source::ChildBySource>::child_by_source_to
   4: <hir::semantics::source_to_def::SourceToDefCtx>::cache_for
   5: <hir::semantics::source_to_def::SourceToDefCtx>::lifetime_param_to_def
   6: <syntax::ast::generated::nodes::LifetimeParam as hir::semantics::ToDef>::to_def
   7: <ide_db::defs::NameClass>::classify_lifetime
   8: <ide_db::defs::IdentClass>::classify_lifetime
   9: ide::syntax_highlighting::highlight
  10: <ide::Analysis>::highlight_as_html
  11: <rust_analyzer::cli::flags::Highlight>::run
  12: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
rust-analyzer 1.77.0-nightly (595bc6f 2024-01-05)

```

**Comment by matthiaskrgr** [comment]
smaller repro:
```rust
trait NeedsWf<'a, 'b> {}

impl<'a, 'b#[cfg(lifetime)] NeedsWf<'a, 'a>  {}
```

**Comment by Veykril** [comment]
This is fixed now
