### ISSUE TITLE
Rust Analyzer instantly crashes

### ISSUE THREAD

**Issue by joelawm** [rust-lang/rust-analyzer#16429]
I have been trying for several days to figure out what is wrong with Rust analyzer on my system. I have not found a similar post on GitHub Issues or just from googling that is similar.  I have tried downgrading VS code and Rust analyzer. I have disabled all other extensions. Completely uninstalled vscode and the removed .vscode directory. I have tried the flatpack version. I have tried apt upgrade and update. I have tried cargo clean and deleting the node_modules library (its a tauri app). I have tried everything I can think of at this point but there seems to be something wrong with my rust at a system level. Notably even Better Toml LSP was breaking. So there seems to be something wrong at a system level. If anyone has any ideas i'm all ears. Thank you logs and system info below!

Here are the Output logs
```
2024-01-25 12:00:54.744 [info] Extension host with pid 13597 started
2024-01-25 12:00:54.744 [info] Skipping acquiring lock for /home/deltagi/.config/Code/User/workspaceStorage/0c6f0e22309da5a4c90548c4ee285c6b.
2024-01-25 12:00:54.841 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-01-25 12:00:54.918 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-01-25 12:00:54.919 [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
2024-01-25 12:00:54.954 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-01-25 12:00:54.966 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-01-25 12:00:54.986 [info] ExtensionService#_doActivateExtension rust-lang.rust-analyzer, startup: true, activationEvent: 'workspaceContains:*/Cargo.toml,*/rust-project.json'
2024-01-25 12:00:55.323 [info] Extension host with pid 13675 started
2024-01-25 12:00:55.323 [info] Skipping acquiring lock for /home/deltagi/.config/Code/User/workspaceStorage/0c6f0e22309da5a4c90548c4ee285c6b.
2024-01-25 12:00:55.325 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-01-25 12:00:55.329 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-01-25 12:00:55.353 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-01-25 12:00:55.354 [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
2024-01-25 12:00:55.362 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-01-25 12:00:55.372 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-01-25 12:00:55.401 [info] ExtensionService#_doActivateExtension rust-lang.rust-analyzer, startup: true, activationEvent: 'workspaceContains:*/Cargo.toml,*/rust-project.json'
2024-01-25 12:00:55.690 [info] Extension host with pid 13738 started
2024-01-25 12:00:55.690 [info] Skipping acquiring lock for /home/deltagi/.config/Code/User/workspaceStorage/0c6f0e22309da5a4c90548c4ee285c6b.
2024-01-25 12:00:55.693 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-01-25 12:00:55.695 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2024-01-25 12:00:55.712 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-01-25 12:00:55.712 [info] ExtensionService#_doActivateExtension vscode.npm, startup: true, activationEvent: 'workspaceContains:package.json'
2024-01-25 12:00:55.721 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-01-25 12:00:55.731 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-01-25 12:00:55.762 [info] ExtensionService#_doActivateExtension rust-lang.rust-analyzer, startup: true, activationEvent: 'workspaceContains:*/Cargo.toml,*/rust-project.json'
```

Here are the logs directly from my Dev Console
```
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-python.python' wants API proposal 'registerIssueDataProvider' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
log.ts:421  INFO Started local extension host with pid 13597.
abstractExtensionService.ts:786 Extension host (LocalProcess pid: 13597) terminated unexpectedly. Code: 132, Signal: unknown
yb @ abstractExtensionService.ts:786
yb @ nativeExtensionService.ts:167
xb @ abstractExtensionService.ts:778
(anonymous) @ abstractExtensionService.ts:751
y @ event.ts:1148
fire @ event.ts:1179
J @ localProcessExtensionHost.ts:517
(anonymous) @ localProcessExtensionHost.ts:282
y @ event.ts:1148
fire @ event.ts:1179
ne @ ipc.ts:675
t @ ipc.ts:743
s @ ipc.ts:732
(anonymous) @ ipc.ts:549
y @ event.ts:1148
z @ event.ts:1159
fire @ event.ts:1183
ue @ event.ts:559
emit @ VM544 sandbox_bundle:2
onMessage @ VM544 sandbox_bundle:2
log.ts:441   ERR Extension host (LocalProcess pid: 13597) terminated unexpectedly. No extensions were activated.
log.ts:421  INFO Automatically restarting the extension host.
log.ts:441   ERR Canceled: Canceled
    at Object.v [as $6] (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:11:1032)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:15738
    at Array.forEach (<anonymous>)
    at m.dispose (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:15676)
    at s.dispose (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:27632)
    at ee.sb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2718:21279)
    at ee.yb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2719:1013)
    at ee.yb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2719:9109)
    at ee.xb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2719:855)
    at o.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2719:417)
    at u.y (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at A.J (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:10189)
    at o.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:6260)
    at u.y (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at ne (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:721)
    at M.t (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:1511)
    at M.s (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:1405)
    at o.value (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:615:1340)
    at u.y (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.z (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at Function.ue (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:56462)
webWorkerExtensionHostIframe.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
log.ts:421  INFO Started local extension host with pid 13675.
log.ts:441   ERR No registered selector for ID: ms-vscode.npm-command
abstractExtensionService.ts:786 Extension host (LocalProcess pid: 13675) terminated unexpectedly. Code: 0, Signal: unknown
yb @ abstractExtensionService.ts:786
yb @ nativeExtensionService.ts:167
xb @ abstractExtensionService.ts:778
(anonymous) @ abstractExtensionService.ts:751
y @ event.ts:1148
fire @ event.ts:1179
J @ localProcessExtensionHost.ts:517
(anonymous) @ localProcessExtensionHost.ts:282
y @ event.ts:1148
fire @ event.ts:1179
ne @ ipc.ts:675
t @ ipc.ts:743
s @ ipc.ts:732
(anonymous) @ ipc.ts:549
y @ event.ts:1148
z @ event.ts:1159
fire @ event.ts:1183
ue @ event.ts:559
emit @ VM544 sandbox_bundle:2
onMessage @ VM544 sandbox_bundle:2
log.ts:441   ERR Extension host (LocalProcess pid: 13675) terminated unexpectedly. No extensions were activated.
log.ts:421  INFO Automatically restarting the extension host.
log.ts:421  INFO Started local extension host with pid 13738.
webWorkerExtensionHostIframe.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
log.ts:441   ERR No registered selector for ID: ms-vscode.npm-command
abstractExtensionService.ts:786 Extension host (LocalProcess pid: 13738) terminated unexpectedly. Code: 132, Signal: unknown
yb @ abstractExtensionService.ts:786
yb @ nativeExtensionService.ts:167
xb @ abstractExtensionService.ts:778
(anonymous) @ abstractExtensionService.ts:751
y @ event.ts:1148
fire @ event.ts:1179
J @ localProcessExtensionHost.ts:517
(anonymous) @ localProcessExtensionHost.ts:282
y @ event.ts:1148
fire @ event.ts:1179
ne @ ipc.ts:675
t @ ipc.ts:743
s @ ipc.ts:732
(anonymous) @ ipc.ts:549
y @ event.ts:1148
z @ event.ts:1159
fire @ event.ts:1183
ue @ event.ts:559
emit @ VM544 sandbox_bundle:2
onMessage @ VM544 sandbox_bundle:2
log.ts:441   ERR Extension host (LocalProcess pid: 13738) terminated unexpectedly. No extensions were activated.
notificationsAlerts.ts:42 Extension host terminated unexpectedly 3 times within the last 5 minutes.
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
y @ event.ts:1148
z @ event.ts:1159
fire @ event.ts:1183
addNotification @ notifications.ts:204
notify @ notificationService.ts:175
prompt @ notificationService.ts:253
yb @ nativeExtensionService.ts:232
xb @ abstractExtensionService.ts:778
(anonymous) @ abstractExtensionService.ts:751
y @ event.ts:1148
fire @ event.ts:1179
J @ localProcessExtensionHost.ts:517
(anonymous) @ localProcessExtensionHost.ts:282
y @ event.ts:1148
fire @ event.ts:1179
ne @ ipc.ts:675
t @ ipc.ts:743
s @ ipc.ts:732
(anonymous) @ ipc.ts:549
y @ event.ts:1148
z @ event.ts:1159
fire @ event.ts:1183
ue @ event.ts:559
emit @ VM544 sandbox_bundle:2
onMessage @ VM544 sandbox_bundle:2
log.ts:421  INFO [perf] Render performance baseline is 14ms
webviewElement.ts:513 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:513
M @ overlayWebview.ts:218
claim @ overlayWebview.ts:120
Db @ extensionEditor.ts:720
await in Db (async)
Gb @ extensionEditor.ts:863
await in Gb (async)
Cb @ extensionEditor.ts:690
Bb @ extensionEditor.ts:675
Ab @ extensionEditor.ts:636
zb @ extensionEditor.ts:577
await in zb (async)
setInput @ extensionEditor.ts:470
await in setInput (async)
S @ editorPanes.ts:445
L @ editorPanes.ts:270
openEditor @ editorPanes.ts:146
(anonymous) @ editorGroupView.ts:1111
Eb @ editorGroupView.ts:1135
Db @ editorGroupView.ts:1093
openEditor @ editorGroupView.ts:999
openEditor @ editorService.ts:551
open @ extensionsWorkbenchService.ts:1082
Tc @ extensionsViews.ts:1035
(anonymous) @ extensionsViews.ts:208
y @ event.ts:1148
fire @ event.ts:1179
(anonymous) @ event.ts:259
y @ event.ts:1148
fire @ event.ts:1179
(anonymous) @ event.ts:152
y @ event.ts:1148
fire @ event.ts:1179
j @ listService.ts:778
g @ listService.ts:749
(anonymous) @ listService.ts:705
y @ event.ts:1148
fire @ event.ts:1179
(anonymous) @ event.ts:118
y @ event.ts:1148
fire @ event.ts:1179
u @ listWidget.ts:783
(anonymous) @ event.ts:169
y @ event.ts:1148
fire @ event.ts:1179
(anonymous) @ event.ts:118
y @ event.ts:1148
fire @ event.ts:1179
C @ event.ts:40
index.html?id=d2a28d0b-9125-4626-b297-e41cd1c3ca02&origin=c0ac4380-4a8b-4f78-bd70-f9d31889397c&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&disableServiceWorker=true:1003 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ index.html?id=d2a28d0b-9125-4626-b297-e41cd1c3ca02&origin=c0ac4380-4a8b-4f78-bd70-f9d31889397c&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&disableServiceWorker=true:1003
```
Rust Analyzer Version: v0.3.1815
Rustc: 1.75
Node and NPM: 21.6.1, and 10.4.0
OS: Pop os
CPU: 7950x with avx512 turned off (not sure if this matters, didnt change anything)

**Comment by davidbarsky** [comment]
I don't know what the issue is, but this line seems suspicious:

```
log.ts:441   ERR Extension host (LocalProcess pid: 13597) terminated unexpectedly. No extensions were activated.
log.ts:421  INFO Automatically restarting the extension host.
log.ts:441   ERR Canceled: Canceled
```

For whatever reason, the VS Code extension host isn't able to start correctly, which indicates to me that it's not an issue with rust-analyzer or Rust, but with either the extension host or whatever you're running the extension host _in_. This, unfortunately, isn't an issue that rust-analyzer can help you with.

**Comment by joelawm** [comment]
@davidbarsky This only happens with Rust Analyzer though, if I load all 39 other extensions they all run fine, rust analyzer breaks almost everything though. Is there another level of logs im missing?

**Comment by joelawm** [comment]
For those following [141280](https://github.com/microsoft/vscode/issues/141280#issuecomment-1912418050) is the fix I used to fix this temporarily till a major release is made.
