### ISSUE TITLE
A spurious panic: index out of bounds: the len is 1 but the index is 1

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust-analyzer#16423]
**rust-analyzer version**: 0.3.1815-standalone

**rustc version**: rustc 1.76.0-nightly (2f8d81f9d 2023-11-21)

**relevant settings**: not sure what is relevant.

Got this r-a crash today:
```
Panic context:
> fetch_native_diagnostics

thread 'Worker' panicked at /__w/rust-analyzer/rust-analyzer/crates/span/src/map.rs:69:19:
index out of bounds: the len is 1 but the index is 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:190:5
   3: hir_expand::mod_path::convert_path
   4: hir_def::item_tree::lower::Ctx::lower_macro_call
   5: hir_def::item_tree::lower::Ctx::lower_mod_item
   6: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   7: hir_def::item_tree::lower::Ctx::lower_module_items
   8: hir_def::item_tree::ItemTree::file_item_tree_query
   9: salsa::Cycle::catch
  10: salsa::derived::slot::Slot<Q,MP>::execute
  11: salsa::derived::slot::Slot<Q,MP>::read
  12: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  13: <DB as hir_def::db::DefDatabase>::file_item_tree
  14: hir_def::nameres::collector::DefCollector::collect_macro_expansion
  15: hir_def::nameres::collector::collect_defs
  16: hir_def::nameres::DefMap::crate_def_map_query
  17: salsa::Cycle::catch
  18: salsa::derived::slot::Slot<Q,MP>::execute
  19: salsa::derived::slot::Slot<Q,MP>::read
  20: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  21: <DB as hir_def::db::DefDatabase>::crate_def_map_query
  22: hir_def::db::crate_def_map_wait
  23: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
  24: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro
  25: hir_def::nameres::collector::DefCollector::resolve_import
  26: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  27: hir_def::nameres::collector::collect_defs
  28: hir_def::nameres::DefMap::crate_def_map_query
  29: salsa::Cycle::catch
  30: salsa::derived::slot::Slot<Q,MP>::execute
  31: salsa::derived::slot::Slot<Q,MP>::read
  32: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  33: <DB as hir_def::db::DefDatabase>::crate_def_map_query
  34: hir_def::db::crate_def_map_wait
  35: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
  36: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro
  37: hir_def::nameres::collector::DefCollector::resolve_import
  38: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  39: hir_def::nameres::collector::collect_defs
  40: hir_def::nameres::DefMap::crate_def_map_query
  41: salsa::Cycle::catch
  42: salsa::derived::slot::Slot<Q,MP>::execute
  43: salsa::derived::slot::Slot<Q,MP>::read
  44: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  45: <DB as hir_def::db::DefDatabase>::crate_def_map_query
  46: hir_def::db::crate_def_map_wait
  47: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
  48: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro
  49: hir_def::nameres::collector::DefCollector::resolve_import
  50: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  51: hir_def::nameres::collector::collect_defs
  52: hir_def::nameres::DefMap::crate_def_map_query
  53: salsa::Cycle::catch
  54: salsa::derived::slot::Slot<Q,MP>::execute
  55: salsa::derived::slot::Slot<Q,MP>::read
  56: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  57: <DB as hir_def::db::DefDatabase>::crate_def_map_query
  58: hir_def::db::crate_def_map_wait
  59: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
  60: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro
  61: hir_def::nameres::collector::DefCollector::resolve_import
  62: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  63: hir_def::nameres::collector::collect_defs
  64: hir_def::nameres::DefMap::crate_def_map_query
  65: salsa::Cycle::catch
  66: salsa::derived::slot::Slot<Q,MP>::execute
  67: salsa::derived::slot::Slot<Q,MP>::read
  68: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  69: <DB as hir_def::db::DefDatabase>::crate_def_map_query
  70: hir_def::db::crate_def_map_wait
  71: hir_def::nameres::collector::DefCollector::import_macros_from_extern_crate
  72: hir_def::nameres::collector::ModCollector::collect::{{closure}}
  73: hir_def::nameres::collector::ModCollector::collect
  74: hir_def::nameres::collector::collect_defs
  75: hir_def::nameres::DefMap::crate_def_map_query
  76: salsa::Cycle::catch
  77: salsa::derived::slot::Slot<Q,MP>::execute
  78: salsa::derived::slot::Slot<Q,MP>::read
  79: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  80: <DB as hir_def::db::DefDatabase>::crate_def_map_query
  81: hir_def::db::crate_def_map_wait
  82: hir::semantics::source_to_def::SourceToDefCtx::file_to_def
  83: ide_diagnostics::diagnostics
  84: salsa::Cancelled::catch
  85: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  86: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  87: rust_analyzer::diagnostics::fetch_native_diagnostics
  88: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.3.1815-standalone
request: textDocument/codeLens CodeLensParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/loc/waffle/rust-j/compiler/rustc_codegen_ssa/src/mir/rvalue.rs",
            query: None,
            fragment: None,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}
```

It was crashing like that continuesly until the client stopped. After reloading vscode window it did not crash anymore. Not sure what to make of it, since I can't reproduce the issue...

**Comment by Veykril** [comment]
Sounds like an incremental corruption, did you add a dependency to your project while r-a was running? (if yes its definitely a known issue)

**Comment by Veykril** [comment]
Even if not, you saying this kept occurring until a restart is pretty much a given that this is the same bug, will close as a dupe there are a few issues regarding the bug open (its presumably a salsa bug).

**Comment by WaffleLapkin** [comment]
> its presumably a salsa bug

Oh no D:
