### ISSUE TITLE
rust-analyzer fresh install from VSCode marketplace failing

### ISSUE THREAD

**Issue by troynguyen8** [rust-lang/rust-analyzer#16804]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
* Trying to download v0.4.1875

**rustc version**: (eg. output of `rustc -V`)
* rustc 1.76.0 (07dca489a 2024-02-04)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)
* Essentially fresh install, no atypical settings

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))

**how reproduce**: 
* Freshly install Rust on MacOS
  * `$ curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh`
  * `$ xcode-select --install`
  * Go to VSCode market place listing for rust-analyzer, install via deeplink in VSCode client https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer
Observe error:
```
[2024-03-10 15:47:38.950] [renderer1] [error] ["Error: Server returned 404","    at i (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:29:132070)","    at j.getManifestFromRawExtensionVersion (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:43957)","    at async j.getEngine (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:50:297)","    at async j.getCompatibleExtension (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:38488)","    at async O.getCompatibleVersion (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:12306)","    at async O.checkAndGetCompatibleVersion (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:11921)","    at async O.doInstallFromGallery (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:4251)","    at async O.installFromGallery (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:2790)"]
[2024-03-10 15:47:38.962] [renderer1] [error] Server returned 404: Error: Server returned 404
    at i (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:29:132070)
    at j.getManifestFromRawExtensionVersion (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:43957)
    at async j.getEngine (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:50:297)
    at async j.getCompatibleExtension (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:38488)
    at async O.getCompatibleVersion (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:12306)
    at async O.checkAndGetCompatibleVersion (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:11921)
    at async O.doInstallFromGallery (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:4251)
    at async O.installFromGallery (vscode-file://vscode-app/private/var/folders/1m/88h9kvgn2qqbmyn47cpzt0y80000gn/T/AppTranslocation/1464E210-7963-4E5F-AC67-B8BB0AA62232/d/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:48:2790)
```

**Comment by troynguyen8** [comment]
After uninstalling VSCode and reinstalling it, this error went away. My first install was kept within my Mac's downloads directory, and second install was moved to "Applications" folder
