### ISSUE TITLE
Rust Analyzer keeps throwing Bootstrap Error

### ISSUE THREAD

**Issue by WarrenN1** [rust-lang/rust-analyzer#16881]
Here is my system error and the Bootstrap Error from the rust analyzer after updating VSCODE. I updated VSCODE today and everything broke.

Using the version of rust-analyzer from a week earlier works. It is solely the new one that fails.
```
cargo 1.71.1 (7f1d04c00 2023-07-29)
release: 1.71.1
commit-hash: 7f1d04c0053083b98fa50b69b6f56e339b0556a8
commit-date: 2023-07-29
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.1 vendored)
libcurl: 8.0.1-DEV (sys:0.4.61+curl-8.0.1 vendored ssl:OpenSSL/1.1.1t)
ssl: OpenSSL 1.1.1t  7 Feb 2023
os: CentOS 8.0.0 [64-bit]
```
```
INFO [3/18/2024, 6:52:55 PM]: Starting language client
INFO [3/18/2024, 6:52:55 PM]: Using server binary at /home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer
INFO [3/18/2024, 6:52:55 PM]: /home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer --version: {
  status: 1,
  signal: null,
  output: [
    null,
    '',
    "/home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer)\n" +
      "/home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer)\n"
  ],
  pid: 466627,
  stdout: '',
  stderr: "/home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer)\n" +
    "/home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by /home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer)\n"
}
ERROR [3/18/2024, 6:52:55 PM]: Bootstrap error [Error: Failed to execute /home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/server/rust-analyzer --version
	at Jy (/home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/out/main.js:343:3165)
	at async qa.getOrCreateClient (/home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/out/main.js:357:2420)
	at async qa.start (/home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/out/main.js:357:4095)
	at async /home/warrenniles/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1885-linux-x64/out/main.js:376:174
	at async u.h (/home/warrenniles/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/workbench/api/node/extensionHostProcess.js:150:184831)]
```

**Comment by emmanuelrflores** [comment]
I am receiving the same error. v0.3.1877 is what's working for me

**Comment by davidbarsky** [comment]
The error is `/lib64/libm.so.6: version `GLIBC_2.29' not found`, which is occurring due to rust-analyzer increasing the minimum glibc version to 2.31. This was [announced here](https://rust-analyzer.github.io/thisweek/2024/03/18/changelog-225.html#announcement).

I don't expect we'll take any action at this time, I'm sorry about that.

**Comment by Jungle666** [comment]
i got error message , libm.so.6: version `GLIBC_2.29' not found,how to fix?

**Comment by Jungle666** [comment]
> i got error message , libm.so.6: version `GLIBC_2.29' not found,how to fix?
 back to v0.3.1877 that's ok.

**Comment by LongZoz** [comment]
I also encountered a similar error after executing./rust-analyzer. My version of the OS is Ubuntu18.04:
./rust-analyzer: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by./rust-analyzer)
./rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.29' not found (required by./rust-analyzer)
./rust-analyzer: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by./rust-analyzer)

> > i got error message , libm.so.6: version `GLIBC_2.29' not found,how to fix?我收到错误消息，libm.so.6：找不到版本“GLIBC_2.29”，如何修复？
> > back to v0.3.1877 that's ok.回到 v0.3.1877 没关系。

**Comment by lnicola** [comment]
@Jungle666, @LongZoz #16793
