### ISSUE TITLE
 internal error: entered unreachable code: `ExpandDatabase::macro_arg` called with `MacroCallKind::Derive`

### ISSUE THREAD

**Issue by lovasoa** [rust-lang/rust-analyzer#16931]
Hello ! 
 I don't really have the time to investigate this, but I thought it may be useful to report this:

The error comes from https://docs.rs/tempfile/latest/tempfile/struct.NamedTempFile.html

```
Error - 12:09:15 PM] Request textDocument/semanticTokens/full failed.
  Message: request handler panicked: internal error: entered unreachable code: `ExpandDatabase::macro_arg` called with `MacroCallKind::Derive`
  Code: -32603 
Panic context:
> 
version: 0.4.1890-standalone (7ef7f442f 2024-03-21)
request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/olojkine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-multipart-0.6.1/src/form/tempfile.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 10,
            character: 0,
        },
        end: Position {
            line: 86,
            character: 46,
        },
    },
}

thread 'Worker' panicked at crates/hir-expand/src/db.rs:438:13:
internal error: entered unreachable code: `ExpandDatabase::macro_arg` called with `MacroCallKind::Derive`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
   2: <hir_expand::db::MacroArgQuery as salsa::plumbing::QueryFunction>::execute
   3: salsa::Cycle::catch
   4: salsa::derived::slot::Slot<Q,MP>::execute
   5: salsa::derived::slot::Slot<Q,MP>::read
   6: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
   7: <DB as hir_expand::db::ExpandDatabase>::macro_arg
   8: hir_expand::ExpansionInfo::new
   9: hir::semantics::SemanticsImpl::descend_into_macros_impl::{{closure}}
  10: hir::semantics::SemanticsImpl::descend_into_macros_impl
  11: hir::semantics::SemanticsImpl::descend_into_macros_single
  12: ide::syntax_highlighting::traverse
  13: ide::syntax_highlighting::highlight
  14: salsa::Cancelled::catch
  15: ide::Analysis::highlight_range
  16: rust_analyzer::handlers::request::handle_semantic_tokens_range
  17: std::panicking::try
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**rust-analyzer version**: `rust-analyzer version: 0.4.1890-standalone (7ef7f442f 2024-03-21)`

**rustc version**: (eg. output of `rustc -V`) `rustc 1.77.0 (aedd173a2 2024-03-17)`

**Comment by lovasoa** [comment]
I can reproduce this inside my own code:

```
[Error - 12:20:01 PM] Request textDocument/semanticTokens/range failed.
  Message: request handler panicked: internal error: entered unreachable code: `ExpandDatabase::macro_arg` called with `MacroCallKind::Derive`
  Code: -32603 
Panic context:
> 
version: 0.4.1890-standalone (7ef7f442f 2024-03-21)
request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/olojkine/dev/sqlpage/src/webserver/http.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 263,
            character: 0,
        },
        end: Position {
            line: 337,
            character: 20,
        },
    },
}

thread 'Worker' panicked at crates/hir-expand/src/db.rs:438:13:
internal error: entered unreachable code: `ExpandDatabase::macro_arg` called with `MacroCallKind::Derive`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
   2: <hir_expand::db::MacroArgQuery as salsa::plumbing::QueryFunction>::execute
   3: salsa::Cycle::catch
   4: salsa::derived::slot::Slot<Q,MP>::execute
   5: salsa::derived::slot::Slot<Q,MP>::read
   6: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
   7: <DB as hir_expand::db::ExpandDatabase>::macro_arg
   8: hir_expand::ExpansionInfo::new
   9: hir::semantics::SemanticsImpl::descend_into_macros_impl::{{closure}}
  10: hir::semantics::SemanticsImpl::descend_into_macros_impl
  11: hir::semantics::SemanticsImpl::descend_into_macros_single
  12: ide::syntax_highlighting::traverse
  13: ide::syntax_highlighting::highlight
  14: salsa::Cancelled::catch
  15: ide::Analysis::highlight_range
  16: rust_analyzer::handlers::request::handle_semantic_tokens_range
  17: std::panicking::try
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 12:20:01 PM] Request textDocument/semanticTokens/range failed.
  Message: request handler panicked: internal error: entered unreachable code: `ExpandDatabase::macro_arg` called with `MacroCallKind::Derive`
  Code: -32603 
```

https://github.com/lovasoa/SQLpage

**Comment by Veykril** [comment]
This is already fixed on the latest releases
