### ISSUE TITLE
rust-analyzer reports errors when dbg! macros are present in saved code

### ISSUE THREAD

**Issue by mylvghb** [rust-lang/rust-analyzer#17261]
Example: 

```
use std::env;

fn main() {
    let args: Vec<String> = env::args().collect();
    dbg!(args);
}
```

Screenshots:

![image](https://github.com/rust-lang/rust-analyzer/assets/35945793/d848bed6-1595-43ae-a997-cb1785a0d69b)

Detail Description:

Panic context:
> 
version: 0.3.1958-standalone (5bf2f85c8 2024-05-09)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/e%3A/study/rust/minigrep/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 6,
            character: 0,
        },
    },
}

thread 'Worker' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\line-index-0.1.1\src\lib.rs:111:35:
invalid offset
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: core::panicking::panic_display<ref$<str$> >
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:197
   3: core::panicking::panic_str
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:172
   4: core::option::expect_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\option.rs:1995
   5: rust_analyzer::lsp::to_proto::inlay_hint
   6: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   7: core::iter::adapters::try_process
   8: rust_analyzer::handlers::request::handle_inlay_hints
   9: std::panicking::try
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 14:07:05] Request textDocument/inlayHint failed.
  Message: request handler panicked: invalid offset
  Code: -32603 
Panic context:
> 
version: 0.3.1958-standalone (5bf2f85c8 2024-05-09)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/e%3A/study/rust/minigrep/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 0,
            character: 0,
        },
        end: Position {
            line: 6,
            character: 0,
        },
    },
}

thread 'Worker' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\line-index-0.1.1\src\lib.rs:111:35:
invalid offset
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: core::panicking::panic_display<ref$<str$> >
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:197
   3: core::panicking::panic_str
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:172
   4: core::option::expect_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\option.rs:1995
   5: rust_analyzer::lsp::to_proto::inlay_hint
   6: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   7: core::iter::adapters::try_process
   8: rust_analyzer::handlers::request::handle_inlay_hints
   9: std::panicking::try
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 14:07:07] Request textDocument/inlayHint failed.
  Message: request handler panicked: invalid offset
  Code: -32603

**Comment by roife** [comment]
I can't reproduce it on 5bf2f85c8054d80424899fa581db1b192230efb5.

**Comment by mylvghb** [comment]
If there is no `dbg!` macro in the code, **ra** works fine.

**Comment by mylvghb** [comment]
> I can't reproduce it on [5bf2f85](https://github.com/rust-lang/rust-analyzer/commit/5bf2f85c8054d80424899fa581db1b192230efb5).

If there is no `dbg!` macro in the code, **ra** works fine.

**Comment by YuniqueUnic** [comment]
This error is on my computer... 

> version: 0.3.2188-standalone
> request: textDocument/inlayHint InlayHintParams {
>     work_done_progress_params: WorkDoneProgressParams {
>         work_done_token: None,
>     },
>     text_document: TextDocumentIdentifier {
>         uri: Url {
>             scheme: "file",
>             cannot_be_a_base: false,
>             username: "",
>             password: None,
>             host: None,
>             port: None,
>             path: "/root/vscodeprojs/rustprojs/rustpad/examples/rust-one-hour/lib.rs",
>             query: None,
>             fragment: None,
>         },
>     },
>     range: Range {
>         start: Position {
>             line: 0,
>             character: 0,
>         },
>         end: Position {
>             line: 48,
>             character: 0,
>         },
>     },
> }
> 
> thread 'Worker' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/line-index-0.1.2/src/lib.rs:111:35:
> invalid offset
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: core::option::expect_failed
>    3: rust_analyzer::lsp::to_proto::inlay_hint
>    4: <alloc::vec::into_iter::IntoIter<T,A> as core::iter::traits::iterator::Iterator>::try_fold
>    5: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
>    6: core::iter::adapters::try_process
>    7: rust_analyzer::handlers::request::handle_inlay_hints
>    8: core::ops::function::FnOnce::call_once{{vtable.shim}}
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [Error - 11:19:04 PM] Request textDocument/inlayHint failed.
>   Message: request handler panicked: invalid offset
>   Code: -32603
