### ISSUE TITLE
Assertion panic from chalk

### ISSUE THREAD

**Issue by EliiasG** [rust-lang/rust-analyzer#17288]
**rust-analyzer version**: 0.3.1958-standalone (5bf2f85c8 2024-05-09)

**rustc version**: 1.78.0 (9b00956e5 2024-04-29)

**editor or extension**: VSCode
This issue might be related to #6956
I keep getting this error, and rust-analyzer keeps restarting:
I am editing a workspace with errors in multiple crates, maybe that is a problem?
```
Panic context:
> 
version: 0.3.1958-standalone (5bf2f85c8 2024-05-09)
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Projects/Git/modula/crates/modula_render/src/lib.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 76,
            character: 40,
        },
        end: Position {
            line: 76,
            character: 40,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
        trigger_kind: Some(
            Automatic,
        ),
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chalk-ir-0.97.0\src\lib.rs:2236:9:
assertion `left == right` failed
  left: 1
 right: 0
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: core::panicking::assert_failed_inner
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:343
   3: core::panicking::assert_failed
   4: chalk_ir::Binders<T>::substitute
   5: hir_ty::mir::ProjectionElem<V,T>::projected_ty
   6: hir_ty::mir::borrowck::borrowck_query
   7: hir_ty::mir::borrowck::borrowck_query
   8: hir_ty::mir::borrowck::borrowck_query
   9: salsa::Cycle::catch
  10: salsa::derived::slot::Slot<Q,MP>::evict
  11: salsa::derived::slot::Slot<Q,MP>::read
  12: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  13: <DB as hir_ty::db::HirDatabase>::borrowck
  14: hir::DefWithBody::diagnostics
  15: hir::ModuleDef::diagnostics
  16: hir::Module::diagnostics
  17: ide_diagnostics::diagnostics
  18: std::panicking::try
  19: ide::Analysis::assists_with_fixes
  20: rust_analyzer::handlers::request::handle_code_action
  21: std::panicking::try
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ChayimFriedman2** [comment]
No Chalk - no panic :)
