### ISSUE TITLE
[Error - 10:32:44 PM] Request textDocument/inlayHint failed.

### ISSUE THREAD

**Issue by dheijl** [rust-lang/rust-analyzer#17376]
VSCode 1.90.0, with RA extension, just opening project https://github.com/dheijl/swyh-rs/ triggers this RA panic:
```
Panic context:
> 
version: 0.4.1990-standalone (913371fb0 2024-06-08)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Users/Danny/source/rust/projects/swyh-rs/src/utils/audiodevices.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 203,
            character: 0,
        },
        end: Position {
            line: 299,
            character: 0,
        },
    },
}

thread 'Worker' panicked at crates\hir\src\semantics.rs:1516:13:


Failed to lookup NAME@9313..9320 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..9887
known nodes: SOURCE_FILE@0..63734, SOURCE_FILE@0..636, SOURCE_FILE@0..82806, SOURCE_FILE@0..9887, SOURCE_FILE@0..123487, SOURCE_FILE@0..8939


stack backtrace:
Panic context:
> 
version: 0.4.1990-standalone (913371fb0 2024-06-08)
request: textDocument/inlayHint InlayHintParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Users/Danny/source/rust/projects/swyh-rs/src/utils/audiodevices.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 203,
            character: 0,
        },
        end: Position {
            line: 299,
            character: 0,
        },
    },
}

thread 'Worker' panicked at crates\hir\src\semantics.rs:1516:13:


Failed to lookup NAME@9313..9320 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..9887
known nodes: SOURCE_FILE@0..63734, SOURCE_FILE@0..636, SOURCE_FILE@0..82806, SOURCE_FILE@0..9887, SOURCE_FILE@0..123487, SOURCE_FILE@0..8939


   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: hir::semantics::SemanticsImpl::find_file
   3: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   4: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   5: ide::inlay_hints::param_name::hints
   6: ide::inlay_hints::hints
   7: ide::inlay_hints::inlay_hints
   8: std::panicking::try
   9: rust_analyzer::handlers::request::handle_inlay_hints
  10: std::panicking::try
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: hir::semantics::SemanticsImpl::find_file
[Error - 10:32:44 PM] Request textDocument/inlayHint failed.
  Message: request handler panicked: 

Failed to lookup NAME@9313..9320 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..9887
known nodes: SOURCE_FILE@0..63734, SOURCE_FILE@0..636, SOURCE_FILE@0..82806, SOURCE_FILE@0..9887, SOURCE_FILE@0..123487, SOURCE_FILE@0..8939


  Code: -32603 
   3: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   4: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   5: ide::inlay_hints::param_name::hints
   6: ide::inlay_hints::hints
   7: ide::inlay_hints::inlay_hints
   8: std::panicking::try
   9: rust_analyzer::handlers::request::handle_inlay_hints
  10: std::panicking::try
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 10:32:44 PM] Request textDocument/inlayHint failed.
  Message: request handler panicked: 

Failed to lookup NAME@9313..9320 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..9887
known nodes: SOURCE_FILE@0..63734, SOURCE_FILE@0..636, SOURCE_FILE@0..82806, SOURCE_FILE@0..9887, SOURCE_FILE@0..123487, SOURCE_FILE@0..8939


  Code: -32603 
```

**Comment by Lurgrid** [comment]
I've been getting the same error since I did the update

**Comment by rubin55** [comment]
Can confirm, have the same issue, which started after I upgraded to `v0.3.1992` of the VSCode rust-analyzer extension. Reverting back to the VSCode rust-analyzer extension with version `v0.3.1983` fixed it for me.

**Comment by lnicola** [comment]
A new stable release is now out (`v0.3.1995`), fixing this and #17378.
