### ISSUE TITLE
Canceling a `flycheck` task causes a panic in the Flycheck thread.

### ISSUE THREAD

**Issue by maxbrunsfeld** [rust-lang/rust-analyzer#17445]
**rust-analyzer version**:  rust-analyzer 0.3.2002-standalone (6b8b8ff4c 2024-06-14)

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: VSCode

**relevant settings**: nothing custom

**repository link (if public, optional)**: https://github.com/zed-industries/zed

**Repro steps**:

* Save a file
* See `cargo check` in the status bar
* Run `rust-analyzer: cancel running flychecks` (or click the status bar item, then click `Cancel`)
* :boom: See this in the Rust-analyzer logs:

```
thread 'Flycheck' panicked at crates/flycheck/src/lib.rs:331:69:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: flycheck::FlycheckActor::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'Worker' panicked at crates/flycheck/src/lib.rs:142:78:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: std::panicking::try
   4: core::ops::function::FnOnce::call_once{{vtable.shim}}
```

* save the file again
* see this in the logs

```
2024-06-18T00:54:14.269543Z ERROR rust_analyzer::handlers::notification: flycheck task panicked: Any { .. }
thread 'Worker' panicked at crates/flycheck/src/lib.rs:142:78:
called `Result::unwrap()` on an `Err` value: "SendError(..)"
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: std::panicking::try
   4: core::ops::function::FnOnce::call_once{{vtable.shim}}
```

**Comment by Veykril** [comment]
Broke in https://github.com/rust-lang/rust-analyzer/pull/17056
