### ISSUE TITLE
thread 'Worker' panicked at crates/span/src/ast_id.rs:203:21

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/rust-analyzer#17575]
**rust-analyzer version**: rust-analyzer version: 0.3.2029-standalone (a5b21ea0a 2024-07-07) [/home/gh-Alexendoo/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.2029-linux-arm64/server/rust-analyzer]

**rustc version**: rustc 1.79.0 (129f3b996 2024-06-10)

**editor or extension**: VSCode 1.91.0

**relevant settings** `./x setup vscode`

I don't have a good reproducer here, but I was on https://github.com/rust-lang/rust/commit/d81987661a06ae8d49a5f014f81824c655e87768 editing `compiler/rustc_passes/src/liveness.rs` when a lot of failed request notifications started appearing in quick succession. There were many panic messages but they all look similar, here's one of them:

```
thread 'Worker' panicked at crates/span/src/ast_id.rs:203:21:
Can't find FN@683..1004 in AstIdMap:
[SyntaxNodePtr { kind: MACRO_ITEMS, range: 0..1003 }, SyntaxNodePtr { kind: CONST, range: 0..683 }, SyntaxNodePtr { kind: FN, range: 683..1003 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 10..682 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 750..1003 }, SyntaxNodePtr { kind: IMPL, range: 11..681 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 845..1002 }, SyntaxNodePtr { kind: FN, range: 124..680 }, SyntaxNodePtr { kind: MACRO_CALL, range: 846..1000 }, SyntaxNodePtr { kind: SELF_PARAM, range: 151..155 }, SyntaxNodePtr { kind: PARAM, range: 156..197 }, SyntaxNodePtr { kind: PARAM, range: 198..223 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 254..680 }, SyntaxNodePtr { kind: BLOCK_EXPR, range: 309..678 }, SyntaxNodePtr { kind: MACRO_CALL, range: 428..441 }]
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: span::ast_id::AstIdMap::erased_ast_id
   3: hir_def::item_tree::lower::Ctx::lower_function
   4: hir_def::item_tree::lower::Ctx::lower_mod_item
   5: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   6: hir_def::item_tree::lower::Ctx::lower_module_items
   7: hir_def::item_tree::ItemTree::file_item_tree_query
   8: salsa::Cycle::catch
   9: salsa::derived::slot::Slot<Q,MP>::execute
  10: salsa::derived::slot::Slot<Q,MP>::read
  11: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  12: <DB as hir_def::db::DefDatabase>::file_item_tree
  13: hir_def::nameres::collector::DefCollector::collect_macro_expansion
  14: hir_def::nameres::collector::collect_defs
  15: hir_def::nameres::DefMap::crate_def_map_query
  16: salsa::Cycle::catch
  17: salsa::derived::slot::Slot<Q,MP>::execute
  18: salsa::derived::slot::Slot<Q,MP>::read
  19: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  20: <DB as hir_def::db::DefDatabase>::crate_def_map
  21: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
  22: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro
  23: hir_def::nameres::collector::DefCollector::resolve_import
  24: alloc::vec::in_place_collect::from_iter_in_place
  25: hir_def::nameres::collector::collect_defs
  26: hir_def::nameres::DefMap::crate_def_map_query
  27: salsa::Cycle::catch
  28: salsa::derived::slot::Slot<Q,MP>::execute
  29: salsa::derived::slot::Slot<Q,MP>::read
  30: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  31: <DB as hir_def::db::DefDatabase>::crate_def_map
  32: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro_single
  33: hir_def::nameres::path_resolution::<impl hir_def::nameres::DefMap>::resolve_path_fp_with_macro
  34: hir_def::nameres::collector::DefCollector::resolve_import
  35: alloc::vec::in_place_collect::from_iter_in_place
  36: hir_def::nameres::collector::collect_defs
  37: hir_def::nameres::DefMap::crate_def_map_query
  38: salsa::Cycle::catch
  39: salsa::derived::slot::Slot<Q,MP>::execute
  40: salsa::derived::slot::Slot<Q,MP>::read
  41: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
  42: <DB as hir_def::db::DefDatabase>::crate_def_map
  43: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  44: ide::parent_module::crates_for
  45: salsa::Cancelled::catch
  46: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.3.2029-standalone (a5b21ea0a 2024-07-07)
request: textDocument/semanticTokens/full/delta SemanticTokensDeltaParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/gh-Alexendoo/rust/compiler/rustc_passes/src/liveness.rs",
            query: None,
            fragment: None,
        },
    },
    previous_result_id: "50",
}
```

**Comment by Veykril** [comment]
We have upgraded salsa now, so this issue report is stale with that and hopefully "fixed"
