### ISSUE TITLE
Panic when analyzing incorrect code

### ISSUE THREAD

**Issue by bragov4ik** [rust-lang/rust-analyzer#17710]
`rust-analyzer` panics with ```Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod 0;``` in pre-release

**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) `rust-analyzer version: 0.4.2049-standalone (c02a4a31e 2024-07-25)`

**rustc version**: (eg. output of `rustc -V`) `rustc 1.79.0 (129f3b996 2024-06-10)`

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; for users of other editors, provide the distribution if applicable) `VSCode (v0.4.2049 (pre-release))`

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`) doesn't seem applicable (let me know if needed)

**repository link (if public, optional)**: not applicable

**code snippet to reproduce**: 
```rust
struct Kek {}

impl Kek {
    pub fn foo(self) {
        // uncommenting the line below results in panic
        // self.0
    }
}

fn main() {}

```

<details><summary><strong>Full language server output</strong></summary>
<p>

```
Panic context:
> fetch_native_diagnostics

thread 'Worker' panicked at crates/syntax/src/ast/make.rs:113:5:
Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod 0;
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: syntax::ast::make::name
   3: ide_diagnostics::handlers::unresolved_field::unresolved_field
   4: ide_diagnostics::diagnostics
   5: salsa::Cancelled::catch
   6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   8: rust_analyzer::diagnostics::fetch_native_diagnostics
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 0.4.2049-standalone (c02a4a31e 2024-07-25)
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/Users/bragov4ik/Documents/rust/test-field/src/main.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 5,
            character: 14,
        },
        end: Position {
            line: 5,
            character: 14,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
        trigger_kind: Some(
            Automatic,
        ),
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at crates/syntax/src/ast/make.rs:113:5:
Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod 0;
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: syntax::ast::make::name
   3: ide_diagnostics::handlers::unresolved_field::unresolved_field
   4: ide_diagnostics::diagnostics
   5: std::panicking::try
   6: ide::Analysis::assists_with_fixes
   7: rust_analyzer::handlers::request::handle_code_action
   8: std::panicking::try
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</p>
</details>

**Comment by Veykril** [comment]
Panic location is https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-diagnostics/src/handlers/unresolved_field.rs#L155

Makes sense this panics now, given the symbol interning now always returns the contents of a name. We gotta check whether the name is an ident or an integer now
