### ISSUE TITLE
Failed assertion "immutable tree" in rowan::cursor::detach()

### ISSUE THREAD

**Issue by krobelus** [rust-lang/rust-analyzer#18295]
```
$ rust-analyzer --version
rust-analyzer 1 (2b750da1a1 2024-10-06)
$ rustc -V
rustc 1.81.0 (eeb90cda1 2024-09-04)
```

I was working on https://github.com/GitoxideLabs/gitoxide in kakoune when rust-analyzer crashed
Still trying  to find reproduction steps..

Unfortunately there is not much backtrace even though I have `RUST_BACKTRACE=1` in my env.

I wonder why does `rust-analyzer` not generate coredumps when it crashes?
That would allow me to attach a debugger to see the full backtrace post-mortem.
It should be as simple as adding `std::process::abort()` to the panic handler passed to `set_hook()`.
I guess this specific case is a panic in the request handler so IDK.

Pasting the error log below though it's probably not enough.
(There is a message about a bogus workspace folder path which I'll fix momentarily)

<details>

```
*** This is the debug buffer, where debug info will be written ***
LSP: INFO kak-lsp server starting. To increase log verbosity, run 'set g lsp_debug true'
LSP: INFO Starting Language server rust-analyzer as `rust-analyzer`
remote client connected: 4
remote client connected: 5
LSP: WARN Language server stderr: 2024-10-13T16:20:16.224257Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix/tests/gix/repository/mod.rs
LSP: WARN Language server stderr: 2024-10-13T16:20:17.334543Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix/src/dirwalk/iter.rs
LSP: INFO Starting Language server marksman as `marksman server`
LSP: WARN Language server stderr: [18:20:18 INF] <LSP Entry> Starting Marksman LSP server: {}
LSP: WARN Language server stderr: 2024-10-13T16:20:19.369858Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix/src/repository/dirwalk.rs
LSP: WARN Language server stderr: [18:20:19 WRN] <ServerUtil> Workspace folder is bogus: {"root": "RootPath (AbsPath \"/home/johannes/git/gitoxide/etc/monthlies/2024\")"}
Error: LSP already enabled at global scope
LSP: WARN Language server stderr: 2024-10-13T16:20:26.861673Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix/src/dirwalk/mod.rs
Error: no matches found: 'fn dirwalk'
LSP: WARN Language server stderr: 2024-10-13T16:30:05.857758Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix-dir/src/walk/function.rs
LSP: WARN Language server stderr: 2024-10-13T16:30:29.058849Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix-dir/src/walk/readdir.rs
LSP: WARN Language server stderr: 2024-10-13T16:33:02.815148Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix-dir/src/walk/classify.rs
LSP: WARN Language server stderr: 2024-10-13T16:33:46.548011Z ERROR duplicate DidOpenTextDocument: /home/johannes/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/path.rs
LSP: WARN Language server stderr: 2024-10-13T16:34:29.854096Z ERROR duplicate DidOpenTextDocument: /home/johannes/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bstr-1.10.0/src/bstring.rs
LSP: WARN Language server stderr: 2024-10-13T16:34:56.402403Z ERROR duplicate DidOpenTextDocument: /home/johannes/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs
LSP: WARN Language server stderr: 2024-10-13T16:34:58.138079Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix-dir/src/walk/mod.rs
LSP: WARN Language server stderr: Panic context:
LSP: WARN Language server stderr: > 
LSP: WARN Language server stderr: version: 1 (2b750da1a1 2024-10-06)
LSP: WARN Language server stderr: request: textDocument/codeAction CodeActionParams {
LSP: WARN Language server stderr:     text_document: TextDocumentIdentifier {
LSP: WARN Language server stderr:         uri: Url {
LSP: WARN Language server stderr:             scheme: "file",
LSP: ERRO Error response from server rust-analyzer: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "request handler panicked: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))", data: None }, id: Num(1303) }
LSP: WARN Language server stderr:             cannot_be_a_base: false,
LSP: WARN Language server stderr:             username: "",
LSP: WARN Language server stderr:             password: None,
LSP: WARN Language server stderr:             host: None,
LSP: WARN Language server stderr:             port: None,
LSP: WARN Language server stderr:             path: "/home/johannes/git/gitoxide/gix-dir/src/walk/function.rs",
LSP: WARN Language server stderr:             query: None,
LSP: WARN Language server stderr:             fragment: None,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     range: Range {
LSP: WARN Language server stderr:         start: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 22,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:         end: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 22,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     context: CodeActionContext {
LSP: WARN Language server stderr:         diagnostics: [],
LSP: WARN Language server stderr:         only: None,
LSP: WARN Language server stderr:         trigger_kind: Some(
LSP: WARN Language server stderr:             Automatic,
LSP: WARN Language server stderr:         ),
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     work_done_progress_params: WorkDoneProgressParams {
LSP: WARN Language server stderr:         work_done_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     partial_result_params: PartialResultParams {
LSP: WARN Language server stderr:         partial_result_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr: }
LSP: WARN Language server stderr: 
LSP: WARN Language server stderr: thread 'Worker' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.15/src/cursor.rs:824:9:
LSP: WARN Language server stderr: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))
LSP: WARN Language server stderr: stack backtrace:
LSP: WARN Language server stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
LSP: WARN Language server stderr: Panic context:
LSP: ERRO Error response from server rust-analyzer: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "request handler panicked: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))", data: None }, id: Num(1306) }
LSP: WARN Language server stderr: > 
LSP: WARN Language server stderr: version: 1 (2b750da1a1 2024-10-06)
LSP: WARN Language server stderr: request: textDocument/codeAction CodeActionParams {
LSP: WARN Language server stderr:     text_document: TextDocumentIdentifier {
LSP: WARN Language server stderr:         uri: Url {
LSP: WARN Language server stderr:             scheme: "file",
LSP: WARN Language server stderr:             cannot_be_a_base: false,
LSP: WARN Language server stderr:             username: "",
LSP: WARN Language server stderr:             password: None,
LSP: WARN Language server stderr:             host: None,
LSP: WARN Language server stderr:             port: None,
LSP: WARN Language server stderr:             path: "/home/johannes/git/gitoxide/gix-dir/src/walk/function.rs",
LSP: WARN Language server stderr:             query: None,
LSP: WARN Language server stderr:             fragment: None,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     range: Range {
LSP: WARN Language server stderr:         start: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 18,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:         end: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 18,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     context: CodeActionContext {
LSP: WARN Language server stderr:         diagnostics: [],
LSP: WARN Language server stderr:         only: None,
LSP: WARN Language server stderr:         trigger_kind: Some(
LSP: WARN Language server stderr:             Automatic,
LSP: WARN Language server stderr:         ),
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     work_done_progress_params: WorkDoneProgressParams {
LSP: WARN Language server stderr:         work_done_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     partial_result_params: PartialResultParams {
LSP: WARN Language server stderr:         partial_result_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr: }
LSP: WARN Language server stderr: 
LSP: WARN Language server stderr: thread 'Worker' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.15/src/cursor.rs:824:9:
LSP: WARN Language server stderr: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))
LSP: WARN Language server stderr: stack backtrace:
LSP: WARN Language server stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
LSP: WARN Language server stderr: Panic context:
LSP: ERRO Error response from server rust-analyzer: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "request handler panicked: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))", data: None }, id: Num(1309) }
LSP: WARN Language server stderr: > 
LSP: WARN Language server stderr: version: 1 (2b750da1a1 2024-10-06)
LSP: WARN Language server stderr: request: textDocument/codeAction CodeActionParams {
LSP: WARN Language server stderr:     text_document: TextDocumentIdentifier {
LSP: WARN Language server stderr:         uri: Url {
LSP: WARN Language server stderr:             scheme: "file",
LSP: WARN Language server stderr:             cannot_be_a_base: false,
LSP: WARN Language server stderr:             username: "",
LSP: WARN Language server stderr:             password: None,
LSP: WARN Language server stderr:             host: None,
LSP: WARN Language server stderr:             port: None,
LSP: WARN Language server stderr:             path: "/home/johannes/git/gitoxide/gix-dir/src/walk/function.rs",
LSP: WARN Language server stderr:             query: None,
LSP: WARN Language server stderr:             fragment: None,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     range: Range {
LSP: WARN Language server stderr:         start: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 14,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:         end: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 14,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     context: CodeActionContext {
LSP: WARN Language server stderr:         diagnostics: [],
LSP: WARN Language server stderr:         only: None,
LSP: WARN Language server stderr:         trigger_kind: Some(
LSP: WARN Language server stderr:             Automatic,
LSP: WARN Language server stderr:         ),
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     work_done_progress_params: WorkDoneProgressParams {
LSP: WARN Language server stderr:         work_done_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     partial_result_params: PartialResultParams {
LSP: WARN Language server stderr:         partial_result_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr: }
LSP: WARN Language server stderr: 
LSP: WARN Language server stderr: thread 'Worker' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.15/src/cursor.rs:824:9:
LSP: WARN Language server stderr: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))
LSP: WARN Language server stderr: stack backtrace:
LSP: WARN Language server stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
LSP: ERRO Error response from server rust-analyzer: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "request handler panicked: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))", data: None }, id: Num(1312) }
LSP: WARN Language server stderr: Panic context:
LSP: WARN Language server stderr: > 
LSP: WARN Language server stderr: version: 1 (2b750da1a1 2024-10-06)
LSP: WARN Language server stderr: request: textDocument/codeAction CodeActionParams {
LSP: WARN Language server stderr:     text_document: TextDocumentIdentifier {
LSP: WARN Language server stderr:         uri: Url {
LSP: WARN Language server stderr:             scheme: "file",
LSP: WARN Language server stderr:             cannot_be_a_base: false,
LSP: WARN Language server stderr:             username: "",
LSP: WARN Language server stderr:             password: None,
LSP: WARN Language server stderr:             host: None,
LSP: WARN Language server stderr:             port: None,
LSP: WARN Language server stderr:             path: "/home/johannes/git/gitoxide/gix-dir/src/walk/function.rs",
LSP: WARN Language server stderr:             query: None,
LSP: WARN Language server stderr:             fragment: None,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     range: Range {
LSP: WARN Language server stderr:         start: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 10,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:         end: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 10,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     context: CodeActionContext {
LSP: WARN Language server stderr:         diagnostics: [],
LSP: WARN Language server stderr:         only: None,
LSP: WARN Language server stderr:         trigger_kind: Some(
LSP: WARN Language server stderr:             Automatic,
LSP: WARN Language server stderr:         ),
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     work_done_progress_params: WorkDoneProgressParams {
LSP: WARN Language server stderr:         work_done_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     partial_result_params: PartialResultParams {
LSP: WARN Language server stderr:         partial_result_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr: }
LSP: WARN Language server stderr: 
LSP: WARN Language server stderr: thread 'Worker' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.15/src/cursor.rs:824:9:
LSP: WARN Language server stderr: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))
LSP: WARN Language server stderr: stack backtrace:
LSP: WARN Language server stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
LSP: WARN Language server stderr: Panic context:
LSP: ERRO Error response from server rust-analyzer: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "request handler panicked: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))", data: None }, id: Num(1315) }
LSP: WARN Language server stderr: > 
LSP: WARN Language server stderr: version: 1 (2b750da1a1 2024-10-06)
LSP: WARN Language server stderr: request: textDocument/codeAction CodeActionParams {
LSP: WARN Language server stderr:     text_document: TextDocumentIdentifier {
LSP: WARN Language server stderr:         uri: Url {
LSP: WARN Language server stderr:             scheme: "file",
LSP: WARN Language server stderr:             cannot_be_a_base: false,
LSP: WARN Language server stderr:             username: "",
LSP: WARN Language server stderr:             password: None,
LSP: WARN Language server stderr:             host: None,
LSP: WARN Language server stderr:             port: None,
LSP: WARN Language server stderr:             path: "/home/johannes/git/gitoxide/gix-dir/src/walk/function.rs",
LSP: WARN Language server stderr:             query: None,
LSP: WARN Language server stderr:             fragment: None,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     range: Range {
LSP: WARN Language server stderr:         start: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 6,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:         end: Position {
LSP: WARN Language server stderr:             line: 198,
LSP: WARN Language server stderr:             character: 6,
LSP: WARN Language server stderr:         },
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     context: CodeActionContext {
LSP: WARN Language server stderr:         diagnostics: [],
LSP: WARN Language server stderr:         only: None,
LSP: WARN Language server stderr:         trigger_kind: Some(
LSP: WARN Language server stderr:             Automatic,
LSP: WARN Language server stderr:         ),
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     work_done_progress_params: WorkDoneProgressParams {
LSP: WARN Language server stderr:         work_done_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr:     partial_result_params: PartialResultParams {
LSP: WARN Language server stderr:         partial_result_token: None,
LSP: WARN Language server stderr:     },
LSP: WARN Language server stderr: }
LSP: WARN Language server stderr: 
LSP: WARN Language server stderr: thread 'Worker' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rowan-0.15.15/src/cursor.rs:824:9:
LSP: WARN Language server stderr: immutable tree: !(emit_ignored.is_none() && matches!(info.status, entry::Status::Ignored(_)))
LSP: WARN Language server stderr: stack backtrace:
LSP: WARN Language server stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
LSP: WARN Language server stderr: 2024-10-13T16:39:07.908628Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix-dir/src/lib.rs
LSP: WARN Language server stderr: 2024-10-13T16:39:41.756303Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix-dir/tests/walk_utils/mod.rs
LSP: WARN Language server stderr: 2024-10-13T16:40:00.623527Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gix-status/src/index_as_worktree_with_renames/mod.rs
LSP: WARN Language server stderr: 2024-10-13T16:40:11.381881Z ERROR duplicate DidOpenTextDocument: /home/johannes/git/gitoxide/gitoxide-core/src/repository/clean.rs
LSP: WARN Language server stderr: 2024-10-13T16:40:20.279729Z ERROR duplicate DidOpenTextDocument: /home/johannes/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/fs.rs
LSP: WARN Language server stderr: 2024-10-13T16:40:32.795740Z ERROR duplicate DidOpenTextDocument: /home/johannes/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/fs.rs
LSP: WARN Language server stderr: 2024-10-13T16:40:48.520863Z ERROR duplicate DidOpenTextDocument: /home/johannes/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs
Error: no matches found: '\bFileType\b'
LSP: ERRO Error response from server rust-analyzer: Failure { jsonrpc: Some(V2), error: Error { code: ServerError(-32801), message: "content modified", data: None }, id: Num(2331) }
```

</details>

**Comment by ludwig-jb** [comment]
Encountered this, too, on `rust-analyzer 1.87.0 (17067e9ac6d 2025-05-09)`. 

Here's a simple reproducer:
```rust
pub fn foo(a: u32, , b: u32){
    todo!()
}
```
Notice how there are two commas one after the other. To trigger the bug, one needs to resolve (`codeAction/resolve`) the "Flip comma" code action on the second comma. For example, both in neovim and vs code, you can do this by placing the cursor on the second comma and invoking the "Flip comma" code action.

Backtrace:
```
thread 'Worker6' panicked at /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rowan-0.15.15/src/cursor.rs:824:9:
immutable tree: b: u32
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rowan::cursor::<impl rowan::utility_types::NodeOrToken<rowan::cursor::SyntaxNode,rowan::cursor::SyntaxToken>>::detach
   3: rowan::cursor::SyntaxNode::splice_children
   4: rowan::api::SyntaxNode<L>::splice_children
   5: syntax::syntax_editor::edit_algo::apply_edits
   6: ide_db::source_change::SourceChangeBuilder::commit
   7: ide_db::source_change::SourceChangeBuilder::finish
   8: ide_assists::assist_context::Assists::add_impl
   9: ide_assists::assist_context::Assists::add
  10: ide_assists::handlers::flip_comma::flip_comma
  11: ide_assists::assists
  12: salsa::cancelled::Cancelled::catch
  13: ide::Analysis::assists_with_fixes
  14: rust_analyzer::handlers::request::handle_code_action_resolve
  15: core::ops::function::FnOnce::call_once{{vtable.shim}}
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by A4-Tacks** [comment]
It seems to have been fixed
