### ISSUE TITLE
"No Compilation Artifacts" after compiling

### ISSUE THREAD

**Issue by hexadecimal233** [rust-lang/rust-analyzer#18311]
**rust-analyzer version**: `rust-analyzer version: 0.4.2148-standalone (418c1365e 2024-10-15) [c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\server\rust-analyzer.exe]`

**rustc version**: `rustc 1.80.0 (051478957 2024-07-21)`

**editor or extension**: Windows, VSCode, Rust-Analyzer, Arduino Community Edition, CodeLLDB

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: `https://github.com/hexadecimal233/esp32c3-singing-stepper`

When trying to execute `rust-analyzer: Debug` every time after modifying the code in the repo above, the artifact shows up in the folder but VSCode gives me the following error:

```
2024-10-17 00:08:11.118 [error] Error: No compilation artifacts
    at n.executableFromArgs (c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:42:1530)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Y_ (c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:42:7964)
    at Hv (c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:42:6267)
    at Io (c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:42:4867)
    at c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:90:5063
    at T0.h (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837)
    at T0.h (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837) rust-analyzer.debugSingle {"value":"rust-lang.rust-analyzer","_lower":"rust-lang.rust-analyzer"}
2024-10-17 00:08:11.118 [error] Error: No compilation artifacts
    at n.executableFromArgs (c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:42:1530)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Y_ (c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:42:7964)
    at Hv (c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:42:6267)
    at Io (c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:42:4867)
    at c:\Users\User\.vscode\extensions\rust-lang.rust-analyzer-0.4.2148-win32-x64\out\main.js:90:5063
    at T0.h (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837)
    at T0.h (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837) __vsc6b3040b2-be47-4f48-a370-72694b3698fa undefined
2024-10-17 00:08:29.340 [info] ExtensionService#_doActivateExtension emilast.LogFileHighlighter, startup: false, activationEvent: 'onLanguage:log'
```

and fails to execute the artifact, while rerunning fixes the errors.

PS: This **only happens** in this repo somehow, havent got a similar error in my other repos

**Comment by NiekAukes** [comment]
Same here, except for me it happens on all my repos

2026-03-09 14:26:05.026 [error] Error: No compilation artifacts
	at t.executableFromArgs (/home/niek/.vscode/extensions/rust-lang.rust-analyzer-0.4.2820-linux-x64/out/main.js:64:1457)
	at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
	at async YN (/home/niek/.vscode/extensions/rust-lang.rust-analyzer-0.4.2820-linux-x64/out/main.js:64:7584)
	at async JS (/home/niek/.vscode/extensions/rust-lang.rust-analyzer-0.4.2820-linux-x64/out/main.js:64:5891)
	at async Qa (/home/niek/.vscode/extensions/rust-lang.rust-analyzer-0.4.2820-linux-x64/out/main.js:64:4747)
	at async /home/niek/.vscode/extensions/rust-lang.rust-analyzer-0.4.2820-linux-x64/out/main.js:114:5487
	at async CA.h (file:///snap/code/224/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:41743)
	at async CA.h (file:///snap/code/224/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:41743) rust-analyzer.debugSingle undefined
