### ISSUE TITLE
Syntax Error: expected a block

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rust-analyzer#18732]
Very weird - basic code reporting a Syntax error, but it runs fine via Cargo run :)

**rust-analyzer version**: rust-analyzer version: 0.3.2220-standalone (27e824fad4 2024-12-15) [c:\Users\robertc\.vscode\extensions\rust-lang.rust-analyzer-0.3.2220-win32-x64\server\rust-analyzer.exe]

**rustc version**: rustc 1.83.0 (90b35a623 2024-11-26)

**editor or extension**: VSCode Version 0.3.2220

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

```
rustup show
$ rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\robertc\.rustup

...

installed targets for active toolchain
--------------------------------------

x86_64-pc-windows-msvc
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.83.0 (90b35a623 2024-11-26)
```

**code snippet to reproduce**: 
```rust
use std::collections::HashMap;

use crate::eval::Value;

pub struct Environment {
    values: HashMap<String, Value>,
}

impl Environment {
    pub fn new() -> Self {
        Self {
            values: HashMap::new(),
        }
    }

    pub fn define(&mut self, name: String, value: Value) {
        self.values.insert(name, value);
    }

    pub fn get(&self, name: &str) -> Result<Value, Box<dyn std::error::Error>> {
        self.values
            .get(name)
            .cloned()
            .ok_or_else(|| format!("Undefined variable {name}").into())
    }
}

```

Reports these problems:

```
[{
	"resource": "/c:/Users/robertc/Documents/src/codecrafters-interpreter-rust/src/environment.rs",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "syntax-error",
		"target": {
			"$mid": 1,
			"path": "/stable/reference/",
			"scheme": "https",
			"authority": "doc.rust-lang.org"
		}
	},
	"severity": 8,
	"message": "Syntax Error: expected a block",
	"source": "rust-analyzer",
	"startLineNumber": 17,
	"startColumn": 16,
	"endLineNumber": 17,
	"endColumn": 16
}]
```

and
```
[{
	"resource": "/c:/Users/robertc/Documents/src/codecrafters-interpreter-rust/src/environment.rs",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "E0308",
		"target": {
			"$mid": 1,
			"path": "/stable/error_codes/E0308.html",
			"scheme": "https",
			"authority": "doc.rust-lang.org"
		}
	},
	"severity": 8,
	"message": "expected String, found &str",
	"source": "rust-analyzer",
	"startLineNumber": 18,
	"startColumn": 28,
	"endLineNumber": 18,
	"endColumn": 32
}]
```

![Image](https://github.com/user-attachments/assets/27c72edc-4624-4bf7-8d85-6cf10167bedd)

**Comment by ChayimFriedman2** [comment]
When some obviously-not-syntax-error reports a SyntaxError, that usually happens in my experience after the diagnostics request has panicked. So, did you saw a popup about the server panicking before?

**Comment by rbtcollins** [comment]
I don't recall one, but the subtle corner popups in vscode rarely attract my eyeballs.

I can see this in the RA LSP output:
```
Panic context:
> 
version: 0.3.2220-standalone (27e824fad4 2024-12-15)
request: textDocument/diagnostic DocumentDiagnosticParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/c%3A/Users/robertc/Documents/src/codecrafters-interpreter-rust/src/environment.rs",
            query: None,
            fragment: None,
        },
    },
    identifier: None,
    previous_result_id: None,
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread 'Worker' panicked at crates\syntax\src\ast\make.rs:117:5:
Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod self;
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:74
   2: syntax::ast::make::name
   3: ide_diagnostics::handlers::unresolved_field::unresolved_field
   4: ide_diagnostics::semantic_diagnostics
   5: ide_diagnostics::full_diagnostics
   6: ra_salsa::Cancelled::catch
   7: ide::Analysis::full_diagnostics
   8: rust_analyzer::handlers::request::handle_document_diagnostics
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 3:40:10 PM] Request textDocument/diagnostic failed.
  Message: request handler panicked: Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod self;
  Code: -32603 
[Error - 3:40:10 PM] Document pull failed for text document file:///c%3A/Users/robertc/Documents/src/codecrafters-interpreter-rust/src/environment.rs
  Message: request handler panicked: Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod self;
  Code: -32603 
```

But I don't know if its connected.

I have restarted the LSP but the problem remained.

**Comment by ChayimFriedman2** [comment]
Yes this means there was a panic in diagnostics. Restarting rust-analyzer should work unless it panics again.

**Comment by Veykril** [comment]
Its definitely a bug that a panic there can cause us to leak (never clear) diagnostics

**Comment by ChayimFriedman2** [comment]
I think this is because the diagnostics request is not wrapped in `catch_unwind()`.

**Comment by Veykril** [comment]
Ah yes, I was looking at the push model style diagnostic handling, not the pull one that is actually being used. That seems a bit odd then, I'd expect vscode to ask for diagnostics again when the doc changes, causing it clear them afterwards when we give it a proper result back
