### ISSUE TITLE
thread 'Worker' panicked with `invalid offset` when `show outgoing call`

### ISSUE THREAD

**Issue by lh123** [rust-lang/rust-analyzer#18800]
**rust-analyzer version**: 0.3.2237-standalone (59bc7b49d0 2024-12-29) 

**rustc version**: rustc 1.83.0 (90b35a623 2024-11-26)

**editor or extension**: VSCode

**code snippet to reproduce**: 
```rust
fn main() {
    let a  = Some(5).take();
    //               ^^^^  invoke outgoing call on take
}
```
```
thread 'Worker' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\line-index-0.1.2\src/lib.rs:111:35:
invalid offset
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:74
   2: core::panicking::panic_display
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:264
   3: core::option::expect_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\option.rs:2021
   4: rust_analyzer::lsp::to_proto::range
   5: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   6: rust_analyzer::handlers::request::handle_call_hierarchy_outgoing
   7: core::ops::function::FnOnce::call_once{{vtable.shim}}
```

**Comment by lh123** [comment]
may relative: 
https://github.com/rust-lang/rust-analyzer/issues/17762
https://github.com/rust-lang/rust-analyzer/issues/14839
